<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="6">
   <form>meiner</form>
   <lemma>meine</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="7">
     <form>eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="8">
     <form>er</form>
     <lemma>vere</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="5">
       <form>ting</form>
       <lemma>ting</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="1">
         <form>Slike</form>
         <lemma>slik</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>fl</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="2">
         <form>små</form>
         <lemma>liten</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>fl</LM>
         </feats>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="3">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="4">
         <form>rare</form>
         <lemma>rar</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>fl</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="9">
       <form>fint</form>
       <lemma>fin</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>SPRED</deprel>
      </LM>
      <LM order="10">
       <form>å</form>
       <lemma>å</lemma>
       <cpostag>inf-merke</cpostag>
       <postag>inf-merke</postag>
       <deprel>PSUBJ</deprel>
       <childnodes>
        <LM order="11">
         <form>samle</form>
         <lemma>samle</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>inf</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="12">
           <form>på</form>
           <lemma>på</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>viktig</form>
   <lemma>viktig</lemma>
   <cpostag>adj</cpostag>
   <postag>adj</postag>
   <feats>
    <LM>pos</LM>
    <LM>nøyt</LM>
    <LM>ub</LM>
    <LM>eint</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="1">
     <form>Og</form>
     <lemma>og</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>&lt;ikkje-clb&gt;</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="3">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>tek</form>
   <lemma>ta</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Og</form>
     <lemma>og</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>dei</form>
     <lemma>dei</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>fl</LM>
      <LM>hum</LM>
      <LM>akk</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="5">
     <form>til</form>
     <lemma>til</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="6">
       <form>inntekt</form>
       <lemma>inntekt</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>fem</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="7">
         <form>for</form>
         <lemma>for</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="10">
           <form>dag</form>
           <lemma>dag</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
            
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="8">
             <form>ein</form>
             <lemma>ein</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>kvant</LM>
              <LM>mask</LM>
              <LM>eint</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="9">
             <form>god</form>
             <lemma>god</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>tenkjer</form>
   <lemma>tenkje</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="9">
     <form>betyr</form>
     <lemma>bety</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>at</form>
       <lemma>at</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="8">
       <form>så</form>
       <lemma>så</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="6">
         <form>skjer</form>
         <lemma>skje</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>pres</LM>
         </feats>
         <deprel>APP</deprel>
         <childnodes>
          <LM order="4">
           <form>når</form>
           <lemma>når</lemma>
           <cpostag>sbu</cpostag>
           <postag>sbu</postag>
           <deprel>SBU</deprel>
          </LM>
          <LM order="5">
           <form>slikt</form>
           <lemma>slikt</lemma>
           <cpostag>pron</cpostag>
           <postag>pron</postag>
           <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
           </feats>
           <deprel>SUBJ</deprel>
          </LM>
          <LM order="7">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="10">
       <form>det</form>
       <lemma>det</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>nøyt</LM>
        <LM>eint</LM>
       </feats>
       <deprel>FSUBJ</deprel>
      </LM>
      <LM order="13">
       <form>vil</form>
       <lemma>vilje</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="11">
         <form>at</form>
         <lemma>at</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="12">
         <form>verda</form>
         <lemma>verd</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>fem</LM>
          <LM>appell</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="14">
         <form>meg</form>
         <lemma>eg</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>1</LM>
          <LM>eint</LM>
          <LM>hum</LM>
          <LM>akk</LM>
         </feats>
         <deprel>DOBJ</deprel>
        </LM>
        <LM order="15">
         <form>vel</form>
         <lemma>vel</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="16">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="19">
       <form>må</form>
       <lemma>måtte</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="17">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>clb</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="20">
         <form>eg</form>
         <lemma>eg</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>1</LM>
          <LM>eint</LM>
          <LM>hum</LM>
          <LM>nom</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="22">
         <form>tru</form>
         <lemma>tru</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>inf</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="18">
           <form>då</form>
           <lemma>då</lemma>
           <cpostag>adv</cpostag>
           <postag>adv</postag>
           <deprel>ADV</deprel>
          </LM>
          <LM order="21">
           <form>berre</form>
           <lemma>berre</lemma>
           <cpostag>adv</cpostag>
           <postag>adv</postag>
           <deprel>ADV</deprel>
          </LM>
          <LM order="23">
           <form>på</form>
           <lemma>på</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="27">
             <form>blir</form>
             <lemma>bli</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pres</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="24">
               <form>at</form>
               <lemma>at</lemma>
               <cpostag>sbu</cpostag>
               <postag>sbu</postag>
               <deprel>SBU</deprel>
              </LM>
              <LM order="26">
               <form>dagen</form>
               <lemma>dag</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
               </feats>
               <deprel>SUBJ</deprel>
               <childnodes>
                <LM order="25">
                 <form>denne</form>
                 <lemma>denne</lemma>
                 <cpostag>det</cpostag>
                 <postag>det</postag>
                 <feats>
                  <LM>dem</LM>
                  <LM>mask</LM>
                  <LM>eint</LM>
                 </feats>
                 <deprel>DET</deprel>
                </LM>
               </childnodes>
              </LM>
              <LM order="28">
               <form>bra</form>
               <lemma>bra</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>pos</LM>
                <LM>m/f</LM>
                <LM>ub</LM>
                <LM>eint</LM>
               </feats>
               <deprel>SPRED</deprel>
               <childnodes>
                <LM order="29">
                 <form>for</form>
                 <lemma>for</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="30">
                   <form>meg</form>
                   <lemma>eg</lemma>
                   <cpostag>pron</cpostag>
                   <postag>pron</postag>
                   <feats>
                    <LM>pers</LM>
                    <LM>1</LM>
                    <LM>eint</LM>
                    <LM>hum</LM>
                    <LM>akk</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="31">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Som</form>
   <lemma>som</lemma>
   <cpostag>prep</cpostag>
   <postag>prep</postag>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>PUTFYLL</deprel>
     <childnodes>
      <LM order="3">
       <form>dag</form>
       <lemma>dag</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
      <LM order="4">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="7">
       <form>kom</form>
       <lemma>kome</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pret</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="5">
         <form>då</form>
         <lemma>då</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="6">
         <form>eg</form>
         <lemma>eg</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>1</LM>
          <LM>eint</LM>
          <LM>hum</LM>
          <LM>nom</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="8">
         <form>innom</form>
         <lemma>innom</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="9">
           <form>Lykke</form>
           <lemma>Lykke</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="10">
             <form>Kaffebar</form>
             <lemma>Kaffebar</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>FLAT</deprel>
            </LM>
            <LM order="11">
             <form>,</form>
             <lemma>$,</lemma>
             <cpostag>&lt;komma&gt;</cpostag>
             <postag>&lt;komma&gt;</postag>
             <deprel>IK</deprel>
            </LM>
            <LM order="14">
             <form>heim</form>
             <lemma>heim</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>APP</deprel>
             <childnodes>
              <LM order="12">
               <form>min</form>
               <lemma>min</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>poss</LM>
                <LM>mask</LM>
                <LM>eint</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
              <LM order="13">
               <form>andre</form>
               <lemma>andre</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>pos</LM>
                <LM>eint</LM>
                <LM>bu</LM>
                <LM>&lt;ordenstal&gt;</LM>
               </feats>
               <deprel>ATR</deprel>
              </LM>
              <LM order="15">
               <form>her</form>
               <lemma>her</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="16">
                 <form>i</form>
                 <lemma>i</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="17">
                   <form>Måløy</form>
                   <lemma>Måløy</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>prop</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>stod</form>
   <lemma>stå</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="2">
     <form>kanelsnurrar</form>
     <lemma>kanelsnurr</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>fl</LM>
      <LM>samset</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="1">
       <form>Nysteikte</form>
       <lemma>nysteikje</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>&lt;perf-part&gt;</LM>
        <LM>fl</LM>
        <LM>samset</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
      <LM order="3">
       <form>med</form>
       <lemma>med</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="4">
         <form>vaniljekrem</form>
         <lemma>vaniljekrem</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
          <LM>samset</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="7">
       <form>disken</form>
       <lemma>disk</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>plukka</form>
     <lemma>plukke</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="8">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="9">
       <form>eg</form>
       <lemma>eg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>1</LM>
        <LM>eint</LM>
        <LM>hum</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="12">
       <form>tilfeldig</form>
       <lemma>tilfeldig</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>m/f</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>SPRED</deprel>
       <childnodes>
        <LM order="11">
         <form>ein</form>
         <lemma>ein</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>kvant</LM>
          <LM>mask</LM>
          <LM>eint</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="14">
       <form>la</form>
       <lemma>leggje</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pret</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="13">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>clb</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="15">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="16">
           <form>asjettet</form>
           <lemma>asjett</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>nøyt</LM>
            <LM>appell</LM>
            <LM>eint</LM>
            <LM>bu</LM>
            <LM>unorm</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="17">
             <form>mitt</form>
             <lemma>min</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>poss</LM>
              <LM>nøyt</LM>
              <LM>eint</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>kjente</form>
   <lemma>kjenne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="8">
       <form>lukta</form>
       <lemma>lukt</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>fem</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="4">
         <form>den</form>
         <lemma>den</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>fem</LM>
          <LM>eint</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="5">
         <form>søte</form>
         <lemma>søt</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="6">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="7">
         <form>varme</form>
         <lemma>varm</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>satte</form>
     <lemma>setje</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
      <LM>unorm</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="9">
       <form>idet</form>
       <lemma>idet</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="10">
       <form>eg</form>
       <lemma>eg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>1</LM>
        <LM>eint</LM>
        <LM>hum</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="12">
       <form>meg</form>
       <lemma>eg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>1</LM>
        <LM>eint</LM>
        <LM>hum</LM>
        <LM>akk</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
      <LM order="13">
       <form>ned</form>
       <lemma>ned</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="14">
       <form>ved</form>
       <lemma>ved</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="15">
         <form>bordet</form>
         <lemma>bord</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>appell</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="16">
           <form>mitt</form>
           <lemma>min</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>poss</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="17">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>såg</form>
   <lemma>sjå</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Og</form>
     <lemma>og</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>så</form>
     <lemma>så</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="4">
     <form>eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="6">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="6">
   <form>var</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="5">
     <form>vaniljekremen</form>
     <lemma>vaniljekrem</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>eint</LM>
      <LM>bu</LM>
      <LM>samset</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="1">
       <form>den</form>
       <lemma>den</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>dem</LM>
        <LM>mask</LM>
        <LM>eint</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="2">
       <form>gule</form>
       <lemma>gul</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="3">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="4">
       <form>fine</form>
       <lemma>fin</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>forma</form>
     <lemma>forme</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>&lt;perf-part&gt;</LM>
      <LM>m/f</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="8">
       <form>som</form>
       <lemma>som</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="10">
         <form>hjarte</form>
         <lemma>hjarte</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="9">
           <form>eit</form>
           <lemma>ein</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>kvant</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>!</form>
     <lemma>$!</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;utrop&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>tek</form>
   <lemma>ta</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="3">
     <form>eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>som</form>
     <lemma>som</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>OPRED</deprel>
     <childnodes>
      <LM order="6">
       <form>teikn</form>
       <lemma>teikn</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="5">
         <form>eit</form>
         <lemma>ein</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>kvant</LM>
          <LM>nøyt</LM>
          <LM>eint</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>På</form>
   <lemma>på</lemma>
   <cpostag>prep</cpostag>
   <postag>prep</postag>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="5">
     <form>blir</form>
     <lemma>bli</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PUTFYLL</deprel>
     <childnodes>
      <LM order="2">
       <form>at</form>
       <lemma>at</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="4">
       <form>dagen</form>
       <lemma>dag</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="3">
         <form>denne</form>
         <lemma>denne</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>mask</LM>
          <LM>eint</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="6">
       <form>bra</form>
       <lemma>bra</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>m/f</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>SPRED</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>På</form>
   <lemma>på</lemma>
   <cpostag>prep</cpostag>
   <postag>prep</postag>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="4">
     <form>vil</form>
     <lemma>vilje</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PUTFYLL</deprel>
     <childnodes>
      <LM order="2">
       <form>at</form>
       <lemma>at</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="3">
       <form>verda</form>
       <lemma>verd</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>fem</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="5">
       <form>meg</form>
       <lemma>eg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>1</LM>
        <LM>eint</LM>
        <LM>hum</LM>
        <LM>akk</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
      <LM order="6">
       <form>vel</form>
       <lemma>vel</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="7">
       <form>trass</form>
       <lemma>trass</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="9">
         <form>kaos</form>
         <lemma>kaos</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="8">
           <form>alt</form>
           <lemma>all</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>kvant</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="11">
           <form>måtte</form>
           <lemma>måtte</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pret</LM>
           </feats>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="10">
             <form>som</form>
             <lemma>som</lemma>
             <cpostag>sbu</cpostag>
             <postag>sbu</postag>
             <deprel>SBU</deprel>
            </LM>
            <LM order="12">
             <form>finnast</form>
             <lemma>finnast</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>inf</LM>
              <LM>&lt;st-verb&gt;</LM>
             </feats>
             <deprel>INFV</deprel>
             <childnodes>
              <LM order="13">
               <form>i</form>
               <lemma>i</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="14">
                 <form>livet</form>
                 <lemma>liv</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>nøyt</LM>
                  <LM>appell</LM>
                  <LM>eint</LM>
                  <LM>bu</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="15">
                   <form>mitt</form>
                   <lemma>min</lemma>
                   <cpostag>det</cpostag>
                   <postag>det</postag>
                   <feats>
                    <LM>poss</LM>
                    <LM>nøyt</LM>
                    <LM>eint</LM>
                   </feats>
                   <deprel>DET</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
              <LM order="17">
               <form>no</form>
               <lemma>no</lemma>
               <cpostag>adv</cpostag>
               <postag>adv</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="16">
                 <form>nett</form>
                 <lemma>nett</lemma>
                 <cpostag>adv</cpostag>
                 <postag>adv</postag>
                 <deprel>ADV</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>På</form>
   <lemma>på</lemma>
   <cpostag>prep</cpostag>
   <postag>prep</postag>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="4">
     <form>har</form>
     <lemma>ha</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PUTFYLL</deprel>
     <childnodes>
      <LM order="2">
       <form>at</form>
       <lemma>at</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="3">
       <form>eg</form>
       <lemma>eg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>1</LM>
        <LM>eint</LM>
        <LM>hum</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="6">
       <form>ting</form>
       <lemma>ting</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="5">
         <form>vakre</form>
         <lemma>vakker</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>fl</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="7">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="8">
         <form>vente</form>
         <lemma>vente</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>fem</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>I</form>
   <lemma>i</lemma>
   <cpostag>prep</cpostag>
   <postag>prep</postag>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>dag</form>
     <lemma>dag</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>PUTFYLL</deprel>
    </LM>
    <LM order="3">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="4">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="5">
       <form>morgon</form>
       <lemma>morgon</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>dagen</form>
     <lemma>dag</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>eint</LM>
      <LM>bu</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="6">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>&lt;ikkje-clb&gt;</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="8">
       <form>etter</form>
       <lemma>etter</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="9">
         <form>det</form>
         <lemma>det</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>3</LM>
          <LM>nøyt</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
