<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="2">
   <form>greier</form>
   <lemma>greie</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="3">
     <form>han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>mask</LM>
      <LM>eint</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="7">
     <form>legg</form>
     <lemma>leggje</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="5">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="6">
       <form>dei</form>
       <lemma>dei</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>fl</LM>
        <LM>hum</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="8">
       <form>ut</form>
       <lemma>ut</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="9">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="12">
           <form>reisa</form>
           <lemma>reise</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>eint</LM>
            <LM>bu</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="10">
             <form>den</form>
             <lemma>den</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>dem</LM>
              <LM>fem</LM>
              <LM>eint</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="11">
             <form>lange</form>
             <lemma>lang</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>eint</LM>
              <LM>bu</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
            <LM order="14">
             <form>sørover</form>
             <lemma>sørover</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="13">
               <form>vidare</form>
               <lemma>vid</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>komp</LM>
               </feats>
               <deprel>ADV</deprel>
              </LM>
              <LM order="15">
               <form>mot</form>
               <lemma>mot</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>PUTFYLL</deprel>
               <childnodes>
                <LM order="16">
                 <form>Afrika-kysten</form>
                 <lemma>Afrika-kyst</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>eint</LM>
                  <LM>bu</LM>
                  <LM>samset</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="17">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>kjem</form>
   <lemma>kome</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Dei</form>
     <lemma>dei</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>fl</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>til</form>
     <lemma>til</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="4">
       <form>slutt</form>
       <lemma>slutt</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>fram</form>
     <lemma>fram</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="6">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="8">
         <form>rike</form>
         <lemma>rike</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="7">
           <form>eit</form>
           <lemma>ein</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>kvant</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="10">
           <form>har</form>
           <lemma>ha</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pres</LM>
           </feats>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="9">
             <form>som</form>
             <lemma>som</lemma>
             <cpostag>sbu</cpostag>
             <postag>sbu</postag>
             <deprel>SBU</deprel>
            </LM>
            <LM order="11">
             <form>fått</form>
             <lemma>få</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>perf-part</LM>
             </feats>
             <deprel>INFV</deprel>
             <childnodes>
              <LM order="13">
               <form>Mapungubwe</form>
               <lemma>Mapungubwe</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>prop</LM>
               </feats>
               <deprel>DOBJ</deprel>
               <childnodes>
                <LM order="12">
                 <form>namnet</form>
                 <lemma>namn</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>nøyt</LM>
                  <LM>appell</LM>
                  <LM>eint</LM>
                  <LM>bu</LM>
                 </feats>
                 <deprel>APP</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
            <LM order="14">
             <form>,</form>
             <lemma>$,</lemma>
             <cpostag>&lt;komma&gt;</cpostag>
             <postag>&lt;komma&gt;</postag>
             <deprel>IK</deprel>
            </LM>
            <LM order="16">
             <form>ligg</form>
             <lemma>liggje</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pres</LM>
             </feats>
             <deprel>KOORD</deprel>
             <childnodes>
              <LM order="15">
               <form>som</form>
               <lemma>som</lemma>
               <cpostag>sbu</cpostag>
               <postag>sbu</postag>
               <deprel>SBU</deprel>
              </LM>
              <LM order="17">
               <form>på</form>
               <lemma>på</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="18">
                 <form>grensa</form>
                 <lemma>grense</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>fem</LM>
                  <LM>appell</LM>
                  <LM>eint</LM>
                  <LM>bu</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="19">
                   <form>mellom</form>
                   <lemma>mellom</lemma>
                   <cpostag>prep</cpostag>
                   <postag>prep</postag>
                   <deprel>ATR</deprel>
                   <childnodes>
                    <LM order="20">
                     <form>Zimbabwe</form>
                     <lemma>Zimbabwe</lemma>
                     <cpostag>subst</cpostag>
                     <postag>subst</postag>
                     <feats>
                      <LM>prop</LM>
                     </feats>
                     <deprel>PUTFYLL</deprel>
                     <childnodes>
                      <LM order="22">
                       <form>Sør-Afrika</form>
                       <lemma>Sør-Afrika</lemma>
                       <cpostag>subst</cpostag>
                       <postag>subst</postag>
                       <feats>
                        <LM>prop</LM>
                       </feats>
                       <deprel>KOORD</deprel>
                       <childnodes>
                        <LM order="21">
                         <form>og</form>
                         <lemma>og</lemma>
                         <cpostag>konj</cpostag>
                         <postag>konj</postag>
                         <feats>
                          <LM>&lt;ikkje-clb&gt;</LM>
                         </feats>
                         <deprel>KONJ</deprel>
                        </LM>
                       </childnodes>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="23">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>er</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>I</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="2">
       <form>dag</form>
       <lemma>dag</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>staden</form>
     <lemma>stad</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>eint</LM>
      <LM>bu</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>verdsarvminnesmerke</form>
     <lemma>verdsarvminnesmerke</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>eint</LM>
      <LM>samset</LM>
     </feats>
     <deprel>SPRED</deprel>
    </LM>
    <LM order="6">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>skip</form>
   <lemma>skip</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>nøyt</LM>
    <LM>appell</LM>
    <LM>ub</LM>
    <LM>fl</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="1">
     <form>Svære</form>
     <lemma>svær</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>pos</LM>
      <LM>fl</LM>
     </feats>
     <deprel>ATR</deprel>
    </LM>
    <LM order="3">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Tore</form>
     <lemma>Tore</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="2">
       <form>Kvæven</form>
       <lemma>Kvæven</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>vitja</form>
     <lemma>vitje</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="5">
       <form>Afrika</form>
       <lemma>Afrika</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
      <LM order="7">
       <form>gonger</form>
       <lemma>gong</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="6">
         <form>fleire</form>
         <lemma>mange</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>komp</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>vore</form>
     <lemma>vere</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="6">
       <form>på</form>
       <lemma>på</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="5">
         <form>både</form>
         <lemma>både</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>&lt;ikkje-clb&gt;</LM>
          <LM>&lt;adv&gt;</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="7">
         <form>kysten</form>
         <lemma>kyst</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="8">
           <form>av</form>
           <lemma>av</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="9">
             <form>Nord-Afrika</form>
             <lemma>Nord-Afrika</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="11">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="10">
           <form>og</form>
           <lemma>og</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikkje-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
          <LM order="14">
           <form>Afrika</form>
           <lemma>Afrika</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="12">
             <form>det</form>
             <lemma>det</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>dem</LM>
              <LM>nøyt</LM>
              <LM>eint</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="13">
             <form>sørlege</form>
             <lemma>sørleg</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>eint</LM>
              <LM>bu</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
            <LM order="15">
             <form>,</form>
             <lemma>$,</lemma>
             <cpostag>&lt;komma&gt;</cpostag>
             <postag>&lt;komma&gt;</postag>
             <deprel>IK</deprel>
            </LM>
            <LM order="20">
             <form>endar</form>
             <lemma>ende</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pres</LM>
             </feats>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="16">
               <form>der</form>
               <lemma>der</lemma>
               <cpostag>sbu</cpostag>
               <postag>sbu</postag>
               <deprel>SBU</deprel>
              </LM>
              <LM order="17">
               <form>vikingane</form>
               <lemma>viking</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>fl</LM>
                <LM>bu</LM>
               </feats>
               <deprel>SUBJ</deprel>
               <childnodes>
                <LM order="18">
                 <form>i</form>
                 <lemma>i</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ATR</deprel>
                 <childnodes>
                  <LM order="19">
                   <form>boka</form>
                   <lemma>bok</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>fem</LM>
                    <LM>appell</LM>
                    <LM>eint</LM>
                    <LM>bu</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
              <LM order="21">
               <form>opp</form>
               <lemma>opp</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="22">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="25">
     <form>har</form>
     <lemma>ha</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="23">
       <form>men</form>
       <lemma>men</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="24">
       <form>eg</form>
       <lemma>eg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>1</LM>
        <LM>eint</LM>
        <LM>hum</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="27">
       <form>segla</form>
       <lemma>segle</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>perf-part</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="26">
         <form>aldri</form>
         <lemma>aldri</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="28">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="29">
           <form>Kongo-elva</form>
           <lemma>Kongo-elv</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>eint</LM>
            <LM>bu</LM>
            <LM>samset</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="30">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="4">
   <form>fortel</form>
   <lemma>fortelje</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>I</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="3">
       <form>boka</form>
       <lemma>bok</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>fem</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>du</form>
     <lemma>du</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>2</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="6">
     <form>om</form>
     <lemma>om</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="7">
       <form>vikingskip</form>
       <lemma>vikingskip</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="8">
         <form>med</form>
         <lemma>med</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="12">
           <form>mann</form>
           <lemma>mann</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>ub</LM>
            <LM>fl</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="9">
             <form>hundre</form>
             <lemma>hundre</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>kvant</LM>
              <LM>fl</LM>
             </feats>
             <deprel>DET</deprel>
             <childnodes>
              <LM order="11">
               <form>førti</form>
               <lemma>førti</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>kvant</LM>
                <LM>fl</LM>
               </feats>
               <deprel>KOORD</deprel>
               <childnodes>
                <LM order="10">
                 <form>og</form>
                 <lemma>og</lemma>
                 <cpostag>konj</cpostag>
                 <postag>konj</postag>
                 <feats>
                  <LM>&lt;ikkje-clb&gt;</LM>
                 </feats>
                 <deprel>KONJ</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>?</form>
     <lemma>$?</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;spm&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>er</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="4">
     <form>skip</form>
     <lemma>skip</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>store</form>
       <lemma>stor</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>fl</LM>
       </feats>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="2">
         <form>Så</form>
         <lemma>så</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>omtalte</form>
     <lemma>omtale</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>&lt;perf-part&gt;</LM>
      <LM>fl</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="8">
       <form>stader</form>
       <lemma>stad</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="7">
         <form>fleire</form>
         <lemma>mange</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>komp</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="6">
     <form>eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="7">
     <form>hatt</form>
     <lemma>ha</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="1">
       <form>I</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="2">
         <form>arbeidet</form>
         <lemma>arbeid</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>appell</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="3">
           <form>med</form>
           <lemma>med</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="4">
             <form>boka</form>
             <lemma>bok</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>fem</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="8">
       <form>kontakt</form>
       <lemma>kontakt</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="9">
         <form>med</form>
         <lemma>med</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="11">
           <form>Jon</form>
           <lemma>Jon</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>mask</LM>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="10">
             <form>båtbyggjaren</form>
             <lemma>båtbyggjar</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
             </feats>
             <deprel>APP</deprel>
            </LM>
            <LM order="12">
             <form>Bojer</form>
             <lemma>Bojer</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>FLAT</deprel>
            </LM>
            <LM order="13">
             <form>Godal</form>
             <lemma>Godal</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>FLAT</deprel>
            </LM>
            <LM order="14">
             <form>,</form>
             <lemma>$,</lemma>
             <cpostag>&lt;komma&gt;</cpostag>
             <postag>&lt;komma&gt;</postag>
             <deprel>IK</deprel>
            </LM>
            <LM order="16">
             <form>er</form>
             <lemma>vere</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pres</LM>
             </feats>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="15">
               <form>som</form>
               <lemma>som</lemma>
               <cpostag>sbu</cpostag>
               <postag>sbu</postag>
               <deprel>SBU</deprel>
              </LM>
              <LM order="17">
               <form>involvert</form>
               <lemma>involvere</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>&lt;perf-part&gt;</LM>
                <LM>m/f</LM>
                <LM>ub</LM>
                <LM>eint</LM>
               </feats>
               <deprel>SPRED</deprel>
               <childnodes>
                <LM order="18">
                 <form>i</form>
                 <lemma>i</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="19">
                   <form>bygginga</form>
                   <lemma>bygging</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>fem</LM>
                    <LM>appell</LM>
                    <LM>eint</LM>
                    <LM>bu</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                   <childnodes>
                    <LM order="20">
                     <form>av</form>
                     <lemma>av</lemma>
                     <cpostag>prep</cpostag>
                     <postag>prep</postag>
                     <deprel>ATR</deprel>
                     <childnodes>
                      <LM order="23">
                       <form>replikk</form>
                       <lemma>replikk</lemma>
                       <cpostag>subst</cpostag>
                       <postag>subst</postag>
                       <feats>
                        <LM>mask</LM>
                        <LM>appell</LM>
                        <LM>ub</LM>
                        <LM>eint</LM>
                       </feats>
                       <deprel>PUTFYLL</deprel>
                       <childnodes>
                        <LM order="21">
                         <form>verdas</form>
                         <lemma>verd</lemma>
                         <cpostag>subst</cpostag>
                         <postag>subst</postag>
                         <feats>
                          <LM>fem</LM>
                          <LM>appell</LM>
                          <LM>eint</LM>
                          <LM>gen</LM>
                          <LM>bu</LM>
                         </feats>
                         <deprel>DET</deprel>
                        </LM>
                        <LM order="22">
                         <form>største</form>
                         <lemma>stor</lemma>
                         <cpostag>adj</cpostag>
                         <postag>adj</postag>
                         <feats>
                          <LM>sup</LM>
                          <LM>bu</LM>
                         </feats>
                         <deprel>ATR</deprel>
                        </LM>
                        <LM order="24">
                         <form>av</form>
                         <lemma>av</lemma>
                         <cpostag>prep</cpostag>
                         <postag>prep</postag>
                         <deprel>ATR</deprel>
                         <childnodes>
                          <LM order="26">
                           <form>vikingskip</form>
                           <lemma>vikingskip</lemma>
                           <cpostag>subst</cpostag>
                           <postag>subst</postag>
                           <feats>
                            <LM>nøyt</LM>
                            <LM>appell</LM>
                            <LM>ub</LM>
                            <LM>eint</LM>
                           </feats>
                           <deprel>PUTFYLL</deprel>
                           <childnodes>
                            <LM order="25">
                             <form>eit</form>
                             <lemma>ein</lemma>
                             <cpostag>det</cpostag>
                             <postag>det</postag>
                             <feats>
                              <LM>kvant</LM>
                              <LM>nøyt</LM>
                              <LM>eint</LM>
                             </feats>
                             <deprel>DET</deprel>
                            </LM>
                           </childnodes>
                          </LM>
                         </childnodes>
                        </LM>
                       </childnodes>
                      </LM>
                     </childnodes>
                    </LM>
                    <LM order="27">
                     <form>i</form>
                     <lemma>i</lemma>
                     <cpostag>prep</cpostag>
                     <postag>prep</postag>
                     <deprel>ATR</deprel>
                     <childnodes>
                      <LM order="28">
                       <form>Haugesund</form>
                       <lemma>Haugesund</lemma>
                       <cpostag>subst</cpostag>
                       <postag>subst</postag>
                       <feats>
                        <LM>prop</LM>
                       </feats>
                       <deprel>PUTFYLL</deprel>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="29">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="4">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="5">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="6">
     <form>vore</form>
     <lemma>vere</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="2">
       <form>For</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="3">
         <form>meg</form>
         <lemma>eg</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>1</LM>
          <LM>eint</LM>
          <LM>hum</LM>
          <LM>akk</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="7">
       <form>viktig</form>
       <lemma>viktig</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>SPRED</deprel>
      </LM>
      <LM order="8">
       <form>å</form>
       <lemma>å</lemma>
       <cpostag>inf-merke</cpostag>
       <postag>inf-merke</postag>
       <deprel>PSUBJ</deprel>
       <childnodes>
        <LM order="9">
         <form>få</form>
         <lemma>få</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>inf</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="10">
           <form>til</form>
           <lemma>til</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
          </LM>
          <LM order="13">
           <form>forteljing</form>
           <lemma>forteljing</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DOBJ</deprel>
           <childnodes>
            <LM order="11">
             <form>ei</form>
             <lemma>ein</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>kvant</LM>
              <LM>fem</LM>
              <LM>eint</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="12">
             <form>spennande</form>
             <lemma>spennande</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>m/f</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="17">
     <form>har</form>
     <lemma>ha</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="15">
       <form>men</form>
       <lemma>men</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="18">
       <form>eg</form>
       <lemma>eg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>1</LM>
        <LM>eint</LM>
        <LM>hum</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="19">
       <form>freista</form>
       <lemma>freiste</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>perf-part</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="16">
         <form>samstundes</form>
         <lemma>samstundes</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="20">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="21">
           <form>gjera</form>
           <lemma>gjere</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="22">
             <form>boka</form>
             <lemma>bok</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>fem</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
             </feats>
             <deprel>DOBJ</deprel>
            </LM>
            <LM order="25">
             <form>korrekt</form>
             <lemma>korrekt</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>m/f</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>OPRED</deprel>
             <childnodes>
              <LM order="24">
               <form>historisk</form>
               <lemma>historisk</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>pos</LM>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>eint</LM>
               </feats>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="23">
                 <form>så</form>
                 <lemma>så</lemma>
                 <cpostag>adv</cpostag>
                 <postag>adv</postag>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="26">
                   <form>som</form>
                   <lemma>som</lemma>
                   <cpostag>prep</cpostag>
                   <postag>prep</postag>
                   <deprel>ADV</deprel>
                   <childnodes>
                    <LM order="27">
                     <form>mogleg</form>
                     <lemma>mogleg</lemma>
                     <cpostag>adj</cpostag>
                     <postag>adj</postag>
                     <feats>
                      <LM>pos</LM>
                      <LM>nøyt</LM>
                      <LM>ub</LM>
                      <LM>eint</LM>
                     </feats>
                     <deprel>PUTFYLL</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="28">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="29">
     <form>fortel</form>
     <lemma>fortelje</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="30">
       <form>Tore</form>
       <lemma>Tore</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="31">
         <form>Kvæven</form>
         <lemma>Kvæven</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="32">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
