<?xml version="1.0" encoding="UTF-8"?>
<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
  <head>
    <schema href="out_schema.xml" />
  </head>
  <body>
    <LM order="4">
      <form>må</form>
      <lemma>måtte</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Kvar</form>
          <lemma>kvar</lemma>
          <cpostag>det</cpostag>
          <postag>det</postag>
          <feats>
            <LM>kvant</LM>
            <LM>mask</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes order="3">
            <form>ein</form>
            <lemma>ein</lemma>
            <cpostag>det</cpostag>
            <postag>det</postag>
            <feats>
              <LM>kvant</LM>
              <LM>mask</LM>
              <LM>eint</LM>
            </feats>
            <deprel>KOORD</deprel>
            <childnodes order="2">
              <form>og</form>
              <lemma>og</lemma>
              <cpostag>konj</cpostag>
              <postag>konj</postag>
              <feats>&lt;ikkje-clb></feats>
              <deprel>KONJ</deprel>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="5">
          <form>ta</form>
          <lemma>ta</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>inf</feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="6">
              <form>dette</form>
              <lemma>dette</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>pers</LM>
                <LM>3</LM>
                <LM>nøyt</LM>
                <LM>eint</LM>
              </feats>
              <deprel>DOBJ</deprel>
            </LM>
            <LM order="7">
              <form>opp</form>
              <lemma>opp</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
            </LM>
            <LM order="8">
              <form>med</form>
              <lemma>med</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="9">
                <form>seg</form>
                <lemma>seg</lemma>
                <cpostag>pron</cpostag>
                <postag>pron</postag>
                <feats>
                  <LM>eint</LM>
                  <LM>akk</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes order="10">
                  <form>sjølv</form>
                  <lemma>sjølv</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>&lt;adj></LM>
                    <LM>forst</LM>
                  </feats>
                  <deprel>DET</deprel>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="11">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="15">
      <form>meiner</form>
      <lemma>meine</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pres</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Og</form>
          <lemma>og</lemma>
          <cpostag>konj</cpostag>
          <postag>konj</postag>
          <feats>&lt;ikkje-clb></feats>
          <deprel>KONJ</deprel>
        </LM>
        <LM order="4">
          <form>skulle</form>
          <lemma>skulle</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>
            <LM>pret</LM>
          </feats>
          <deprel>ADV</deprel>
          <childnodes>
            <LM order="2">
              <form>om</form>
              <lemma>om</lemma>
              <cpostag>sbu</cpostag>
              <postag>sbu</postag>
              <deprel>SBU</deprel>
            </LM>
            <LM order="3">
              <form>det</form>
              <lemma>det</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>pers</LM>
                <LM>3</LM>
                <LM>nøyt</LM>
                <LM>eint</LM>
              </feats>
              <deprel>FSUBJ</deprel>
            </LM>
            <LM order="5">
              <form>finnast</form>
              <lemma>finnast</lemma>
              <cpostag>verb</cpostag>
              <postag>verb</postag>
              <feats>
                <LM>inf</LM>
                <LM>&lt;st-verb></LM>
              </feats>
              <deprel>INFV</deprel>
              <childnodes order="6">
                <form>reglar</form>
                <lemma>regel</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>fl</LM>
                </feats>
                <deprel>PSUBJ</deprel>
                <childnodes order="7">
                  <form>for</form>
                  <lemma>for</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>ATR</deprel>
                  <childnodes order="12">
                    <form>er</form>
                    <lemma>vere</lemma>
                    <cpostag>verb</cpostag>
                    <postag>verb</postag>
                    <feats>
                      <LM>pres</LM>
                    </feats>
                    <deprel>PUTFYLL</deprel>
                    <childnodes>
                      <LM order="8">
                        <form>når</form>
                        <lemma>når</lemma>
                        <cpostag>sbu</cpostag>
                        <postag>sbu</postag>
                        <deprel>SBU</deprel>
                      </LM>
                      <LM order="9">
                        <form>motstand</form>
                        <lemma>motstand</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>
                          <LM>mask</LM>
                          <LM>appell</LM>
                          <LM>ub</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>SUBJ</deprel>
                        <childnodes order="10">
                          <form>mot</form>
                          <lemma>mot</lemma>
                          <cpostag>prep</cpostag>
                          <postag>prep</postag>
                          <deprel>ATR</deprel>
                          <childnodes order="11">
                            <form>staten</form>
                            <lemma>stat</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>mask</LM>
                              <LM>appell</LM>
                              <LM>eint</LM>
                              <LM>bu</LM>
                            </feats>
                            <deprel>PUTFYLL</deprel>
                          </childnodes>
                        </childnodes>
                      </LM>
                      <LM order="13">
                        <form>legitimt</form>
                        <lemma>legitim</lemma>
                        <cpostag>adj</cpostag>
                        <postag>adj</postag>
                        <feats>
                          <LM>pos</LM>
                          <LM>nøyt</LM>
                          <LM>ub</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>SPRED</deprel>
                      </LM>
                    </childnodes>
                  </childnodes>
                </childnodes>
              </childnodes>
            </LM>
            <LM order="14">
              <form>,</form>
              <lemma>$,</lemma>
              <cpostag>&lt;komma&gt;</cpostag>
              <postag>&lt;komma&gt;</postag>
              <deprel>IK</deprel>
            </LM>
          </childnodes>
        </LM>
        <LM order="16">
          <form>han</form>
          <lemma>han</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>mask</LM>
            <LM>eint</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="21">
          <form>vil</form>
          <lemma>vilje</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>
            <LM>pres</LM>
          </feats>
          <deprel>DOBJ</deprel>
          <childnodes>
            <LM order="17">
              <form>at</form>
              <lemma>at</lemma>
              <cpostag>sbu</cpostag>
              <postag>sbu</postag>
              <deprel>SBU</deprel>
            </LM>
            <LM order="19">
              <form>reglane</form>
              <lemma>regel</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>fl</LM>
                <LM>bu</LM>
              </feats>
              <deprel>SUBJ</deprel>
              <childnodes order="18">
                <form>desse</form>
                <lemma>desse</lemma>
                <cpostag>det</cpostag>
                <postag>det</postag>
                <feats>
                  <LM>dem</LM>
                  <LM>fl</LM>
                </feats>
                <deprel>DET</deprel>
              </childnodes>
            </LM>
            <LM order="22">
              <form>vera</form>
              <lemma>vere</lemma>
              <cpostag>verb</cpostag>
              <postag>verb</postag>
              <feats>
                <LM>inf</LM>
              </feats>
              <deprel>INFV</deprel>
              <childnodes>
                <LM order="20">
                  <form>berre</form>
                  <lemma>berre</lemma>
                  <cpostag>adv</cpostag>
                  <postag>adv</postag>
                  <deprel>ADV</deprel>
                </LM>
                <LM order="24">
                  <form>tome</form>
                  <lemma>tom</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>pos</LM>
                    <LM>fl</LM>
                  </feats>
                  <deprel>SPRED</deprel>
                  <childnodes>
                    <LM order="23">
                      <form>nokså</form>
                      <lemma>nokså</lemma>
                      <cpostag>adv</cpostag>
                      <postag>adv</postag>
                      <deprel>ADV</deprel>
                    </LM>
                    <LM order="26">
                      <form>innhaldslause</form>
                      <lemma>innhaldslaus</lemma>
                      <cpostag>adj</cpostag>
                      <postag>adj</postag>
                      <feats>
                        <LM>pos</LM>
                        <LM>fl</LM>
                      </feats>
                      <deprel>KOORD</deprel>
                      <childnodes order="25">
                        <form>og</form>
                        <lemma>og</lemma>
                        <cpostag>konj</cpostag>
                        <postag>konj</postag>
                        <feats>&lt;ikkje-clb></feats>
                        <deprel>KONJ</deprel>
                      </childnodes>
                    </LM>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="27">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="8">
      <form>kan</form>
      <lemma>kunne</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="10">
          <form>teori</form>
          <lemma>teori</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes order="9">
            <form>ingen</form>
            <lemma>ingen</lemma>
            <cpostag>det</cpostag>
            <postag>det</postag>
            <feats>
              <LM>kvant</LM>
              <LM>mask</LM>
              <LM>eint</LM>
            </feats>
            <deprel>DET</deprel>
          </childnodes>
        </LM>
        <LM order="11">
          <form>løysa</form>
          <lemma>løyse</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>inf</feats>
          <deprel>INFV</deprel>
          <childnodes order="2">
            <form>konflikten</form>
            <lemma>konflikt</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
            </feats>
            <deprel>DOBJ</deprel>
            <childnodes>
              <LM order="1">
                <form>Denne</form>
                <lemma>denne</lemma>
                <cpostag>det</cpostag>
                <postag>det</postag>
                <feats>
                  <LM>dem</LM>
                  <LM>mask</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>DET</deprel>
              </LM>
              <LM order="3">
                <form>mellom</form>
                <lemma>mellom</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ATR</deprel>
                <childnodes order="4">
                  <form>samvit</form>
                  <lemma>samvit</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>nøyt</LM>
                    <LM>appell</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>PUTFYLL</deprel>
                  <childnodes order="7">
                    <form>orden</form>
                    <lemma>orden</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>mask</LM>
                      <LM>appell</LM>
                      <LM>ub</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>KOORD</deprel>
                    <childnodes>
                      <LM order="5">
                        <form>og</form>
                        <lemma>og</lemma>
                        <cpostag>konj</cpostag>
                        <postag>konj</postag>
                        <feats>&lt;ikkje-clb></feats>
                        <deprel>KONJ</deprel>
                      </LM>
                      <LM order="6">
                        <form>sosial</form>
                        <lemma>sosial</lemma>
                        <cpostag>adj</cpostag>
                        <postag>adj</postag>
                        <feats>
                          <LM>pos</LM>
                          <LM>m/f</LM>
                          <LM>ub</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>ATR</deprel>
                      </LM>
                    </childnodes>
                  </childnodes>
                </childnodes>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="12">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>undrast</form>
      <lemma>undrast</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
        <LM>&lt;st-verb></LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Eg</form>
          <lemma>eg</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>1</LM>
            <LM>eint</LM>
            <LM>hum</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="8">
          <form>kunne</form>
          <lemma>kunne</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>
            <LM>pret</LM>
          </feats>
          <deprel>DOBJ</deprel>
          <childnodes>
            <LM order="3">
              <form>om</form>
              <lemma>om</lemma>
              <cpostag>sbu</cpostag>
              <postag>sbu</postag>
              <deprel>SBU</deprel>
            </LM>
            <LM order="7">
              <form>overgangsrådet</form>
              <lemma>overgangsråd</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>nøyt</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
                <LM>samset</LM>
              </feats>
              <deprel>SUBJ</deprel>
              <childnodes>
                <LM order="5">
                  <form>det</form>
                  <lemma>det</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>dem</LM>
                    <LM>nøyt</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>DET</deprel>
                </LM>
                <LM order="6">
                  <form>libyske</form>
                  <lemma>libysk</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>pos</LM>
                    <LM>eint</LM>
                    <LM>bu</LM>
                  </feats>
                  <deprel>ATR</deprel>
                </LM>
              </childnodes>
            </LM>
            <LM order="9">
              <form>hatt</form>
              <lemma>ha</lemma>
              <cpostag>verb</cpostag>
              <postag>verb</postag>
              <feats>
                <LM>perf-part</LM>
              </feats>
              <deprel>INFV</deprel>
              <childnodes>
                <LM order="4">
                  <form>ikkje</form>
                  <lemma>ikkje</lemma>
                  <cpostag>adv</cpostag>
                  <postag>adv</postag>
                  <deprel>ADV</deprel>
                </LM>
                <LM order="10">
                  <form>nytte</form>
                  <lemma>nytte</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>fem</LM>
                    <LM>appell</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>DOBJ</deprel>
                  <childnodes order="11">
                    <form>av</form>
                    <lemma>av</lemma>
                    <cpostag>prep</cpostag>
                    <postag>prep</postag>
                    <deprel>ATR</deprel>
                    <childnodes order="12">
                      <form>å</form>
                      <lemma>å</lemma>
                      <cpostag>inf-merke</cpostag>
                      <postag>inf-merke</postag>
                      <deprel>PUTFYLL</deprel>
                      <childnodes order="13">
                        <form>lesa</form>
                        <lemma>lese</lemma>
                        <cpostag>verb</cpostag>
                        <postag>verb</postag>
                        <feats>inf</feats>
                        <deprel>INFV</deprel>
                        <childnodes order="17">
                          <form>analysar</form>
                          <lemma>analyse</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>mask</LM>
                            <LM>appell</LM>
                            <LM>ub</LM>
                            <LM>fl</LM>
                          </feats>
                          <deprel>DOBJ</deprel>
                          <childnodes>
                            <LM order="14">
                              <form>Neumanns</form>
                              <lemma>Neumann</lemma>
                              <cpostag>subst</cpostag>
                              <postag>subst</postag>
                              <feats>
                                <LM>prop</LM>
                                <LM>gen</LM>
                              </feats>
                              <deprel>DET</deprel>
                            </LM>
                            <LM order="15">
                              <form>kloke</form>
                              <lemma>klok</lemma>
                              <cpostag>adj</cpostag>
                              <postag>adj</postag>
                              <feats>
                                <LM>pos</LM>
                                <LM>fl</LM>
                              </feats>
                              <deprel>ATR</deprel>
                            </LM>
                            <LM order="16">
                              <form>historiske</form>
                              <lemma>historisk</lemma>
                              <cpostag>adj</cpostag>
                              <postag>adj</postag>
                              <feats>
                                <LM>pos</LM>
                                <LM>fl</LM>
                              </feats>
                              <deprel>ATR</deprel>
                            </LM>
                            <LM order="18">
                              <form>omkring</form>
                              <lemma>omkring</lemma>
                              <cpostag>prep</cpostag>
                              <postag>prep</postag>
                              <deprel>ATR</deprel>
                              <childnodes order="21">
                                <form>problemet</form>
                                <lemma>problem</lemma>
                                <cpostag>subst</cpostag>
                                <postag>subst</postag>
                                <feats>
                                  <LM>nøyt</LM>
                                  <LM>appell</LM>
                                  <LM>eint</LM>
                                  <LM>bu</LM>
                                </feats>
                                <deprel>PUTFYLL</deprel>
                                <childnodes>
                                  <LM order="19">
                                    <form>dette</form>
                                    <lemma>dette</lemma>
                                    <cpostag>det</cpostag>
                                    <postag>det</postag>
                                    <feats>
                                      <LM>dem</LM>
                                      <LM>nøyt</LM>
                                      <LM>eint</LM>
                                    </feats>
                                    <deprel>DET</deprel>
                                  </LM>
                                  <LM order="20">
                                    <form>livsviktige</form>
                                    <lemma>livsviktig</lemma>
                                    <cpostag>adj</cpostag>
                                    <postag>adj</postag>
                                    <feats>
                                      <LM>pos</LM>
                                      <LM>eint</LM>
                                      <LM>bu</LM>
                                    </feats>
                                    <deprel>ATR</deprel>
                                  </LM>
                                </childnodes>
                              </childnodes>
                            </LM>
                          </childnodes>
                        </childnodes>
                      </childnodes>
                    </childnodes>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="22">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="1">
      <form>No</form>
      <lemma>no</lemma>
      <cpostag>adv</cpostag>
      <postag>adv</postag>
      <deprel>FRAG</deprel>
      <childnodes>
        <LM order="4">
          <form>skal</form>
          <lemma>skulle</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>
            <LM>pres</LM>
          </feats>
          <deprel>ADV</deprel>
          <childnodes>
            <LM order="2">
              <form>som</form>
              <lemma>som</lemma>
              <cpostag>sbu</cpostag>
              <postag>sbu</postag>
              <deprel>SBU</deprel>
            </LM>
            <LM order="3">
              <form>dei</form>
              <lemma>dei</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>pers</LM>
                <LM>3</LM>
                <LM>fl</LM>
                <LM>hum</LM>
                <LM>nom</LM>
              </feats>
              <deprel>SUBJ</deprel>
            </LM>
            <LM order="5">
              <form>finna</form>
              <lemma>finne</lemma>
              <cpostag>verb</cpostag>
              <postag>verb</postag>
              <feats>inf</feats>
              <deprel>INFV</deprel>
              <childnodes>
                <LM order="6">
                  <form>ut</form>
                  <lemma>ut</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>ADV</deprel>
                </LM>
                <LM order="9">
                  <form>hende</form>
                  <lemma>hende</lemma>
                  <cpostag>verb</cpostag>
                  <postag>verb</postag>
                  <feats>pret</feats>
                  <deprel>DOBJ</deprel>
                  <childnodes>
                    <LM order="7">
                      <form>kva</form>
                      <lemma>kva</lemma>
                      <cpostag>pron</cpostag>
                      <postag>pron</postag>
                      <feats>
                        <LM>ikke-hum</LM>
                        <LM>sp</LM>
                      </feats>
                      <deprel>SUBJ</deprel>
                    </LM>
                    <LM order="8">
                      <form>som</form>
                      <lemma>som</lemma>
                      <cpostag>sbu</cpostag>
                      <postag>sbu</postag>
                      <deprel>SBU</deprel>
                    </LM>
                    <LM order="10">
                      <form>med</form>
                      <lemma>med</lemma>
                      <cpostag>prep</cpostag>
                      <postag>prep</postag>
                      <deprel>ADV</deprel>
                      <childnodes order="11">
                        <form>Muammar</form>
                        <lemma>Muammar</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>prop</feats>
                        <deprel>PUTFYLL</deprel>
                        <childnodes>
                          <LM order="12">
                            <form>Gaddafi</form>
                            <lemma>Gaddafi</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>prop</feats>
                            <deprel>FLAT</deprel>
                          </LM>
                          <LM order="13">
                            <form>,</form>
                            <lemma>$,</lemma>
                            <cpostag>&lt;komma&gt;</cpostag>
                            <postag>&lt;komma&gt;</postag>
                            <deprel>IK</deprel>
                          </LM>
                          <LM order="14">
                            <form>despoten</form>
                            <lemma>despot</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>mask</LM>
                              <LM>appell</LM>
                              <LM>eint</LM>
                              <LM>bu</LM>
                            </feats>
                            <deprel>APP</deprel>
                            <childnodes order="15">
                              <form>over</form>
                              <lemma>over</lemma>
                              <cpostag>prep</cpostag>
                              <postag>prep</postag>
                              <deprel>ATR</deprel>
                              <childnodes order="17">
                                <form>despotar</form>
                                <lemma>despot</lemma>
                                <cpostag>subst</cpostag>
                                <postag>subst</postag>
                                <feats>
                                  <LM>mask</LM>
                                  <LM>appell</LM>
                                  <LM>ub</LM>
                                  <LM>fl</LM>
                                </feats>
                                <deprel>PUTFYLL</deprel>
                                <childnodes>
                                  <LM order="16">
                                    <form>alle</form>
                                    <lemma>all</lemma>
                                    <cpostag>det</cpostag>
                                    <postag>det</postag>
                                    <feats>
                                      <LM>kvant</LM>
                                      <LM>fl</LM>
                                    </feats>
                                    <deprel>DET</deprel>
                                  </LM>
                                  <LM order="18">
                                    <form>i</form>
                                    <lemma>i</lemma>
                                    <cpostag>prep</cpostag>
                                    <postag>prep</postag>
                                    <deprel>ATR</deprel>
                                    <childnodes order="20">
                                      <form>tid</form>
                                      <lemma>tid</lemma>
                                      <cpostag>subst</cpostag>
                                      <postag>subst</postag>
                                      <feats>
                                        <LM>fem</LM>
                                        <LM>appell</LM>
                                        <LM>ub</LM>
                                        <LM>eint</LM>
                                      </feats>
                                      <deprel>PUTFYLL</deprel>
                                      <childnodes order="19">
                                        <form>nyare</form>
                                        <lemma>ny</lemma>
                                        <cpostag>adj</cpostag>
                                        <postag>adj</postag>
                                        <feats>komp</feats>
                                        <deprel>ATR</deprel>
                                      </childnodes>
                                    </childnodes>
                                  </LM>
                                </childnodes>
                              </childnodes>
                            </childnodes>
                          </LM>
                        </childnodes>
                      </childnodes>
                    </LM>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="21">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>vil</form>
      <lemma>vilje</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="4">
          <form>fleste</form>
          <lemma>mange</lemma>
          <cpostag>adj</cpostag>
          <postag>adj</postag>
          <feats>
            <LM>sup</LM>
            <LM>bu</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes>
            <LM order="3">
              <form>dei</form>
              <lemma>dei</lemma>
              <cpostag>det</cpostag>
              <postag>det</postag>
              <feats>
                <LM>dem</LM>
                <LM>fl</LM>
              </feats>
              <deprel>DET</deprel>
            </LM>
            <LM order="5">
              <form>i</form>
              <lemma>i</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="6">
                <form>dag</form>
                <lemma>dag</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="7">
          <form>ta</form>
          <lemma>ta</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>inf</feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="1">
              <form>Uansett</form>
              <lemma>uansett</lemma>
              <cpostag>adv</cpostag>
              <postag>adv</postag>
              <deprel>ADV</deprel>
            </LM>
            <LM order="9">
              <form>avstand</form>
              <lemma>avstand</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>ub</LM>
                <LM>eint</LM>
              </feats>
              <deprel>DOBJ</deprel>
              <childnodes>
                <LM order="8">
                  <form>klårt</form>
                  <lemma>klår</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>pos</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>ATR</deprel>
                </LM>
                <LM order="10">
                  <form>frå</form>
                  <lemma>frå</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>ATR</deprel>
                  <childnodes order="11">
                    <form>måten</form>
                    <lemma>måte</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>mask</LM>
                      <LM>appell</LM>
                      <LM>eint</LM>
                      <LM>bu</LM>
                    </feats>
                    <deprel>PUTFYLL</deprel>
                    <childnodes order="13">
                      <form>kom</form>
                      <lemma>kome</lemma>
                      <cpostag>verb</cpostag>
                      <postag>verb</postag>
                      <feats>pret</feats>
                      <deprel>ATR</deprel>
                      <childnodes>
                        <LM order="12">
                          <form>han</form>
                          <lemma>han</lemma>
                          <cpostag>pron</cpostag>
                          <postag>pron</postag>
                          <feats>
                            <LM>pers</LM>
                            <LM>3</LM>
                            <LM>mask</LM>
                            <LM>eint</LM>
                            <LM>nom</LM>
                          </feats>
                          <deprel>SUBJ</deprel>
                        </LM>
                        <LM order="14">
                          <form>til</form>
                          <lemma>til</lemma>
                          <cpostag>prep</cpostag>
                          <postag>prep</postag>
                                                    <deprel>ADV</deprel>
                          <childnodes order="15">
                            <form>endes</form>
                            <lemma>ende</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>mask</LM>
                              <LM>appell</LM>
                              <LM>ub</LM>
                              <LM>eint</LM>
                              <LM>gen</LM>
                            </feats>
                            <deprel>PUTFYLL</deprel>
                          </childnodes>
                        </LM>
                        <LM order="16">
                          <form>på</form>
                          <lemma>på</lemma>
                          <cpostag>prep</cpostag>
                          <postag>prep</postag>
                          <deprel>ADV</deprel>
                        </LM>
                      </childnodes>
                    </childnodes>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="17">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>var</form>
      <lemma>vere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pret</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Den</form>
          <lemma>den</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>mask</LM>
            <LM>fem</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>uverdig</form>
          <lemma>uverdig</lemma>
          <cpostag>adj</cpostag>
          <postag>adj</postag>
          <feats>
            <LM>pos</LM>
            <LM>m/f</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SPRED</deprel>
          <childnodes order="7">
            <form>start</form>
            <lemma>start</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
            </feats>
            <deprel>KOORD</deprel>
            <childnodes>
              <LM order="4">
                <form>og</form>
                <lemma>og</lemma>
                <cpostag>konj</cpostag>
                <postag>konj</postag>
                <feats>&lt;ikkje-clb></feats>
                <deprel>KONJ</deprel>
              </LM>
              <LM order="5">
                <form>ein</form>
                <lemma>ein</lemma>
                <cpostag>det</cpostag>
                <postag>det</postag>
                <feats>
                  <LM>kvant</LM>
                  <LM>mask</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>DET</deprel>
              </LM>
              <LM order="6">
                <form>dårleg</form>
                <lemma>dårleg</lemma>
                <cpostag>adj</cpostag>
                <postag>adj</postag>
                <feats>
                  <LM>pos</LM>
                  <LM>m/f</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>ATR</deprel>
              </LM>
              <LM order="8">
                <form>for</form>
                <lemma>for</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ATR</deprel>
                <childnodes order="11">
                  <form>Libya</form>
                  <lemma>Libya</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>prop</feats>
                  <deprel>PUTFYLL</deprel>
                  <childnodes>
                    <LM order="9">
                      <form>eit</form>
                      <lemma>ein</lemma>
                      <cpostag>det</cpostag>
                      <postag>det</postag>
                      <feats>
                        <LM>kvant</LM>
                        <LM>nøyt</LM>
                        <LM>eint</LM>
                      </feats>
                      <deprel>DET</deprel>
                    </LM>
                    <LM order="10">
                      <form>demokratisk</form>
                      <lemma>demokratisk</lemma>
                      <cpostag>adj</cpostag>
                      <postag>adj</postag>
                      <feats>
                        <LM>pos</LM>
                        <LM>nøyt</LM>
                        <LM>ub</LM>
                        <LM>eint</LM>
                      </feats>
                      <deprel>ATR</deprel>
                    </LM>
                  </childnodes>
                </childnodes>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="12">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="3">
      <form>er</form>
      <lemma>vere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Bernt</form>
          <lemma>Bernt</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>prop</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes order="2">
            <form>Hagtvet</form>
            <lemma>Hagtvet</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>prop</feats>
            <deprel>FLAT</deprel>
          </childnodes>
        </LM>
        <LM order="4">
          <form>professor</form>
          <lemma>professor</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SPRED</deprel>
          <childnodes>
            <LM order="5">
              <form>i</form>
              <lemma>i</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="6">
                <form>statsvitskap</form>
                <lemma>statsvitskap</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
              </childnodes>
            </LM>
            <LM order="7">
              <form>ved</form>
              <lemma>ved</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="8">
                <form>Universitetet</form>
                <lemma>Universitetet</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>prop</feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="9">
                    <form>i</form>
                    <lemma>i</lemma>
                    <cpostag>prep</cpostag>
                    <postag>prep</postag>
                    <deprel>FLAT</deprel>
                  </LM>
                  <LM order="10">
                    <form>Oslo</form>
                    <lemma>Oslo</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>prop</feats>
                    <deprel>FLAT</deprel>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
            <LM order="13">
              <form>skribent</form>
              <lemma>skribent</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>ub</LM>
                <LM>eint</LM>
              </feats>
              <deprel>KOORD</deprel>
              <childnodes>
                <LM order="11">
                  <form>og</form>
                  <lemma>og</lemma>
                  <cpostag>konj</cpostag>
                  <postag>konj</postag>
                  <feats>&lt;ikkje-clb></feats>
                  <deprel>KONJ</deprel>
                </LM>
                <LM order="12">
                  <form>fast</form>
                  <lemma>fast</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>pos</LM>
                    <LM>m/f</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>ATR</deprel>
                </LM>
                <LM order="14">
                  <form>for</form>
                  <lemma>for</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>ATR</deprel>
                  <childnodes order="15">
                    <form>Dag</form>
                    <lemma>Dag</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>mask</LM>
                      <LM>prop</LM>
                    </feats>
                    <deprel>PUTFYLL</deprel>
                    <childnodes>
                      <LM order="16">
                        <form>og</form>
                        <lemma>og</lemma>
                        <cpostag>konj</cpostag>
                        <postag>konj</postag>
                        <feats>&lt;ikkje-clb></feats>
                        <deprel>FLAT</deprel>
                      </LM>
                      <LM order="17">
                        <form>Tid</form>
                        <lemma>Tid</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>prop</feats>
                        <deprel>FLAT</deprel>
                      </LM>
                    </childnodes>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="18">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
  </body>
</conll>
