<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="2">
   <form>vert</form>
   <lemma>verte</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Difor</form>
     <lemma>difor</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="3">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="5">
     <form>merksemd</form>
     <lemma>merksemd</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>fem</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>PSUBJ</deprel>
     <childnodes>
      <LM order="4">
       <form>meir</form>
       <lemma>mykje</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>komp</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
      <LM order="6">
       <form>kring</form>
       <lemma>kring</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="7">
         <form>spørsmål</form>
         <lemma>spørsmål</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="8">
           <form>om</form>
           <lemma>om</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="9">
             <form>integritet</form>
             <lemma>integritet</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
            <LM order="13">
             <form>kan</form>
             <lemma>kunne</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pres</LM>
             </feats>
             <deprel>KOORD</deprel>
             <childnodes>
              <LM order="10">
               <form>og</form>
               <lemma>og</lemma>
               <cpostag>konj</cpostag>
               <postag>konj</postag>
               <feats>
                <LM>&lt;ikkje-clb&gt;</LM>
               </feats>
               <deprel>KONJ</deprel>
              </LM>
              <LM order="11">
               <form>om</form>
               <lemma>om</lemma>
               <cpostag>sbu</cpostag>
               <postag>sbu</postag>
               <deprel>SBU</deprel>
              </LM>
              <LM order="12">
               <form>ein</form>
               <lemma>ein</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>pers</LM>
                <LM>eint</LM>
                <LM>hum</LM>
               </feats>
               <deprel>SUBJ</deprel>
              </LM>
              <LM order="14">
               <form>ta</form>
               <lemma>ta</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>inf</LM>
               </feats>
               <deprel>INFV</deprel>
               <childnodes>
                <LM order="16">
                 <form>politikar</form>
                 <lemma>politikar</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                 </feats>
                 <deprel>DOBJ</deprel>
                 <childnodes>
                  <LM order="15">
                   <form>ein</form>
                   <lemma>ein</lemma>
                   <cpostag>det</cpostag>
                   <postag>det</postag>
                   <feats>
                    <LM>kvant</LM>
                    <LM>mask</LM>
                    <LM>eint</LM>
                   </feats>
                   <deprel>DET</deprel>
                  </LM>
                 </childnodes>
                </LM>
                <LM order="17">
                 <form>for</form>
                 <lemma>for</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="18">
                   <form>å</form>
                   <lemma>å</lemma>
                   <cpostag>inf-merke</cpostag>
                   <postag>inf-merke</postag>
                   <deprel>PUTFYLL</deprel>
                   <childnodes>
                    <LM order="19">
                     <form>tala</form>
                     <lemma>tale</lemma>
                     <cpostag>verb</cpostag>
                     <postag>verb</postag>
                     <feats>
                      <LM>inf</LM>
                     </feats>
                     <deprel>INFV</deprel>
                     <childnodes>
                      <LM order="20">
                       <form>usant</form>
                       <lemma>usann</lemma>
                       <cpostag>adj</cpostag>
                       <postag>adj</postag>
                       <feats>
                        <LM>pos</LM>
                        <LM>nøyt</LM>
                        <LM>ub</LM>
                        <LM>eint</LM>
                       </feats>
                       <deprel>ADV</deprel>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
                <LM order="21">
                 <form>-</form>
                 <lemma>$-</lemma>
                 <cpostag>&lt;strek&gt;</cpostag>
                 <postag>&lt;strek&gt;</postag>
                 <deprel>IK</deprel>
                </LM>
                <LM order="26">
                 <form>måtte</form>
                 <lemma>måtte</lemma>
                 <cpostag>verb</cpostag>
                 <postag>verb</postag>
                 <feats>
                  <LM>pret</LM>
                 </feats>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="25">
                   <form>saka</form>
                   <lemma>sak</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>fem</LM>
                    <LM>appell</LM>
                    <LM>eint</LM>
                    <LM>bu</LM>
                   </feats>
                   <deprel>SUBJ</deprel>
                  </LM>
                  <LM order="27">
                   <form>vera</form>
                   <lemma>vere</lemma>
                   <cpostag>verb</cpostag>
                   <postag>verb</postag>
                   <feats>
                    <LM>inf</LM>
                   </feats>
                   <deprel>INFV</deprel>
                   <childnodes>
                    <LM order="24">
                     <form>bagatellmessig</form>
                     <lemma>bagatellmessig</lemma>
                     <cpostag>adj</cpostag>
                     <postag>adj</postag>
                     <feats>
                      <LM>pos</LM>
                      <LM>m/f</LM>
                      <LM>ub</LM>
                      <LM>eint</LM>
                     </feats>
                     <deprel>SPRED</deprel>
                     <childnodes>
                      <LM order="23">
                       <form>kor</form>
                       <lemma>kor</lemma>
                       <cpostag>adv</cpostag>
                       <postag>adv</postag>
                       <deprel>ADV</deprel>
                       <childnodes>
                        <LM order="22">
                         <form>same</form>
                         <lemma>same</lemma>
                         <cpostag>det</cpostag>
                         <postag>det</postag>
                         <feats>
                          <LM>dem</LM>
                          <LM>&lt;adj&gt;</LM>
                          <LM>bu</LM>
                         </feats>
                         <deprel>ADV</deprel>
                        </LM>
                       </childnodes>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="28">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>må</form>
   <lemma>måtte</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="3">
     <form>politikarane</form>
     <lemma>politikar</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>fl</LM>
      <LM>bu</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>ta</form>
     <lemma>ta</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="5">
       <form>høgd</form>
       <lemma>høgd</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>fem</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
      <LM order="6">
       <form>for</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="1">
         <form>Det</form>
         <lemma>det</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>3</LM>
          <LM>nøyt</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
