<?xml version="1.0" encoding="UTF-8"?>
<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
  <head>
    <schema href="out_schema.xml" />
  </head>
  <body>
    <LM order="3">
      <form>hadde</form>
      <lemma>ha</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pret</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>«</form>
          <lemma>$"</lemma>
          <cpostag>&lt;anf></cpostag>
          <postag>&lt;anf></postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="2">
          <form>Eg</form>
          <lemma>eg</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>1</LM>
            <LM>eint</LM>
            <LM>hum</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="5">
          <form>søkt</form>
          <lemma>søkje</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>perf-part</feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="4">
              <form>alltid</form>
              <lemma>alltid</lemma>
              <cpostag>adv</cpostag>
              <postag>adv</postag>
              <deprel>ADV</deprel>
            </LM>
            <LM order="6">
              <form>mot</form>
              <lemma>mot</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="8">
                <form>lyssky</form>
                <lemma>lyssky</lemma>
                <cpostag>adj</cpostag>
                <postag>adj</postag>
                <feats>
                  <LM>pos</LM>
                  <LM>eint</LM>
                  <LM>bu</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="7">
                    <form>det</form>
                    <lemma>det</lemma>
                    <cpostag>det</cpostag>
                    <postag>det</postag>
                    <feats>
                      <LM>dem</LM>
                      <LM>nøyt</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>DET</deprel>
                  </LM>
                  <LM order="9">
                    <form>,</form>
                    <lemma>$,</lemma>
                    <cpostag>&lt;komma&gt;</cpostag>
                    <postag>&lt;komma&gt;</postag>
                    <deprel>IK</deprel>
                  </LM>
                  <LM order="10">
                    <form>det</form>
                    <lemma>det</lemma>
                    <cpostag>pron</cpostag>
                    <postag>pron</postag>
                    <feats>
                      <LM>pers</LM>
                      <LM>3</LM>
                      <LM>nøyt</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>APP</deprel>
                    <childnodes order="13">
                      <form>kunne</form>
                      <lemma>kunne</lemma>
                      <cpostag>verb</cpostag>
                      <postag>verb</postag>
                      <feats>
                        <LM>pret</LM>
                      </feats>
                      <deprel>ATR</deprel>
                      <childnodes>
                        <LM order="11">
                          <form>som</form>
                          <lemma>som</lemma>
                          <cpostag>sbu</cpostag>
                          <postag>sbu</postag>
                          <deprel>SBU</deprel>
                        </LM>
                        <LM order="14">
                          <form>delast</form>
                          <lemma>dele</lemma>
                          <cpostag>verb</cpostag>
                          <postag>verb</postag>
                          <feats>
                            <LM>inf</LM>
                            <LM>st-form</LM>
                          </feats>
                          <deprel>INFV</deprel>
                          <childnodes>
                            <LM order="12">
                              <form>bare</form>
                              <lemma>bare</lemma>
                              <cpostag>adv</cpostag>
                              <postag>adv</postag>
                              <deprel>ADV</deprel>
                            </LM>
                            <LM order="15">
                              <form>mellom</form>
                              <lemma>mellom</lemma>
                              <cpostag>prep</cpostag>
                              <postag>prep</postag>
                              <deprel>ADV</deprel>
                              <childnodes order="16">
                                <form>to</form>
                                <lemma>to</lemma>
                                <cpostag>det</cpostag>
                                <postag>det</postag>
                                <feats>
                                  <LM>kvant</LM>
                                  <LM>fl</LM>
                                </feats>
                                <deprel>PUTFYLL</deprel>
                              </childnodes>
                            </LM>
                          </childnodes>
                        </LM>
                      </childnodes>
                    </childnodes>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="17">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="3">
      <form>hadde</form>
      <lemma>ha</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pret</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="2">
          <form>intimitet</form>
          <lemma>intimitet</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes order="1">
            <form>Ekte</form>
            <lemma>ekte</lemma>
            <cpostag>adj</cpostag>
            <postag>adj</postag>
            <feats>
              <LM>pos</LM>
              <LM>m/f</LM>
              <LM>ub</LM>
              <LM>eint</LM>
            </feats>
            <deprel>ATR</deprel>
          </childnodes>
        </LM>
        <LM order="5">
          <form>oppstått</form>
          <lemma>oppstå</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>perf-part</feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="4">
              <form>bare</form>
              <lemma>bare</lemma>
              <cpostag>adv</cpostag>
              <postag>adv</postag>
              <deprel>ADV</deprel>
            </LM>
            <LM order="6">
              <form>i</form>
              <lemma>i</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="8">
                <form>rom</form>
                <lemma>rom</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>nøyt</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>fl</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes order="7">
                  <form>løynde</form>
                  <lemma>løynd</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>pos</LM>
                    <LM>fl</LM>
                  </feats>
                  <deprel>ATR</deprel>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="9">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="10">
      <form>hadde</form>
      <lemma>ha</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pret</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="11">
          <form>det</form>
          <lemma>det</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes order="13">
            <form>var</form>
            <lemma>vere</lemma>
            <cpostag>verb</cpostag>
            <postag>verb</postag>
            <feats>
              <LM>pret</LM>
            </feats>
            <deprel>ATR</deprel>
            <childnodes>
              <LM order="12">
                <form>som</form>
                <lemma>som</lemma>
                <cpostag>sbu</cpostag>
                <postag>sbu</postag>
                <deprel>SBU</deprel>
              </LM>
              <LM order="14">
                <form>stort</form>
                <lemma>stor</lemma>
                <cpostag>adj</cpostag>
                <postag>adj</postag>
                <feats>
                  <LM>pos</LM>
                  <LM>nøyt</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>SPRED</deprel>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="15">
          <form>blitt</form>
          <lemma>bli</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>
            <LM>perf-part</LM>
          </feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="3">
              <form>fekk</form>
              <lemma>få</lemma>
              <cpostag>verb</cpostag>
              <postag>verb</postag>
              <feats>
                <LM>pret</LM>
              </feats>
              <deprel>ADV</deprel>
              <childnodes>
                <LM order="1">
                  <form>Straks</form>
                  <lemma>straks</lemma>
                  <cpostag>sbu</cpostag>
                  <postag>sbu</postag>
                  <deprel>SBU</deprel>
                </LM>
                <LM order="2">
                  <form>andre</form>
                  <lemma>annan</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>dem</LM>
                    <LM>&lt;adj></LM>
                    <LM>fl</LM>
                  </feats>
                  <deprel>SUBJ</deprel>
                </LM>
                <LM order="4">
                  <form>sjå</form>
                  <lemma>sjå</lemma>
                  <cpostag>verb</cpostag>
                  <postag>verb</postag>
                  <feats>inf</feats>
                  <deprel>INFV</deprel>
                  <childnodes>
                    <LM order="5">
                      <form>,</form>
                      <lemma>$,</lemma>
                      <cpostag>&lt;komma&gt;</cpostag>
                      <postag>&lt;komma&gt;</postag>
                      <deprel>IK</deprel>
                    </LM>
                    <LM order="6">
                      <form>observere</form>
                      <lemma>observere</lemma>
                      <cpostag>verb</cpostag>
                      <postag>verb</postag>
                      <feats>inf</feats>
                      <deprel>KOORD</deprel>
                    </LM>
                    <LM order="8">
                      <form>tolke</form>
                      <lemma>tolke</lemma>
                      <cpostag>verb</cpostag>
                      <postag>verb</postag>
                      <feats>inf</feats>
                      <deprel>KOORD</deprel>
                      <childnodes order="7">
                        <form>og</form>
                        <lemma>og</lemma>
                        <cpostag>konj</cpostag>
                        <postag>konj</postag>
                        <feats>&lt;ikkje-clb></feats>
                        <deprel>KONJ</deprel>
                      </childnodes>
                    </LM>
                  </childnodes>
                </LM>
                <LM order="9">
                  <form>,</form>
                  <lemma>$,</lemma>
                  <cpostag>&lt;komma&gt;</cpostag>
                  <postag>&lt;komma&gt;</postag>
                  <deprel>IK</deprel>
                </LM>
              </childnodes>
            </LM>
            <LM order="16">
              <form>lite</form>
              <lemma>liten</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>pos</LM>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>eint</LM>
              </feats>
              <deprel>SPRED</deprel>
            </LM>
          </childnodes>
        </LM>
        <LM order="17">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>hadde</form>
      <lemma>ha</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pret</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Det</form>
          <lemma>det</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>forsvunne</form>
          <lemma>forsvinne</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>perf-part</feats>
          <deprel>INFV</deprel>
          <childnodes order="5">
            <form>blitt</form>
            <lemma>bli</lemma>
            <cpostag>verb</cpostag>
            <postag>verb</postag>
            <feats>
              <LM>perf-part</LM>
            </feats>
            <deprel>KOORD</deprel>
            <childnodes>
              <LM order="4">
                <form>og</form>
                <lemma>og</lemma>
                <cpostag>konj</cpostag>
                <postag>konj</postag>
                <feats>&lt;ikkje-clb></feats>
                <deprel>KONJ</deprel>
              </LM>
              <LM order="6">
                <form>borte</form>
                <lemma>borte</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ADV</deprel>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="7">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
        <LM order="8">
          <form>»</form>
          <lemma>$"</lemma>
          <cpostag>&lt;anf></cpostag>
          <postag>&lt;anf></postag>
          <deprel>IK</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="3">
      <form>formidlar</form>
      <lemma>formidle</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pres</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="2">
          <form>Eikemo</form>
          <lemma>Eikemo</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>prop</feats>
          <deprel>SUBJ</deprel>
          <childnodes order="1">
            <form>Pageturner</form>
            <lemma>pageturner</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
              <LM>unorm</LM>
            </feats>
            <deprel>APP</deprel>
          </childnodes>
        </LM>
        <LM order="5">
          <form>lengt</form>
          <lemma>lengt</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>DOBJ</deprel>
          <childnodes>
            <LM order="4">
              <form>syrgjeleg</form>
              <lemma>syrgjeleg</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>pos</LM>
                <LM>m/f</LM>
                <LM>ub</LM>
                <LM>eint</LM>
              </feats>
              <deprel>ATR</deprel>
            </LM>
            <LM order="8">
              <form>grenseløyse</form>
              <lemma>grenseløyse</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>fem</LM>
                <LM>appell</LM>
                <LM>ub</LM>
                <LM>eint</LM>
              </feats>
              <deprel>KOORD</deprel>
              <childnodes>
                <LM order="6">
                  <form>og</form>
                  <lemma>og</lemma>
                  <cpostag>konj</cpostag>
                  <postag>konj</postag>
                  <feats>&lt;ikkje-clb></feats>
                  <deprel>KONJ</deprel>
                </LM>
                <LM order="7">
                  <form>menneskeleg</form>
                  <lemma>menneskeleg</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>pos</LM>
                    <LM>m/f</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>ATR</deprel>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="9">
          <form>i</form>
          <lemma>i</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
          <childnodes order="13">
            <form>dialogar</form>
            <lemma>dialog</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>fl</LM>
            </feats>
            <deprel>PUTFYLL</deprel>
            <childnodes order="10">
              <form>tette</form>
              <lemma>tett</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>pos</LM>
                <LM>fl</LM>
              </feats>
              <deprel>ATR</deprel>
              <childnodes order="12">
                <form>gode</form>
                <lemma>god</lemma>
                <cpostag>adj</cpostag>
                <postag>adj</postag>
                <feats>
                  <LM>pos</LM>
                  <LM>fl</LM>
                </feats>
                <deprel>KOORD</deprel>
                <childnodes order="11">
                  <form>og</form>
                  <lemma>og</lemma>
                  <cpostag>konj</cpostag>
                  <postag>konj</postag>
                  <feats>&lt;ikkje-clb></feats>
                  <deprel>KONJ</deprel>
                </childnodes>
              </childnodes>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="14">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>har</form>
      <lemma>ha</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Ho</form>
          <lemma>ho</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>fem</LM>
            <LM>eint</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>skapt</form>
          <lemma>skape</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>perf-part</feats>
          <deprel>INFV</deprel>
          <childnodes order="5">
            <form>pageturner</form>
            <lemma>pageturner</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
              <LM>unorm</LM>
            </feats>
            <deprel>DOBJ</deprel>
            <childnodes order="4">
              <form>ein</form>
              <lemma>ein</lemma>
              <cpostag>det</cpostag>
              <postag>det</postag>
              <feats>
                <LM>kvant</LM>
                <LM>mask</LM>
                <LM>eint</LM>
              </feats>
              <deprel>DET</deprel>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="6">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>er</form>
      <lemma>vere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Boka</form>
          <lemma>bok</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>eint</LM>
            <LM>bu</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="5">
          <form>skildring</form>
          <lemma>skildring</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SPRED</deprel>
          <childnodes>
            <LM order="3">
              <form>ei</form>
              <lemma>ein</lemma>
              <cpostag>det</cpostag>
              <postag>det</postag>
              <feats>
                <LM>kvant</LM>
                <LM>fem</LM>
                <LM>eint</LM>
              </feats>
              <deprel>DET</deprel>
            </LM>
            <LM order="4">
              <form>sår</form>
              <lemma>sår</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>pos</LM>
                <LM>m/f</LM>
                <LM>ub</LM>
                <LM>eint</LM>
              </feats>
              <deprel>ATR</deprel>
            </LM>
            <LM order="6">
              <form>om</form>
              <lemma>om</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes>
                <LM order="9">
                  <form>historier</form>
                  <lemma>historie</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>fem</LM>
                    <LM>appell</LM>
                    <LM>ub</LM>
                    <LM>fl</LM>
                  </feats>
                  <deprel>PUTFYLL</deprel>
                  <childnodes>
                    <LM order="7">
                      <form>to</form>
                      <lemma>to</lemma>
                      <cpostag>det</cpostag>
                      <postag>det</postag>
                      <feats>
                        <LM>kvant</LM>
                        <LM>fl</LM>
                      </feats>
                      <deprel>DET</deprel>
                    </LM>
                    <LM order="8">
                      <form>parallelle</form>
                      <lemma>parallell</lemma>
                      <cpostag>adj</cpostag>
                      <postag>adj</postag>
                      <feats>
                        <LM>pos</LM>
                        <LM>fl</LM>
                      </feats>
                      <deprel>ATR</deprel>
                    </LM>
                  </childnodes>
                </LM>
                <LM order="10">
                  <form>,</form>
                  <lemma>$,</lemma>
                  <cpostag>&lt;komma&gt;</cpostag>
                  <postag>&lt;komma&gt;</postag>
                  <deprel>IK</deprel>
                </LM>
                <LM order="11">
                  <form>om</form>
                  <lemma>om</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>APP</deprel>
                  <childnodes order="14">
                    <form>tettstad</form>
                    <lemma>tettstad</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>mask</LM>
                      <LM>appell</LM>
                      <LM>ub</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>PUTFYLL</deprel>
                    <childnodes>
                      <LM order="12">
                        <form>ein</form>
                        <lemma>ein</lemma>
                        <cpostag>det</cpostag>
                        <postag>det</postag>
                        <feats>
                          <LM>kvant</LM>
                          <LM>mask</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>DET</deprel>
                      </LM>
                      <LM order="13">
                        <form>forlaten</form>
                        <lemma>forlate</lemma>
                        <cpostag>adj</cpostag>
                        <postag>adj</postag>
                        <feats>
                          <LM>&lt;perf-part></LM>
                          <LM>m/f</LM>
                          <LM>ub</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>ATR</deprel>
                      </LM>
                      <LM order="18">
                        <form>kvinne</form>
                        <lemma>kvinne</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>
                          <LM>fem</LM>
                          <LM>appell</LM>
                          <LM>ub</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>KOORD</deprel>
                        <childnodes>
                          <LM order="15">
                            <form>og</form>
                            <lemma>og</lemma>
                            <cpostag>konj</cpostag>
                            <postag>konj</postag>
                            <feats>&lt;ikkje-clb></feats>
                            <deprel>KONJ</deprel>
                          </LM>
                          <LM order="16">
                            <form>ei</form>
                            <lemma>ein</lemma>
                            <cpostag>det</cpostag>
                            <postag>det</postag>
                            <feats>
                              <LM>kvant</LM>
                              <LM>fem</LM>
                              <LM>eint</LM>
                            </feats>
                            <deprel>DET</deprel>
                          </LM>
                          <LM order="17">
                            <form>sorgtung</form>
                            <lemma>sorgtung</lemma>
                            <cpostag>adj</cpostag>
                            <postag>adj</postag>
                            <feats>
                              <LM>pos</LM>
                              <LM>m/f</LM>
                              <LM>ub</LM>
                              <LM>eint</LM>
                            </feats>
                            <deprel>ATR</deprel>
                          </LM>
                        </childnodes>
                      </LM>
                    </childnodes>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="19">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>maktar</form>
      <lemma>makte</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pres</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Eikemo</form>
          <lemma>Eikemo</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>prop</feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>å</form>
          <lemma>å</lemma>
          <cpostag>inf-merke</cpostag>
          <postag>inf-merke</postag>
          <deprel>DOBJ</deprel>
          <childnodes order="4">
            <form>vikle</form>
            <lemma>vikle</lemma>
            <cpostag>verb</cpostag>
            <postag>verb</postag>
            <feats>inf</feats>
            <deprel>INFV</deprel>
            <childnodes>
              <LM order="5">
                <form>kvinna</form>
                <lemma>kvinne</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>fem</LM>
                  <LM>appell</LM>
                  <LM>eint</LM>
                  <LM>bu</LM>
                </feats>
                <deprel>DOBJ</deprel>
                <childnodes order="7">
                  <form>staden</form>
                  <lemma>stad</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>mask</LM>
                    <LM>appell</LM>
                    <LM>eint</LM>
                    <LM>bu</LM>
                  </feats>
                  <deprel>KOORD</deprel>
                  <childnodes order="6">
                    <form>og</form>
                    <lemma>og</lemma>
                    <cpostag>konj</cpostag>
                    <postag>konj</postag>
                    <feats>&lt;ikkje-clb></feats>
                    <deprel>KONJ</deprel>
                  </childnodes>
                </childnodes>
              </LM>
              <LM order="8">
                <form>saman</form>
                <lemma>saman</lemma>
                <cpostag>adv</cpostag>
                <postag>adv</postag>
                <deprel>ADV</deprel>
              </LM>
              <LM order="9">
                <form>til</form>
                <lemma>til</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ADV</deprel>
                <childnodes order="11">
                  <form>historie</form>
                  <lemma>historie</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>fem</LM>
                    <LM>appell</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>PUTFYLL</deprel>
                  <childnodes order="10">
                    <form>ei</form>
                    <lemma>ein</lemma>
                    <cpostag>det</cpostag>
                    <postag>det</postag>
                    <feats>
                      <LM>kvant</LM>
                      <LM>fem</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>DET</deprel>
                  </childnodes>
                </childnodes>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="12">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="5">
      <form>er</form>
      <lemma>vere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="2">
          <form>kvinnekroppen</form>
          <lemma>kvinnekropp</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>eint</LM>
            <LM>bu</LM>
            <LM>samset</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes>
            <LM order="1">
              <form>Både</form>
              <lemma>både</lemma>
              <cpostag>konj</cpostag>
              <postag>konj</postag>
              <feats>
                <LM>&lt;ikkje-clb></LM>
                <LM>&lt;adv></LM>
              </feats>
              <deprel>KONJ</deprel>
            </LM>
            <LM order="4">
              <form>tettstaden</form>
              <lemma>tettstad</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
              </feats>
              <deprel>KOORD</deprel>
              <childnodes order="3">
                <form>og</form>
                <lemma>og</lemma>
                <cpostag>konj</cpostag>
                <postag>konj</postag>
                <feats>&lt;ikkje-clb></feats>
                <deprel>KONJ</deprel>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="6">
          <form>etterlatne</form>
          <lemma>etterlate</lemma>
          <cpostag>adj</cpostag>
          <postag>adj</postag>
          <feats>
            <LM>&lt;perf-part></LM>
            <LM>fl</LM>
          </feats>
          <deprel>SPRED</deprel>
        </LM>
        <LM order="7">
          <form>,</form>
          <lemma>$,</lemma>
          <cpostag>&lt;komma&gt;</cpostag>
          <postag>&lt;komma&gt;</postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="8">
          <form>svikne</form>
          <lemma>svike</lemma>
          <cpostag>adj</cpostag>
          <postag>adj</postag>
          <feats>
            <LM>&lt;perf-part></LM>
            <LM>fl</LM>
          </feats>
          <deprel>FSPRED</deprel>
          <childnodes order="9">
            <form>av</form>
            <lemma>av</lemma>
            <cpostag>prep</cpostag>
            <postag>prep</postag>
            <deprel>ADV</deprel>
            <childnodes order="10">
              <form>tida</form>
              <lemma>tid</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>fem</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
              </feats>
              <deprel>PUTFYLL</deprel>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="11">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>står</form>
      <lemma>stå</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pres</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Dei</form>
          <lemma>dei</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>fl</LM>
            <LM>hum</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>att</form>
          <lemma>att</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
        </LM>
        <LM order="4">
          <form>,</form>
          <lemma>$,</lemma>
          <cpostag>&lt;komma&gt;</cpostag>
          <postag>&lt;komma&gt;</postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="5">
          <form>tomme</form>
          <lemma>tom</lemma>
          <cpostag>adj</cpostag>
          <postag>adj</postag>
          <feats>
            <LM>pos</LM>
            <LM>fl</LM>
          </feats>
          <deprel>SPRED</deprel>
          <childnodes order="7">
            <form>utan</form>
            <lemma>utan</lemma>
            <cpostag>prep</cpostag>
            <postag>prep</postag>
            <deprel>KOORD</deprel>
            <childnodes>
              <LM order="6">
                <form>og</form>
                <lemma>og</lemma>
                <cpostag>konj</cpostag>
                <postag>konj</postag>
                <feats>&lt;ikkje-clb></feats>
                <deprel>KONJ</deprel>
              </LM>
              <LM order="8">
                <form>røyndom</form>
                <lemma>røyndom</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="9">
          <form>,</form>
          <lemma>$,</lemma>
          <cpostag>&lt;komma&gt;</cpostag>
          <postag>&lt;komma&gt;</postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="10">
          <form>som</form>
          <lemma>som</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
          <childnodes order="13">
            <form>dialekt</form>
            <lemma>dialekt</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
            </feats>
            <deprel>PUTFYLL</deprel>
            <childnodes>
              <LM order="11">
                <form>ein</form>
                <lemma>ein</lemma>
                <cpostag>det</cpostag>
                <postag>det</postag>
                <feats>
                  <LM>kvant</LM>
                  <LM>mask</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>DET</deprel>
              </LM>
              <LM order="12">
                <form>utdøydd</form>
                <lemma>utdøydd</lemma>
                <cpostag>adj</cpostag>
                <postag>adj</postag>
                <feats>
                  <LM>pos</LM>
                  <LM>m/f</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>ATR</deprel>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="14">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="3">
      <form>er</form>
      <lemma>vere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Eskil</form>
          <lemma>Eskil</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>prop</feats>
          <deprel>SUBJ</deprel>
          <childnodes order="2">
            <form>Skjeldal</form>
            <lemma>Skjeldal</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>prop</feats>
            <deprel>FLAT</deprel>
          </childnodes>
        </LM>
        <LM order="4">
          <form>stipendiat</form>
          <lemma>stipendiat</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>SPRED</deprel>
        </LM>
        <LM order="5">
          <form>ved</form>
          <lemma>ved</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
          <childnodes order="6">
            <form>Menighetsfakultetet</form>
            <lemma>Menighetsfakultetet</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>prop</feats>
            <deprel>PUTFYLL</deprel>
          </childnodes>
        </LM>
        <LM order="8">
          <form>melder</form>
          <lemma>melde</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>pres</feats>
          <deprel>KOORD</deprel>
          <childnodes>
            <LM order="7">
              <form>og</form>
              <lemma>og</lemma>
              <cpostag>konj</cpostag>
              <postag>konj</postag>
              <feats>clb</feats>
              <deprel>KONJ</deprel>
            </LM>
            <LM order="9">
              <form>bøker</form>
              <lemma>bok</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>fem</LM>
                <LM>appell</LM>
                <LM>ub</LM>
                <LM>fl</LM>
              </feats>
              <deprel>DOBJ</deprel>
            </LM>
            <LM order="10">
              <form>for</form>
              <lemma>for</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="11">
                <form>Dag</form>
                <lemma>Dag</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>prop</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="12">
                    <form>og</form>
                    <lemma>og</lemma>
                    <cpostag>konj</cpostag>
                    <postag>konj</postag>
                    <feats>&lt;ikkje-clb></feats>
                    <deprel>FLAT</deprel>
                  </LM>
                  <LM order="13">
                    <form>Tid</form>
                    <lemma>Tid</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>prop</feats>
                    <deprel>FLAT</deprel>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="14">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
  </body>
</conll>
