<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="3">
   <form>mållaus</form>
   <lemma>mållaus</lemma>
   <cpostag>adj</cpostag>
   <postag>adj</postag>
   <feats>
    <LM>pos</LM>
    <LM>m/f</LM>
    <LM>ub</LM>
    <LM>eint</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Heilt</form>
     <lemma>heil</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>pos</LM>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="4">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>var</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Og</form>
     <lemma>og</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>Tv-sjåarane</form>
     <lemma>Tv-sjåar</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>fl</LM>
      <LM>bu</LM>
      <LM>samset</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>samde</form>
     <lemma>samd</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>pos</LM>
      <LM>fl</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="5">
       <form>med</form>
       <lemma>med</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="6">
         <form>dommarane</form>
         <lemma>dommar</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>fl</LM>
          <LM>bu</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>fekk</form>
   <lemma>få</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Vegard</form>
     <lemma>Vegard</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>ein</form>
     <lemma>ein</lemma>
     <cpostag>det</cpostag>
     <postag>det</postag>
     <feats>
      <LM>kvant</LM>
      <LM>mask</LM>
      <LM>eint</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="4">
       <form>av</form>
       <lemma>av</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="8">
         <form>finaleplassane</form>
         <lemma>finaleplass</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>fl</LM>
          <LM>bu</LM>
          <LM>samset</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="5">
           <form>dei</form>
           <lemma>dei</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>fl</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="6">
           <form>to</form>
           <lemma>to</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>kvant</LM>
            <LM>fl</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="7">
           <form>første</form>
           <lemma>første</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>pos</LM>
            <LM>fl</LM>
            <LM>&lt;ordenstal&gt;</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>Gløym</form>
   <lemma>gløyme</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>imp</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="3">
     <form>Kurt</form>
     <lemma>Kurt</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>prop</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="7">
       <form>preferansar</form>
       <lemma>preferanse</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="4">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>&lt;ikkje-clb&gt;</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="5">
         <form>alle</form>
         <lemma>all</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>kvant</LM>
          <LM>fl</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="6">
         <form>andre</form>
         <lemma>annan</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>&lt;adj&gt;</LM>
          <LM>fl</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="9">
         <form>referansar</form>
         <lemma>referanse</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="8">
           <form>eller</form>
           <lemma>eller</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikkje-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="11">
     <form>var</form>
     <lemma>vere</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="12">
       <form>tilbakemeldinga</form>
       <lemma>tilbakemelding</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>fem</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="13">
         <form>frå</form>
         <lemma>frå</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="15">
           <form>Gunnar</form>
           <lemma>Gunnar</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>mask</LM>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="14">
             <form>dommar</form>
             <lemma>dommar</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>APP</deprel>
            </LM>
            <LM order="16">
             <form>Greve</form>
             <lemma>Greve</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>FLAT</deprel>
            </LM>
            <LM order="17">
             <form>Pettersen</form>
             <lemma>Pettersen</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>FLAT</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>er</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Eg</form>
     <lemma>eg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>1</LM>
      <LM>eint</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>mållaus</form>
     <lemma>mållaus</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>pos</LM>
      <LM>m/f</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="4">
       <form>heilt</form>
       <lemma>heil</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>finst</form>
   <lemma>finnast</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
    <LM>&lt;st-verb&gt;</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="3">
     <form>ikkje</form>
     <lemma>ikkje</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="4">
     <form>ord</form>
     <lemma>ord</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>PSUBJ</deprel>
     <childnodes>
      <LM order="5">
       <form>for</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="6">
         <form>dette</form>
         <lemma>dette</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>3</LM>
          <LM>nøyt</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="8">
     <form>sa</form>
     <lemma>seie</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="9">
       <form>Leite</form>
       <lemma>Leite</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="10">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="11">
         <form>vg.no</form>
         <lemma>vg.no</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="13">
       <form>etter</form>
       <lemma>etter</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="12">
         <form>like</form>
         <lemma>like</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="16">
         <form>fekk</form>
         <lemma>få</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>pret</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="14">
           <form>at</form>
           <lemma>at</lemma>
           <cpostag>sbu</cpostag>
           <postag>sbu</postag>
           <deprel>SBU</deprel>
          </LM>
          <LM order="15">
           <form>han</form>
           <lemma>han</lemma>
           <cpostag>pron</cpostag>
           <postag>pron</postag>
           <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>mask</LM>
            <LM>eint</LM>
            <LM>nom</LM>
           </feats>
           <deprel>SUBJ</deprel>
          </LM>
          <LM order="17">
           <form>beskjed</form>
           <lemma>beskjed</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DOBJ</deprel>
           <childnodes>
            <LM order="18">
             <form>om</form>
             <lemma>om</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="21">
               <form>er</form>
               <lemma>vere</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>pres</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
               <childnodes>
                <LM order="19">
                 <form>at</form>
                 <lemma>at</lemma>
                 <cpostag>sbu</cpostag>
                 <postag>sbu</postag>
                 <deprel>SBU</deprel>
                </LM>
                <LM order="20">
                 <form>han</form>
                 <lemma>han</lemma>
                 <cpostag>pron</cpostag>
                 <postag>pron</postag>
                 <feats>
                  <LM>pers</LM>
                  <LM>3</LM>
                  <LM>mask</LM>
                  <LM>eint</LM>
                  <LM>nom</LM>
                 </feats>
                 <deprel>SUBJ</deprel>
                </LM>
                <LM order="22">
                 <form>ein</form>
                 <lemma>ein</lemma>
                 <cpostag>det</cpostag>
                 <postag>det</postag>
                 <feats>
                  <LM>kvant</LM>
                  <LM>mask</LM>
                  <LM>eint</LM>
                 </feats>
                 <deprel>SPRED</deprel>
                 <childnodes>
                  <LM order="23">
                   <form>av</form>
                   <lemma>av</lemma>
                   <cpostag>prep</cpostag>
                   <postag>prep</postag>
                   <deprel>ATR</deprel>
                   <childnodes>
                    <LM order="25">
                     <form>to</form>
                     <lemma>to</lemma>
                     <cpostag>det</cpostag>
                     <postag>det</postag>
                     <feats>
                      <LM>kvant</LM>
                      <LM>fl</LM>
                     </feats>
                     <deprel>PUTFYLL</deprel>
                     <childnodes>
                      <LM order="24">
                       <form>dei</form>
                       <lemma>dei</lemma>
                       <cpostag>det</cpostag>
                       <postag>det</postag>
                       <feats>
                        <LM>dem</LM>
                        <LM>fl</LM>
                       </feats>
                       <deprel>DET</deprel>
                      </LM>
                      <LM order="27">
                       <form>går</form>
                       <lemma>gå</lemma>
                       <cpostag>verb</cpostag>
                       <postag>verb</postag>
                       <feats>
                        <LM>pres</LM>
                       </feats>
                       <deprel>ATR</deprel>
                       <childnodes>
                        <LM order="26">
                         <form>som</form>
                         <lemma>som</lemma>
                         <cpostag>sbu</cpostag>
                         <postag>sbu</postag>
                         <deprel>SBU</deprel>
                        </LM>
                        <LM order="28">
                         <form>vidare</form>
                         <lemma>vid</lemma>
                         <cpostag>adj</cpostag>
                         <postag>adj</postag>
                         <feats>
                          <LM>komp</LM>
                         </feats>
                         <deprel>ADV</deprel>
                        </LM>
                        <LM order="29">
                         <form>til</form>
                         <lemma>til</lemma>
                         <cpostag>prep</cpostag>
                         <postag>prep</postag>
                         <deprel>ADV</deprel>
                         <childnodes>
                          <LM order="30">
                           <form>finalen</form>
                           <lemma>finale</lemma>
                           <cpostag>subst</cpostag>
                           <postag>subst</postag>
                           <feats>
                            <LM>mask</LM>
                            <LM>appell</LM>
                            <LM>eint</LM>
                            <LM>bu</LM>
                           </feats>
                           <deprel>PUTFYLL</deprel>
                           <childnodes>
                            <LM order="31">
                             <form>i</form>
                             <lemma>i</lemma>
                             <cpostag>prep</cpostag>
                             <postag>prep</postag>
                             <deprel>ATR</deprel>
                             <childnodes>
                              <LM order="32">
                               <form>Idol</form>
                               <lemma>Idol</lemma>
                               <cpostag>subst</cpostag>
                               <postag>subst</postag>
                               <feats>
                                <LM>prop</LM>
                               </feats>
                               <deprel>PUTFYLL</deprel>
                              </LM>
                             </childnodes>
                            </LM>
                           </childnodes>
                          </LM>
                         </childnodes>
                        </LM>
                       </childnodes>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="33">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Familien</form>
   <lemma>familie</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>mask</LM>
    <LM>appell</LM>
    <LM>eint</LM>
    <LM>bu</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="3">
       <form>salen</form>
       <lemma>sal</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>heila</form>
   <lemma>heile</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Frå</form>
     <lemma>frå</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="2">
       <form>salen</form>
       <lemma>sal</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>familie</form>
     <lemma>familie</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="6">
       <form>venner</form>
       <lemma>venn</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="5">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>&lt;ikkje-clb&gt;</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="8">
       <form>Vegard</form>
       <lemma>Vegard</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>prop</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="4">
   <form>var</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="6">
     <form>familiemedlemmer</form>
     <lemma>familiemedlem</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="5">
       <form>åtte</form>
       <lemma>åtte</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>kvant</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>reist</form>
     <lemma>reise</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>&lt;perf-part&gt;</LM>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="2">
       <form>frå</form>
       <lemma>frå</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="1">
         <form>Berre</form>
         <lemma>berre</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="3">
         <form>Værlandet</form>
         <lemma>Værlandet</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="8">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="9">
         <form>Oslo</form>
         <lemma>Oslo</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="10">
       <form>for</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="11">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="12">
           <form>få</form>
           <lemma>få</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="13">
             <form>med</form>
             <lemma>med</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="14">
               <form>seg</form>
               <lemma>seg</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>eint</LM>
                <LM>akk</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
            <LM order="15">
             <form>direktesendinga</form>
             <lemma>direktesending</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>fem</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
             </feats>
             <deprel>DOBJ</deprel>
            </LM>
            <LM order="16">
             <form>frå</form>
             <lemma>frå</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="17">
               <form>salen</form>
               <lemma>sal</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>hadde</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Til</form>
     <lemma>til</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="2">
       <form>saman</form>
       <lemma>saman</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>Vegard</form>
     <lemma>Vegard</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="6">
     <form>25</form>
     <lemma>25</lemma>
     <cpostag>det</cpostag>
     <postag>det</postag>
     <feats>
      <LM>kvant</LM>
      <LM>fl</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="5">
       <form>minst</form>
       <lemma>liten</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>sup</LM>
        <LM>ub</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
      <LM order="7">
       <form>av</form>
       <lemma>av</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="9">
         <form>næraste</form>
         <lemma>nær</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>sup</LM>
          <LM>bu</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="8">
           <form>sine</form>
           <lemma>sin</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>poss</LM>
            <LM>fl</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>OPRED</deprel>
     <childnodes>
      <LM order="11">
       <form>salen</form>
       <lemma>sal</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>fredag</form>
     <lemma>fredag</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="13">
       <form>kveld</form>
       <lemma>kveld</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
