<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="6">
   <form>kjem</form>
   <lemma>kome</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Med</form>
     <lemma>med</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="5">
       <form>vêr</form>
       <lemma>vêr</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="2">
         <form>våt</form>
         <lemma>våt</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>eint</LM>
          <LM>unorm</LM>
         </feats>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="4">
           <form>kaldt</form>
           <lemma>kald</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>pos</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="3">
             <form>og</form>
             <lemma>og</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>&lt;ikkje-clb&gt;</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>ofte</form>
     <lemma>ofte</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>pos</LM>
      <LM>&lt;adv&gt;</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="8">
     <form>doggen</form>
     <lemma>dogg</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>fem</LM>
      <LM>appell</LM>
      <LM>eint</LM>
      <LM>bu</LM>
      <LM>unorm</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="9">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="10">
       <form>bilvindauga</form>
       <lemma>bilvindauge</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>appell</LM>
        <LM>fl</LM>
        <LM>bu</LM>
        <LM>samset</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="15">
     <form>kan</form>
     <lemma>kunne</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="12">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="16">
       <form>ein</form>
       <lemma>ein</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>eint</LM>
        <LM>hum</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="17">
       <form>observere</form>
       <lemma>observere</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="14">
         <form>sjeldan</form>
         <lemma>sjeldan</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="13">
           <form>ikkje</form>
           <lemma>ikkje</lemma>
           <cpostag>adv</cpostag>
           <postag>adv</postag>
           <deprel>ADV</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="18">
         <form>bilar</form>
         <lemma>bil</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="19">
           <form>med</form>
           <lemma>med</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="20">
             <form>frontruta</form>
             <lemma>frontrute</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>fem</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="27">
               <form>sikt</form>
               <lemma>sikt</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>fem</LM>
                <LM>appell</LM>
                <LM>ub</LM>
                <LM>eint</LM>
               </feats>
               <deprel>KOORD</deprel>
               <childnodes>
                <LM order="24">
                 <form>og</form>
                 <lemma>og</lemma>
                 <cpostag>konj</cpostag>
                 <postag>konj</postag>
                 <feats>
                  <LM>&lt;ikkje-clb&gt;</LM>
                 </feats>
                 <deprel>KONJ</deprel>
                </LM>
                <LM order="26">
                 <form>null</form>
                 <lemma>null</lemma>
                 <cpostag>det</cpostag>
                 <postag>det</postag>
                 <feats>
                  <LM>kvant</LM>
                  <LM>fl</LM>
                 </feats>
                 <deprel>DET</deprel>
                 <childnodes>
                  <LM order="25">
                   <form>tilnærma</form>
                   <lemma>tilnærma</lemma>
                   <cpostag>adj</cpostag>
                   <postag>adj</postag>
                   <feats>
                    <LM>pos</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                   </feats>
                   <deprel>ADV</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
            <LM order="21">
             <form>full</form>
             <lemma>full</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>m/f</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>OPRED</deprel>
             <childnodes>
              <LM order="22">
               <form>i</form>
               <lemma>i</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="23">
                 <form>dogg</form>
                 <lemma>dogg</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>fem</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
            <LM order="28">
             <form>,</form>
             <lemma>$,</lemma>
             <cpostag>&lt;komma&gt;</cpostag>
             <postag>&lt;komma&gt;</postag>
             <deprel>IK</deprel>
            </LM>
            <LM order="29">
             <form>noko</form>
             <lemma>noko</lemma>
             <cpostag>pron</cpostag>
             <postag>pron</postag>
             <feats>
              <LM>pers</LM>
              <LM>3</LM>
              <LM>nøyt</LM>
              <LM>eint</LM>
             </feats>
             <deprel>APP</deprel>
             <childnodes>
              <LM order="31">
               <form>kan</form>
               <lemma>kunne</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>pres</LM>
               </feats>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="30">
                 <form>som</form>
                 <lemma>som</lemma>
                 <cpostag>sbu</cpostag>
                 <postag>sbu</postag>
                 <deprel>SBU</deprel>
                </LM>
                <LM order="32">
                 <form>vere</form>
                 <lemma>vere</lemma>
                 <cpostag>verb</cpostag>
                 <postag>verb</postag>
                 <feats>
                  <LM>inf</LM>
                 </feats>
                 <deprel>INFV</deprel>
                 <childnodes>
                  <LM order="33">
                   <form>livsfarleg</form>
                   <lemma>livsfarleg</lemma>
                   <cpostag>adj</cpostag>
                   <postag>adj</postag>
                   <feats>
                    <LM>pos</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                   </feats>
                   <deprel>SPRED</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="34">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>er</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="4">
     <form>betre</form>
     <lemma>bra</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>komp</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="16">
       <form>enn</form>
       <lemma>enn</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="17">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="18">
           <form>ta</form>
           <lemma>ta</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="19">
             <form>sjansar</form>
             <lemma>sjanse</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>fl</LM>
             </feats>
             <deprel>DOBJ</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>å</form>
     <lemma>å</lemma>
     <cpostag>inf-merke</cpostag>
     <postag>inf-merke</postag>
     <deprel>PSUBJ</deprel>
     <childnodes>
      <LM order="6">
       <form>vente</form>
       <lemma>vente</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="8">
         <form>minutt</form>
         <lemma>minutt</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="7">
           <form>nokre</form>
           <lemma>nokon</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>kvant</LM>
            <LM>fl</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="14">
         <form>er</form>
         <lemma>vere</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>pres</LM>
         </feats>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="10">
           <form>at</form>
           <lemma>at</lemma>
           <cpostag>sbu</cpostag>
           <postag>sbu</postag>
           <deprel>SBU</deprel>
           <childnodes>
            <LM order="9">
             <form>slik</form>
             <lemma>slik</lemma>
             <cpostag>adv</cpostag>
             <postag>adv</postag>
             <deprel>ADV</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="11">
           <form>dogg</form>
           <lemma>dogg</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>SUBJ</deprel>
           <childnodes>
            <LM order="13">
             <form>is</form>
             <lemma>is</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>KOORD</deprel>
             <childnodes>
              <LM order="12">
               <form>og</form>
               <lemma>og</lemma>
               <cpostag>konj</cpostag>
               <postag>konj</postag>
               <feats>
                <LM>&lt;ikkje-clb&gt;</LM>
               </feats>
               <deprel>KONJ</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
          <LM order="15">
           <form>fjerna</form>
           <lemma>fjerne</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>&lt;perf-part&gt;</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>INFV</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="20">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="21">
     <form>meiner</form>
     <lemma>meine</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="22">
       <form>Voll</form>
       <lemma>Voll</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="23">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="4">
   <form>er</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="3">
     <form>ting</form>
     <lemma>ting</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="2">
       <form>Ein</form>
       <lemma>ein</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>kvant</LM>
        <LM>mask</LM>
        <LM>eint</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>tryggleiken</form>
     <lemma>tryggleik</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>eint</LM>
      <LM>bu</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="6">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="7">
         <form>sjåføren</form>
         <lemma>sjåfør</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="10">
     <form>kva</form>
     <lemma>kva</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ikke-hum</LM>
      <LM>sp</LM>
     </feats>
     <deprel>KOORD-ELL</deprel>
     <childnodes>
      <LM order="9">
       <form>men</form>
       <lemma>men</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="13">
       <form>køyrer</form>
       <lemma>køyre</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="11">
         <form>om</form>
         <lemma>om</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="12">
         <form>ein</form>
         <lemma>ein</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>eint</LM>
          <LM>hum</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="14">
         <form>ned-</form>
         <lemma>ned</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <feats>
          <LM>unorm</LM>
         </feats>
         <deprel>ADV</deprel>
        </LM>
        <LM order="16">
         <form>rygger</form>
         <lemma>rygge</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>pres</LM>
          <LM>unorm</LM>
         </feats>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="15">
           <form>eller</form>
           <lemma>eller</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>clb</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
          <LM order="17">
           <form>på</form>
           <lemma>på</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
          </LM>
          <LM order="19">
           <form>skadar</form>
           <lemma>skade</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pres</LM>
            <LM>unorm</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="18">
             <form>og</form>
             <lemma>og</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>clb</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
            <LM order="21">
             <form>born</form>
             <lemma>barn</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>nøyt</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
              <LM>unorm</LM>
             </feats>
             <deprel>DOBJ</deprel>
             <childnodes>
              <LM order="20">
               <form>eit</form>
               <lemma>ein</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>kvant</LM>
                <LM>nøyt</LM>
                <LM>eint</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
              <LM order="23">
               <form>andre</form>
               <lemma>annan</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>dem</LM>
                <LM>&lt;adj&gt;</LM>
                <LM>fl</LM>
               </feats>
               <deprel>KOORD</deprel>
               <childnodes>
                <LM order="22">
                 <form>eller</form>
                 <lemma>eller</lemma>
                 <cpostag>konj</cpostag>
                 <postag>konj</postag>
                 <feats>
                  <LM>&lt;ikkje-clb&gt;</LM>
                 </feats>
                 <deprel>KONJ</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="24">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="25">
     <form>avsluttar</form>
     <lemma>avslutte</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="26">
       <form>Arne</form>
       <lemma>Arne</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="27">
         <form>Voll</form>
         <lemma>Voll</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
        <LM order="28">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="29">
           <form>Gjensidige</form>
           <lemma>Gjensidige</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="30">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="31">
         <form>firda.no</form>
         <lemma>firda.no</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="32">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
