<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="2">
   <form>var</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>snarare</form>
     <lemma>snar</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>komp</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="6">
     <form>oppgåve</form>
     <lemma>oppgåve</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>fem</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="4">
       <form>ei</form>
       <lemma>ein</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>kvant</LM>
        <LM>fem</LM>
        <LM>eint</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="5">
       <form>moralsk</form>
       <lemma>moralsk</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>m/f</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>for</form>
     <lemma>for</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="8">
       <form>han</form>
       <lemma>han</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>mask</LM>
        <LM>eint</LM>
        <LM>akk</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="11">
     <form>dreiv</form>
     <lemma>drive</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="10">
       <form>han</form>
       <lemma>han</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>mask</LM>
        <LM>eint</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="12">
       <form>med</form>
       <lemma>med</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="13">
         <form>fysikk</form>
         <lemma>fysikk</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="14">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="17">
         <form>ånd</form>
         <lemma>ånd</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>fem</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="16">
           <form>protestantisk</form>
           <lemma>protestantisk</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>pos</LM>
            <LM>m/f</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="15">
             <form>klassisk</form>
             <lemma>klassisk</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>m/f</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>ADV</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="18">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="19">
       <form>som</form>
       <lemma>som</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>FOPRED</deprel>
       <childnodes>
        <LM order="21">
         <form>arbeid</form>
         <lemma>arbeid</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="20">
           <form>hardt</form>
           <lemma>hard</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>pos</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
          <LM order="22">
           <form>utan</form>
           <lemma>utan</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="23">
             <form>tanke</form>
             <lemma>tanke</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="24">
               <form>for</form>
               <lemma>for</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="25">
                 <form>belønning</form>
                 <lemma>belønning</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>fem</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                  <LM>samset</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="28">
                   <form>berømming</form>
                   <lemma>berømming</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>fem</LM>
                    <LM>appell</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                    <LM>samset</LM>
                   </feats>
                   <deprel>KOORD</deprel>
                   <childnodes>
                    <LM order="26">
                     <form>eller</form>
                     <lemma>eller</lemma>
                     <cpostag>konj</cpostag>
                     <postag>konj</postag>
                     <feats>
                      <LM>&lt;ikkje-clb&gt;</LM>
                     </feats>
                     <deprel>KONJ</deprel>
                    </LM>
                    <LM order="27">
                     <form>personleg</form>
                     <lemma>personleg</lemma>
                     <cpostag>adj</cpostag>
                     <postag>adj</postag>
                     <feats>
                      <LM>pos</LM>
                      <LM>m/f</LM>
                      <LM>ub</LM>
                      <LM>eint</LM>
                     </feats>
                     <deprel>ATR</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="29">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>ville</form>
   <lemma>vilje</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Einstein</form>
     <lemma>Einstein</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>kome</form>
     <lemma>kome</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="4">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="5">
         <form>berøring</form>
         <lemma>berøring</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>fem</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="6">
           <form>med</form>
           <lemma>med</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="9">
             <form>røynda</form>
             <lemma>røynd</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>fem</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="7">
               <form>den</form>
               <lemma>den</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>dem</LM>
                <LM>fem</LM>
                <LM>eint</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
              <LM order="8">
               <form>objektive</form>
               <lemma>objektiv</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>pos</LM>
                <LM>eint</LM>
                <LM>bu</LM>
               </feats>
               <deprel>ATR</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="15">
     <form>ville</form>
     <lemma>vilje</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="16">
       <form>han</form>
       <lemma>han</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>mask</LM>
        <LM>eint</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="17">
       <form>kome</form>
       <lemma>kome</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="11">
         <form>gjennom</form>
         <lemma>gjennom</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="12">
           <form>musikk</form>
           <lemma>musikk</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="14">
             <form>fysikk</form>
             <lemma>fysikk</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>KOORD</deprel>
             <childnodes>
              <LM order="13">
               <form>eller</form>
               <lemma>eller</lemma>
               <cpostag>konj</cpostag>
               <postag>konj</postag>
               <feats>
                <LM>&lt;ikkje-clb&gt;</LM>
               </feats>
               <deprel>KONJ</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="18">
         <form>inn</form>
         <lemma>inn</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="19">
           <form>i</form>
           <lemma>i</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="21">
             <form>sfære</form>
             <lemma>sfære</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="20">
               <form>ein</form>
               <lemma>ein</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>kvant</LM>
                <LM>mask</LM>
                <LM>eint</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
              <LM order="25">
               <form>fanst</form>
               <lemma>finnast</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>pret</LM>
                <LM>&lt;st-verb&gt;</LM>
               </feats>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="22">
                 <form>der</form>
                 <lemma>der</lemma>
                 <cpostag>sbu</cpostag>
                 <postag>sbu</postag>
                 <deprel>SBU</deprel>
                </LM>
                <LM order="23">
                 <form>det</form>
                 <lemma>det</lemma>
                 <cpostag>pron</cpostag>
                 <postag>pron</postag>
                 <feats>
                  <LM>pers</LM>
                  <LM>3</LM>
                  <LM>nøyt</LM>
                  <LM>eint</LM>
                 </feats>
                 <deprel>FSUBJ</deprel>
                </LM>
                <LM order="24">
                 <form>ikkje</form>
                 <lemma>ikkje</lemma>
                 <cpostag>adv</cpostag>
                 <postag>adv</postag>
                 <deprel>ADV</deprel>
                </LM>
                <LM order="27">
                 <form>draumar</form>
                 <lemma>draum</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>fl</LM>
                 </feats>
                 <deprel>PSUBJ</deprel>
                 <childnodes>
                  <LM order="26">
                   <form>menneskelege</form>
                   <lemma>menneskeleg</lemma>
                   <cpostag>adj</cpostag>
                   <postag>adj</postag>
                   <feats>
                    <LM>pos</LM>
                    <LM>fl</LM>
                   </feats>
                   <deprel>ATR</deprel>
                  </LM>
                  <LM order="29">
                   <form>vilje</form>
                   <lemma>vilje</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>mask</LM>
                    <LM>appell</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                   </feats>
                   <deprel>KOORD</deprel>
                   <childnodes>
                    <LM order="28">
                     <form>eller</form>
                     <lemma>eller</lemma>
                     <cpostag>konj</cpostag>
                     <postag>konj</postag>
                     <feats>
                      <LM>&lt;ikkje-clb&gt;</LM>
                     </feats>
                     <deprel>KONJ</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
            <LM order="30">
             <form>,</form>
             <lemma>$,</lemma>
             <cpostag>&lt;komma&gt;</cpostag>
             <postag>&lt;komma&gt;</postag>
             <deprel>IK</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="31">
           <form>inn</form>
           <lemma>inn</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="32">
             <form>til</form>
             <lemma>til</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="35">
               <form>objektiviteten</form>
               <lemma>objektivitet</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
               <childnodes>
                <LM order="33">
                 <form>den</form>
                 <lemma>den</lemma>
                 <cpostag>det</cpostag>
                 <postag>det</postag>
                 <feats>
                  <LM>dem</LM>
                  <LM>fem</LM>
                  <LM>eint</LM>
                 </feats>
                 <deprel>DET</deprel>
                </LM>
                <LM order="34">
                 <form>reine</form>
                 <lemma>rein</lemma>
                 <cpostag>adj</cpostag>
                 <postag>adj</postag>
                 <feats>
                  <LM>pos</LM>
                  <LM>eint</LM>
                  <LM>bu</LM>
                 </feats>
                 <deprel>ATR</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="36">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>var</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Einstein</form>
     <lemma>Einstein</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>inspirert</form>
     <lemma>inspirere</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>&lt;perf-part&gt;</LM>
      <LM>m/f</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="3">
       <form>veldig</form>
       <lemma>veldig</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
      <LM order="5">
       <form>av</form>
       <lemma>av</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="7">
         <form>Schopenhauer</form>
         <lemma>Schopenhauer</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="6">
           <form>filosofen</form>
           <lemma>filosof</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>eint</LM>
            <LM>bu</LM>
           </feats>
           <deprel>APP</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="8">
   <form>kunne</form>
   <lemma>kunne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Og</form>
     <lemma>og</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="9">
     <form>han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>mask</LM>
      <LM>eint</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="12">
     <form>forstå</form>
     <lemma>forstå</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="3">
       <form>mediemerksemda</form>
       <lemma>mediemerksemd</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>fem</LM>
        <LM>appell</LM>
        <LM>eint</LM>
        <LM>bu</LM>
        <LM>samset</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="2">
         <form>all</form>
         <lemma>all</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>kvant</LM>
          <LM>fem</LM>
          <LM>eint</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="4">
         <form>om</form>
         <lemma>om</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="7">
           <form>person</form>
           <lemma>person</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="5">
             <form>sin</form>
             <lemma>sin</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>poss</LM>
              <LM>mask</LM>
              <LM>eint</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="6">
             <form>eigen</form>
             <lemma>eigen</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>&lt;adj&gt;</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>eint</LM>
              <LM>forst</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="11">
       <form>ikkje</form>
       <lemma>ikkje</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="10">
         <form>slett</form>
         <lemma>slett</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>ADV</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>var</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Einstein</form>
     <lemma>Einstein</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>smålåten</form>
     <lemma>smålåten</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>pos</LM>
      <LM>m/f</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="4">
       <form>oppriktig</form>
       <lemma>oppriktig</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>kunne</form>
     <lemma>kunne</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="6">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="9">
       <form>forstå</form>
       <lemma>forstå</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="8">
         <form>ikkje</form>
         <lemma>ikkje</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="11">
         <form>viraken</form>
         <lemma>virak</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="10">
           <form>all</form>
           <lemma>all</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>kvant</LM>
            <LM>mask</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="12">
           <form>rundt</form>
           <lemma>rundt</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="15">
             <form>person</form>
             <lemma>person</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="13">
               <form>hans</form>
               <lemma>hans</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>poss</LM>
                <LM>mask</LM>
                <LM>eint</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
              <LM order="14">
               <form>eigen</form>
               <lemma>eigen</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>&lt;adj&gt;</LM>
                <LM>mask</LM>
                <LM>ub</LM>
                <LM>eint</LM>
                <LM>forst</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="16">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>forstod</form>
   <lemma>forstå</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>mask</LM>
      <LM>eint</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>gjorde</form>
     <lemma>gjere</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>at</form>
       <lemma>at</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="4">
       <form>han</form>
       <lemma>han</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>mask</LM>
        <LM>eint</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="7">
       <form>innsats</form>
       <lemma>innsats</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="6">
         <form>ein</form>
         <lemma>ein</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>kvant</LM>
          <LM>mask</LM>
          <LM>eint</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="11">
     <form>oppfatta</form>
     <lemma>oppfatte</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="9">
       <form>men</form>
       <lemma>men</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="10">
       <form>han</form>
       <lemma>han</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>mask</LM>
        <LM>eint</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="17">
       <form>hadde</form>
       <lemma>ha</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pret</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="12">
         <form>at</form>
         <lemma>at</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="15">
         <form>fysikken</form>
         <lemma>fysikk</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>SUBJ</deprel>
         <childnodes>
          <LM order="13">
           <form>den</form>
           <lemma>den</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>mask</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="14">
           <form>teoretiske</form>
           <lemma>teoretisk</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>pos</LM>
            <LM>eint</LM>
            <LM>bu</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="18">
         <form>tatt</form>
         <lemma>ta</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>perf-part</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="16">
           <form>berre</form>
           <lemma>berre</lemma>
           <cpostag>adv</cpostag>
           <postag>adv</postag>
           <deprel>ADV</deprel>
          </LM>
          <LM order="22">
           <form>skritta</form>
           <lemma>skritt</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>nøyt</LM>
            <LM>appell</LM>
            <LM>fl</LM>
            <LM>bu</LM>
           </feats>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="19">
             <form>dei</form>
             <lemma>dei</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>dem</LM>
              <LM>fl</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="20">
             <form>første</form>
             <lemma>første</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>fl</LM>
              <LM>&lt;ordenstal&gt;</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
            <LM order="21">
             <form>vaklande</form>
             <lemma>vakle</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>&lt;pres-part&gt;</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="23">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
        <LM order="27">
         <form>var</form>
         <lemma>vere</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>pret</LM>
         </feats>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="24">
           <form>og</form>
           <lemma>og</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikkje-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
          <LM order="25">
           <form>at</form>
           <lemma>at</lemma>
           <cpostag>sbu</cpostag>
           <postag>sbu</postag>
           <deprel>SBU</deprel>
          </LM>
          <LM order="26">
           <form>det</form>
           <lemma>det</lemma>
           <cpostag>pron</cpostag>
           <postag>pron</postag>
           <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
           </feats>
           <deprel>FSUBJ</deprel>
          </LM>
          <LM order="28">
           <form>naudsynt</form>
           <lemma>naudsynt</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>pos</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>SPRED</deprel>
          </LM>
          <LM order="29">
           <form>å</form>
           <lemma>å</lemma>
           <cpostag>inf-merke</cpostag>
           <postag>inf-merke</postag>
           <deprel>PSUBJ</deprel>
           <childnodes>
            <LM order="30">
             <form>vere</form>
             <lemma>vere</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>inf</LM>
             </feats>
             <deprel>INFV</deprel>
             <childnodes>
              <LM order="31">
               <form>audmjuk</form>
               <lemma>audmjuk</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>pos</LM>
                <LM>m/f</LM>
                <LM>ub</LM>
                <LM>eint</LM>
               </feats>
               <deprel>SPRED</deprel>
               <childnodes>
                <LM order="32">
                 <form>overfor</form>
                 <lemma>overfor</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="35">
                   <form>oppgåva</form>
                   <lemma>oppgåve</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>fem</LM>
                    <LM>appell</LM>
                    <LM>eint</LM>
                    <LM>bu</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                   <childnodes>
                    <LM order="33">
                     <form>den</form>
                     <lemma>den</lemma>
                     <cpostag>det</cpostag>
                     <postag>det</postag>
                     <feats>
                      <LM>dem</LM>
                      <LM>fem</LM>
                      <LM>eint</LM>
                     </feats>
                     <deprel>DET</deprel>
                    </LM>
                    <LM order="34">
                     <form>vidare</form>
                     <lemma>vid</lemma>
                     <cpostag>adj</cpostag>
                     <postag>adj</postag>
                     <feats>
                      <LM>komp</LM>
                     </feats>
                     <deprel>ATR</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="36">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
