<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="15">
   <form>synest</form>
   <lemma>synast</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
    <LM>&lt;st-verb&gt;</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="16">
     <form>kyrkja</form>
     <lemma>kyrkje</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>fem</LM>
      <LM>appell</LM>
      <LM>eint</LM>
      <LM>bu</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="17">
     <form>er</form>
     <lemma>vere</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="4">
       <form>blir</form>
       <lemma>bli</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="1">
         <form>At</form>
         <lemma>at</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="2">
         <form>dette</form>
         <lemma>dette</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>pers</LM>
          <LM>3</LM>
          <LM>nøyt</LM>
          <LM>eint</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
         <form>ikkje</form>
         <lemma>ikkje</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="7">
         <form>visitas</form>
         <lemma>visitas</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>SPRED</deprel>
         <childnodes>
          <LM order="5">
           <form>ein</form>
           <lemma>ein</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>kvant</LM>
            <LM>mask</LM>
            <LM>eint</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="6">
           <form>ordinær</form>
           <lemma>ordinær</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>pos</LM>
            <LM>m/f</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
          <LM order="8">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="13">
           <form>vitjing</form>
           <lemma>vitjing</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="9">
             <form>snarare</form>
             <lemma>snar</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>komp</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
            <LM order="10">
             <form>ei</form>
             <lemma>ein</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>kvant</LM>
              <LM>fem</LM>
              <LM>eint</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="12">
             <form>uformell</form>
             <lemma>uformell</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>pos</LM>
              <LM>m/f</LM>
              <LM>ub</LM>
              <LM>eint</LM>
             </feats>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="11">
               <form>meir</form>
               <lemma>mykje</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>komp</LM>
               </feats>
               <deprel>ADV</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="14">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="18">
       <form>positivt</form>
       <lemma>positiv</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>SPRED</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="19">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>er</form>
   <lemma>vere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Dette</form>
     <lemma>dette</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="6">
     <form>gest</form>
     <lemma>gest</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>mask</LM>
      <LM>appell</LM>
      <LM>ub</LM>
      <LM>eint</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="4">
       <form>ein</form>
       <lemma>ein</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>kvant</LM>
        <LM>mask</LM>
        <LM>eint</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="5">
       <form>fin</form>
       <lemma>fin</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>pos</LM>
        <LM>m/f</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
      <LM order="7">
       <form>av</form>
       <lemma>av</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="8">
         <form>biskopen</form>
         <lemma>biskop</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>appell</LM>
          <LM>eint</LM>
          <LM>bu</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>syner</form>
   <lemma>syne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>pers</LM>
      <LM>3</LM>
      <LM>nøyt</LM>
      <LM>eint</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="5">
     <form>er</form>
     <lemma>vere</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="3">
       <form>at</form>
       <lemma>at</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="4">
       <form>han</form>
       <lemma>han</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>mask</LM>
        <LM>eint</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="6">
       <form>interessert</form>
       <lemma>interessere</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>&lt;perf-part&gt;</LM>
        <LM>m/f</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>SPRED</deprel>
      </LM>
      <LM order="7">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="8">
         <form>smått</form>
         <lemma>liten</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>pos</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>eint</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="10">
           <form>stort</form>
           <lemma>stor</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>pos</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>eint</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="9">
             <form>og</form>
             <lemma>og</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>&lt;ikkje-clb&gt;</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
            <LM order="11">
             <form>i</form>
             <lemma>i</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="12">
               <form>bispedømet</form>
               <lemma>bispedøme</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>nøyt</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="15">
     <form>tek</form>
     <lemma>ta</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PSUBJ</deprel>
     <childnodes>
      <LM order="13">
       <form>når</form>
       <lemma>når</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="14">
       <form>han</form>
       <lemma>han</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>mask</LM>
        <LM>eint</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="16">
       <form>seg</form>
       <lemma>seg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>eint</LM>
        <LM>akk</LM>
       </feats>
       <deprel>IOBJ</deprel>
      </LM>
      <LM order="17">
       <form>tid</form>
       <lemma>tid</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>fem</LM>
        <LM>appell</LM>
        <LM>ub</LM>
        <LM>eint</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
      <LM order="18">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="19">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="20">
           <form>koma</form>
           <lemma>kome</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="21">
             <form>til</form>
             <lemma>til</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="22">
               <form>Dalen</form>
               <lemma>Dalen</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>prop</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
            <LM order="26">
             <form>på</form>
             <lemma>på</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="23">
               <form>meir</form>
               <lemma>mykje</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>komp</LM>
               </feats>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="25">
                 <form>mindre</form>
                 <lemma>liten</lemma>
                 <cpostag>adj</cpostag>
                 <postag>adj</postag>
                 <feats>
                  <LM>komp</LM>
                 </feats>
                 <deprel>KOORD</deprel>
                 <childnodes>
                  <LM order="24">
                   <form>eller</form>
                   <lemma>eller</lemma>
                   <cpostag>konj</cpostag>
                   <postag>konj</postag>
                   <feats>
                    <LM>&lt;ikkje-clb&gt;</LM>
                   </feats>
                   <deprel>KONJ</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
              <LM order="27">
               <form>sparket</form>
               <lemma>spark</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>nøyt</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="28">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="29">
     <form>avsluttar</form>
     <lemma>avslutte</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="30">
       <form>Ove</form>
       <lemma>Ove</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>mask</LM>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="31">
         <form>Kjell</form>
         <lemma>Kjell</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>mask</LM>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
        <LM order="32">
         <form>Huvestad</form>
         <lemma>Huvestad</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="33">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
