<?xml version="1.0" encoding="UTF-8"?>
<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
  <head>
    <schema href="out_schema.xml" />
  </head>
  <body>
    <LM order="4">
      <form>kjenner</form>
      <lemma>kjenne</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pres</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>-</form>
          <lemma>$-</lemma>
          <cpostag>&lt;strek></cpostag>
          <postag>&lt;strek></postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="2">
          <form>Innan</form>
          <lemma>innan</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
          <childnodes order="3">
            <form>folkemusikkmiljøet</form>
            <lemma>folkemusikkmiljø</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>nøyt</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
              <LM>samset</LM>
            </feats>
            <deprel>PUTFYLL</deprel>
          </childnodes>
        </LM>
        <LM order="5">
          <form>eg</form>
          <lemma>eg</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>1</LM>
            <LM>eint</LM>
            <LM>hum</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="7">
          <form>mange</form>
          <lemma>mange</lemma>
          <cpostag>adj</cpostag>
          <postag>adj</postag>
          <feats>
            <LM>pos</LM>
            <LM>fl</LM>
          </feats>
          <deprel>DOBJ</deprel>
          <childnodes order="6">
            <form>så</form>
            <lemma>så</lemma>
            <cpostag>adv</cpostag>
            <postag>adv</postag>
            <deprel>ADV</deprel>
            <childnodes order="11">
              <form>er</form>
              <lemma>vere</lemma>
              <cpostag>verb</cpostag>
              <postag>verb</postag>
              <feats>
                <LM>pres</LM>
              </feats>
              <deprel>ADV</deprel>
              <childnodes>
                <LM order="8">
                  <form>at</form>
                  <lemma>at</lemma>
                  <cpostag>sbu</cpostag>
                  <postag>sbu</postag>
                  <deprel>SBU</deprel>
                </LM>
                <LM order="9">
                  <form>det</form>
                  <lemma>det</lemma>
                  <cpostag>pron</cpostag>
                  <postag>pron</postag>
                  <feats>
                    <LM>pers</LM>
                    <LM>3</LM>
                    <LM>nøyt</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>FSUBJ</deprel>
                </LM>
                <LM order="10">
                  <form>ikkje</form>
                  <lemma>ikkje</lemma>
                  <cpostag>adv</cpostag>
                  <postag>adv</postag>
                  <deprel>ADV</deprel>
                </LM>
                <LM order="12">
                  <form>vanskeleg</form>
                  <lemma>vanskeleg</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>pos</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>SPRED</deprel>
                </LM>
                <LM order="13">
                  <form>å</form>
                  <lemma>å</lemma>
                  <cpostag>inf-merke</cpostag>
                  <postag>inf-merke</postag>
                  <deprel>PSUBJ</deprel>
                  <childnodes order="14">
                    <form>få</form>
                    <lemma>få</lemma>
                    <cpostag>verb</cpostag>
                    <postag>verb</postag>
                    <feats>
                      <LM>inf</LM>
                    </feats>
                    <deprel>INFV</deprel>
                    <childnodes order="15">
                      <form>lære</form>
                      <lemma>lære</lemma>
                      <cpostag>verb</cpostag>
                      <postag>verb</postag>
                      <feats>inf</feats>
                      <deprel>INFV</deprel>
                      <childnodes order="16">
                        <form>det</form>
                        <lemma>det</lemma>
                        <cpostag>pron</cpostag>
                        <postag>pron</postag>
                        <feats>
                          <LM>pers</LM>
                          <LM>3</LM>
                          <LM>nøyt</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>DOBJ</deprel>
                        <childnodes order="18">
                          <form>vil</form>
                          <lemma>vilje</lemma>
                          <cpostag>verb</cpostag>
                          <postag>verb</postag>
                          <feats>
                            <LM>pres</LM>
                          </feats>
                          <deprel>ATR</deprel>
                          <childnodes order="17">
                            <form>eg</form>
                            <lemma>eg</lemma>
                            <cpostag>pron</cpostag>
                            <postag>pron</postag>
                            <feats>
                              <LM>pers</LM>
                              <LM>1</LM>
                              <LM>eint</LM>
                              <LM>hum</LM>
                              <LM>nom</LM>
                            </feats>
                            <deprel>SUBJ</deprel>
                          </childnodes>
                        </childnodes>
                      </childnodes>
                    </childnodes>
                  </childnodes>
                </LM>
              </childnodes>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="19">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>har</form>
      <lemma>ha</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Dessutan</form>
          <lemma>dessutan</lemma>
          <cpostag>adv</cpostag>
          <postag>adv</postag>
          <deprel>ADV</deprel>
        </LM>
        <LM order="3">
          <form>eg</form>
          <lemma>eg</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>1</LM>
            <LM>eint</LM>
            <LM>hum</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="5">
          <form>høve</form>
          <lemma>høve</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>nøyt</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>DOBJ</deprel>
          <childnodes>
            <LM order="4">
              <form>godt</form>
              <lemma>god</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>pos</LM>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>eint</LM>
              </feats>
              <deprel>ATR</deprel>
            </LM>
            <LM order="6">
              <form>til</form>
              <lemma>til</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="7">
                <form>å</form>
                <lemma>å</lemma>
                <cpostag>inf-merke</cpostag>
                <postag>inf-merke</postag>
                <deprel>PUTFYLL</deprel>
                <childnodes order="8">
                  <form>drive</form>
                  <lemma>drive</lemma>
                  <cpostag>verb</cpostag>
                  <postag>verb</postag>
                  <feats>inf</feats>
                  <deprel>INFV</deprel>
                  <childnodes>
                    <LM order="9">
                      <form>med</form>
                      <lemma>med</lemma>
                      <cpostag>prep</cpostag>
                      <postag>prep</postag>
                      <deprel>ADV</deprel>
                      <childnodes order="10">
                        <form>spel</form>
                        <lemma>spel</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>
                          <LM>nøyt</LM>
                          <LM>appell</LM>
                          <LM>ub</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>PUTFYLL</deprel>
                      </childnodes>
                    </LM>
                    <LM order="11">
                      <form>samtidig</form>
                      <lemma>samtidig</lemma>
                      <cpostag>adj</cpostag>
                      <postag>adj</postag>
                      <feats>
                        <LM>pos</LM>
                        <LM>nøyt</LM>
                        <LM>ub</LM>
                        <LM>eint</LM>
                      </feats>
                      <deprel>ADV</deprel>
                      <childnodes order="12">
                        <form>med</form>
                        <lemma>med</lemma>
                        <cpostag>prep</cpostag>
                        <postag>prep</postag>
                        <deprel>ADV</deprel>
                        <childnodes order="13">
                          <form>tekstilstudiane</form>
                          <lemma>tekstilstudie</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>mask</LM>
                            <LM>appell</LM>
                            <LM>fl</LM>
                            <LM>bu</LM>
                            <LM>samset</LM>
                          </feats>
                          <deprel>PUTFYLL</deprel>
                        </childnodes>
                      </childnodes>
                    </LM>
                  </childnodes>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="14">
          <form>,</form>
          <lemma>$,</lemma>
          <cpostag>&lt;komma&gt;</cpostag>
          <postag>&lt;komma&gt;</postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="15">
          <form>understrekar</form>
          <lemma>understreke</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>pres</feats>
          <deprel>PAR</deprel>
          <childnodes order="16">
            <form>ho</form>
            <lemma>ho</lemma>
            <cpostag>pron</cpostag>
            <postag>pron</postag>
            <feats>
              <LM>pers</LM>
              <LM>3</LM>
              <LM>fem</LM>
              <LM>eint</LM>
              <LM>nom</LM>
            </feats>
            <deprel>SUBJ</deprel>
          </childnodes>
        </LM>
        <LM order="17">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>var</form>
      <lemma>vere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pret</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Sara</form>
          <lemma>Sara</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>fem</LM>
            <LM>prop</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>ikkje</form>
          <lemma>ikkje</lemma>
          <cpostag>adv</cpostag>
          <postag>adv</postag>
          <deprel>ADV</deprel>
        </LM>
        <LM order="5">
          <form>einaste</form>
          <lemma>einaste</lemma>
          <cpostag>det</cpostag>
          <postag>det</postag>
          <feats>
            <LM>kvant</LM>
            <LM>&lt;adj></LM>
            <LM>bu</LM>
          </feats>
          <deprel>SPRED</deprel>
          <childnodes>
            <LM order="4">
              <form>den</form>
              <lemma>den</lemma>
              <cpostag>det</cpostag>
              <postag>det</postag>
              <feats>
                <LM>dem</LM>
                <LM>fem</LM>
                <LM>eint</LM>
              </feats>
              <deprel>DET</deprel>
            </LM>
            <LM order="7">
              <form>gjorde</form>
              <lemma>gjere</lemma>
              <cpostag>verb</cpostag>
              <postag>verb</postag>
              <feats>pret</feats>
              <deprel>ATR</deprel>
              <childnodes>
                <LM order="6">
                  <form>som</form>
                  <lemma>som</lemma>
                  <cpostag>sbu</cpostag>
                  <postag>sbu</postag>
                  <deprel>SBU</deprel>
                </LM>
                <LM order="8">
                  <form>det</form>
                  <lemma>det</lemma>
                  <cpostag>pron</cpostag>
                  <postag>pron</postag>
                  <feats>
                    <LM>pers</LM>
                    <LM>3</LM>
                    <LM>nøyt</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>FOBJ</deprel>
                </LM>
                <LM order="9">
                  <form>godt</form>
                  <lemma>god</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>pos</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>OPRED</deprel>
                </LM>
                <LM order="10">
                  <form>i</form>
                  <lemma>i</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>ADV</deprel>
                  <childnodes order="11">
                    <form>B-klassa</form>
                    <lemma>B-klasse</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>fem</LM>
                      <LM>appell</LM>
                      <LM>eint</LM>
                      <LM>bu</LM>
                      <LM>samset</LM>
                    </feats>
                    <deprel>PUTFYLL</deprel>
                    <childnodes>
                      <LM order="12">
                        <form>for</form>
                        <lemma>for</lemma>
                        <cpostag>prep</cpostag>
                        <postag>prep</postag>
                        <deprel>ATR</deprel>
                        <childnodes order="13">
                          <form>hardingfele</form>
                          <lemma>hardingfele</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>fem</LM>
                            <LM>appell</LM>
                            <LM>ub</LM>
                            <LM>eint</LM>
                          </feats>
                          <deprel>PUTFYLL</deprel>
                        </childnodes>
                      </LM>
                      <LM order="14">
                        <form>,</form>
                        <lemma>$,</lemma>
                        <cpostag>&lt;komma&gt;</cpostag>
                        <postag>&lt;komma&gt;</postag>
                        <deprel>IK</deprel>
                      </LM>
                      <LM order="20">
                        <form>deltok</form>
                        <lemma>delta</lemma>
                        <cpostag>verb</cpostag>
                        <postag>verb</postag>
                        <feats>pret</feats>
                        <deprel>ATR</deprel>
                        <childnodes>
                          <LM order="15">
                            <form>der</form>
                            <lemma>der</lemma>
                            <cpostag>sbu</cpostag>
                            <postag>sbu</postag>
                            <deprel>SBU</deprel>
                          </LM>
                          <LM order="19">
                            <form>utøvarar</form>
                            <lemma>utøvar</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>mask</LM>
                              <LM>appell</LM>
                              <LM>ub</LM>
                              <LM>fl</LM>
                            </feats>
                            <deprel>SUBJ</deprel>
                            <childnodes>
                              <LM order="16">
                                <form>i</form>
                                <lemma>i</lemma>
                                <cpostag>prep</cpostag>
                                <postag>prep</postag>
                                <deprel>ATR</deprel>
                                <childnodes order="17">
                                  <form>alt</form>
                                  <lemma>alt</lemma>
                                  <cpostag>pron</cpostag>
                                  <postag>pron</postag>
                                  <feats>
                                    <LM>pers</LM>
                                    <LM>3</LM>
                                    <LM>nøyt</LM>
                                    <LM>eint</LM>
                                  </feats>
                                  <deprel>PUTFYLL</deprel>
                                </childnodes>
                              </LM>
                              <LM order="18">
                                <form>29</form>
                                <lemma>29</lemma>
                                <cpostag>det</cpostag>
                                <postag>det</postag>
                                <feats>
                                  <LM>kvant</LM>
                                  <LM>fl</LM>
                                </feats>
                                <deprel>DET</deprel>
                              </LM>
                            </childnodes>
                          </LM>
                        </childnodes>
                      </LM>
                    </childnodes>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="21">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="5">
      <form>spela</form>
      <lemma>spele</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pret</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Ottar</form>
          <lemma>Ottar</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>prop</feats>
          <deprel>SUBJ</deprel>
          <childnodes>
            <LM order="2">
              <form>Kåsa</form>
              <lemma>Kåsa</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>prop</feats>
              <deprel>FLAT</deprel>
            </LM>
            <LM order="3">
              <form>frå</form>
              <lemma>frå</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="4">
                <form>Arabygdi</form>
                <lemma>Arabygdi</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>prop</feats>
                <deprel>PUTFYLL</deprel>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="6">
          <form>seg</form>
          <lemma>seg</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>eint</LM>
            <LM>akk</LM>
          </feats>
          <deprel>DOBJ</deprel>
        </LM>
        <LM order="7">
          <form>opp</form>
          <lemma>opp</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>OPRED</deprel>
          <childnodes order="8">
            <form>i</form>
            <lemma>i</lemma>
            <cpostag>prep</cpostag>
            <postag>prep</postag>
            <deprel>PUTFYLL</deprel>
            <childnodes order="9">
              <form>A-klassa</form>
              <lemma>A-klasse</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>fem</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
                <LM>samset</LM>
              </feats>
              <deprel>PUTFYLL</deprel>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="10">
          <form>etter</form>
          <lemma>etter</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
          <childnodes order="11">
            <form>å</form>
            <lemma>å</lemma>
            <cpostag>inf-merke</cpostag>
            <postag>inf-merke</postag>
            <deprel>PUTFYLL</deprel>
            <childnodes>
              <LM order="12">
                <form>ha</form>
                <lemma>ha</lemma>
                <cpostag>verb</cpostag>
                <postag>verb</postag>
                <feats>
                  <LM>inf</LM>
                </feats>
                <deprel>INFV</deprel>
                <childnodes order="13">
                  <form>passert</form>
                  <lemma>passere</lemma>
                  <cpostag>verb</cpostag>
                  <postag>verb</postag>
                  <feats>perf-part</feats>
                  <deprel>INFV</deprel>
                  <childnodes>
                    <LM order="14">
                      <form>grensa</form>
                      <lemma>grense</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>fem</LM>
                        <LM>appell</LM>
                        <LM>eint</LM>
                        <LM>bu</LM>
                      </feats>
                      <deprel>DOBJ</deprel>
                      <childnodes order="15">
                        <form>på</form>
                        <lemma>på</lemma>
                        <cpostag>prep</cpostag>
                        <postag>prep</postag>
                        <deprel>ATR</deprel>
                        <childnodes order="17">
                          <form>poeng</form>
                          <lemma>poeng</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>nøyt</LM>
                            <LM>appell</LM>
                            <LM>ub</LM>
                            <LM>fl</LM>
                          </feats>
                          <deprel>PUTFYLL</deprel>
                          <childnodes order="16">
                            <form>114</form>
                            <lemma>114</lemma>
                            <cpostag>det</cpostag>
                            <postag>det</postag>
                            <feats>
                              <LM>kvant</LM>
                              <LM>fl</LM>
                            </feats>
                            <deprel>DET</deprel>
                          </childnodes>
                        </childnodes>
                      </childnodes>
                    </LM>
                    <LM order="18">
                      <form>for</form>
                      <lemma>for</lemma>
                      <cpostag>prep</cpostag>
                      <postag>prep</postag>
                      <deprel>ADV</deprel>
                      <childnodes order="20">
                        <form>gong</form>
                        <lemma>gong</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>
                          <LM>mask</LM>
                          <LM>appell</LM>
                          <LM>ub</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>PUTFYLL</deprel>
                        <childnodes order="19">
                          <form>andre</form>
                          <lemma>andre</lemma>
                          <cpostag>adj</cpostag>
                          <postag>adj</postag>
                          <feats>
                            <LM>pos</LM>
                            <LM>eint</LM>
                            <LM>bu</LM>
                            <LM>&lt;ordenstal></LM>
                          </feats>
                          <deprel>ATR</deprel>
                        </childnodes>
                      </childnodes>
                    </LM>
                    <LM order="21">
                      <form>,</form>
                      <lemma>$,</lemma>
                      <cpostag>&lt;komma&gt;</cpostag>
                      <postag>&lt;komma&gt;</postag>
                      <deprel>IK</deprel>
                    </LM>
                  </childnodes>
                </childnodes>
              </LM>
              <LM order="23">
                <form>innsats</form>
                <lemma>innsats</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>APP</deprel>
                <childnodes>
                  <LM order="22">
                    <form>ein</form>
                    <lemma>ein</lemma>
                    <cpostag>det</cpostag>
                    <postag>det</postag>
                    <feats>
                      <LM>kvant</LM>
                      <LM>mask</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>DET</deprel>
                  </LM>
                  <LM order="25">
                    <form>plasserte</form>
                    <lemma>plassere</lemma>
                    <cpostag>verb</cpostag>
                    <postag>verb</postag>
                    <feats>pret</feats>
                    <deprel>ATR</deprel>
                    <childnodes>
                      <LM order="24">
                        <form>som</form>
                        <lemma>som</lemma>
                        <cpostag>sbu</cpostag>
                        <postag>sbu</postag>
                        <deprel>SBU</deprel>
                      </LM>
                      <LM order="26">
                        <form>han</form>
                        <lemma>han</lemma>
                        <cpostag>pron</cpostag>
                        <postag>pron</postag>
                        <feats>
                          <LM>pers</LM>
                          <LM>3</LM>
                          <LM>mask</LM>
                          <LM>eint</LM>
                          <LM>akk</LM>
                        </feats>
                        <deprel>DOBJ</deprel>
                      </LM>
                      <LM order="27">
                        <form>som</form>
                        <lemma>som</lemma>
                        <cpostag>prep</cpostag>
                        <postag>prep</postag>
                        <deprel>OPRED</deprel>
                        <childnodes order="29">
                          <form>fem</form>
                          <lemma>fem</lemma>
                          <cpostag>det</cpostag>
                          <postag>det</postag>
                          <feats>
                            <LM>kvant</LM>
                            <LM>fl</LM>
                          </feats>
                          <deprel>PUTFYLL</deprel>
                          <childnodes order="28">
                            <form>nummer</form>
                            <lemma>nummer</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>nøyt</LM>
                              <LM>appell</LM>
                              <LM>ub</LM>
                              <LM>eint</LM>
                            </feats>
                            <deprel>ADV</deprel>
                          </childnodes>
                        </childnodes>
                      </LM>
                      <LM order="30">
                        <form>på</form>
                        <lemma>på</lemma>
                        <cpostag>prep</cpostag>
                        <postag>prep</postag>
                        <deprel>ADV</deprel>
                        <childnodes order="31">
                          <form>resultatlista</form>
                          <lemma>resultatliste</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>fem</LM>
                            <LM>appell</LM>
                            <LM>eint</LM>
                            <LM>bu</LM>
                            <LM>samset</LM>
                          </feats>
                          <deprel>PUTFYLL</deprel>
                        </childnodes>
                      </LM>
                    </childnodes>
                  </LM>
                </childnodes>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="32">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="7">
      <form>har</form>
      <lemma>ha</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="2">
          <form>Ingebjørg</form>
          <lemma>Ingebjørg</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>fem</LM>
            <LM>prop</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes>
            <LM order="1">
              <form>Nykonfirmerte</form>
              <lemma>nykonfirmert</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>pos</LM>
                <LM>eint</LM>
                <LM>bu</LM>
              </feats>
              <deprel>ATR</deprel>
            </LM>
            <LM order="3">
              <form>Harman</form>
              <lemma>Harman</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>prop</feats>
              <deprel>FLAT</deprel>
            </LM>
            <LM order="4">
              <form>Bratland</form>
              <lemma>Bratland</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>prop</feats>
              <deprel>FLAT</deprel>
            </LM>
            <LM order="5">
              <form>frå</form>
              <lemma>frå</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="6">
                <form>Edland</form>
                <lemma>Edland</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>prop</feats>
                <deprel>PUTFYLL</deprel>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="9">
          <form>rokke</form>
          <lemma>rekke</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>perf-part</feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="8">
              <form>alt</form>
              <lemma>alt</lemma>
              <cpostag>adv</cpostag>
              <postag>adv</postag>
              <deprel>ADV</deprel>
            </LM>
            <LM order="10">
              <form>å</form>
              <lemma>å</lemma>
              <cpostag>inf-merke</cpostag>
              <postag>inf-merke</postag>
              <deprel>DOBJ</deprel>
              <childnodes order="11">
                <form>bli</form>
                <lemma>bli</lemma>
                <cpostag>verb</cpostag>
                <postag>verb</postag>
                <feats>
                  <LM>inf</LM>
                </feats>
                <deprel>INFV</deprel>
                <childnodes>
                  <LM order="13">
                    <form>veteran</form>
                    <lemma>veteran</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>mask</LM>
                      <LM>appell</LM>
                      <LM>ub</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>SPRED</deprel>
                    <childnodes order="12">
                      <form>ein</form>
                      <lemma>ein</lemma>
                      <cpostag>det</cpostag>
                      <postag>det</postag>
                      <feats>
                        <LM>kvant</LM>
                        <LM>mask</LM>
                        <LM>eint</LM>
                      </feats>
                      <deprel>DET</deprel>
                    </childnodes>
                  </LM>
                  <LM order="14">
                    <form>i</form>
                    <lemma>i</lemma>
                    <cpostag>prep</cpostag>
                    <postag>prep</postag>
                    <deprel>ADV</deprel>
                    <childnodes order="15">
                      <form>landstoppen</form>
                      <lemma>landstopp</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>mask</LM>
                        <LM>appell</LM>
                        <LM>eint</LM>
                        <LM>bu</LM>
                        <LM>samset</LM>
                      </feats>
                      <deprel>PUTFYLL</deprel>
                      <childnodes order="16">
                        <form>i</form>
                        <lemma>i</lemma>
                        <cpostag>prep</cpostag>
                        <postag>prep</postag>
                        <deprel>ATR</deprel>
                        <childnodes order="17">
                          <form>kveding</form>
                          <lemma>kveding</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>fem</LM>
                            <LM>appell</LM>
                            <LM>ub</LM>
                            <LM>eint</LM>
                          </feats>
                          <deprel>PUTFYLL</deprel>
                        </childnodes>
                      </childnodes>
                    </childnodes>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="18">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="3">
      <form>skuffa</form>
      <lemma>skuffe</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pret</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Og</form>
          <lemma>og</lemma>
          <cpostag>konj</cpostag>
          <postag>konj</postag>
          <feats>clb</feats>
          <deprel>KONJ</deprel>
        </LM>
        <LM order="2">
          <form>ho</form>
          <lemma>ho</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>fem</LM>
            <LM>eint</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="5">
          <form>ikkje</form>
          <lemma>ikkje</lemma>
          <cpostag>adv</cpostag>
          <postag>adv</postag>
          <deprel>ADV</deprel>
          <childnodes order="4">
            <form>slett</form>
            <lemma>slett</lemma>
            <cpostag>adj</cpostag>
            <postag>adj</postag>
            <feats>
              <LM>pos</LM>
              <LM>nøyt</LM>
              <LM>ub</LM>
              <LM>eint</LM>
            </feats>
            <deprel>ADV</deprel>
          </childnodes>
        </LM>
        <LM order="8">
          <form>inntok</form>
          <lemma>innta</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>pret</feats>
          <deprel>ADV</deprel>
          <childnodes>
            <LM order="6">
              <form>der</form>
              <lemma>der</lemma>
              <cpostag>sbu</cpostag>
              <postag>sbu</postag>
              <deprel>SBU</deprel>
            </LM>
            <LM order="7">
              <form>ho</form>
              <lemma>ho</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>pers</LM>
                <LM>3</LM>
                <LM>fem</LM>
                <LM>eint</LM>
                <LM>nom</LM>
              </feats>
              <deprel>SUBJ</deprel>
            </LM>
            <LM order="9">
              <form>koret</form>
              <lemma>kor</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>nøyt</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
              </feats>
              <deprel>DOBJ</deprel>
              <childnodes order="10">
                <form>i</form>
                <lemma>i</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ATR</deprel>
                <childnodes order="11">
                  <form>Bergstaden</form>
                  <lemma>Bergstaden</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>prop</feats>
                  <deprel>PUTFYLL</deprel>
                  <childnodes>
                    <LM order="12">
                      <form>Ziir</form>
                      <lemma>Ziir</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>prop</feats>
                      <deprel>FLAT</deprel>
                    </LM>
                    <LM order="13">
                      <form>,</form>
                      <lemma>$,</lemma>
                      <cpostag>&lt;komma&gt;</cpostag>
                      <postag>&lt;komma&gt;</postag>
                      <deprel>IK</deprel>
                    </LM>
                    <LM order="16">
                      <form>steinkyrkja</form>
                      <lemma>steinkyrkje</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>fem</LM>
                        <LM>appell</LM>
                        <LM>eint</LM>
                        <LM>bu</LM>
                        <LM>samset</LM>
                      </feats>
                      <deprel>APP</deprel>
                      <childnodes>
                        <LM order="14">
                          <form>den</form>
                          <lemma>den</lemma>
                          <cpostag>det</cpostag>
                          <postag>det</postag>
                          <feats>
                            <LM>dem</LM>
                            <LM>fem</LM>
                            <LM>eint</LM>
                          </feats>
                          <deprel>DET</deprel>
                        </LM>
                        <LM order="15">
                          <form>monumentale</form>
                          <lemma>monumental</lemma>
                          <cpostag>adj</cpostag>
                          <postag>adj</postag>
                          <feats>
                            <LM>pos</LM>
                            <LM>eint</LM>
                            <LM>bu</LM>
                          </feats>
                          <deprel>ATR</deprel>
                        </LM>
                        <LM order="17">
                          <form>på</form>
                          <lemma>på</lemma>
                          <cpostag>prep</cpostag>
                          <postag>prep</postag>
                          <deprel>ATR</deprel>
                          <childnodes order="18">
                            <form>Røros</form>
                            <lemma>Røros</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>prop</feats>
                            <deprel>PUTFYLL</deprel>
                          </childnodes>
                        </LM>
                      </childnodes>
                    </LM>
                  </childnodes>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="19">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>song</form>
      <lemma>syngje</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pret</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Fyrst</form>
          <lemma>fyrst</lemma>
          <cpostag>adv</cpostag>
          <postag>adv</postag>
          <deprel>ADV</deprel>
        </LM>
        <LM order="3">
          <form>ho</form>
          <lemma>ho</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>fem</LM>
            <LM>eint</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="4">
          <form>Elsk</form>
          <lemma>Elsk</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>prop</feats>
          <deprel>DOBJ</deprel>
          <childnodes>
            <LM order="5">
              <form>,</form>
              <lemma>$,</lemma>
              <cpostag>&lt;komma&gt;</cpostag>
              <postag>&lt;komma&gt;</postag>
              <deprel>IK</deprel>
            </LM>
            <LM order="6">
              <form>frå</form>
              <lemma>frå</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="9">
                <form>Haugtussa</form>
                <lemma>Haugtussa</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>prop</feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="7">
                    <form>Arne</form>
                    <lemma>Arne</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>mask</LM>
                      <LM>prop</LM>
                    </feats>
                    <deprel>DET</deprel>
                    <childnodes order="8">
                      <form>Garborgs</form>
                      <lemma>Garborg</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>prop</LM>
                        <LM>gen</LM>
                      </feats>
                      <deprel>FLAT</deprel>
                    </childnodes>
                  </LM>
                  <LM order="10">
                    <form>,</form>
                    <lemma>$,</lemma>
                    <cpostag>&lt;komma&gt;</cpostag>
                    <postag>&lt;komma&gt;</postag>
                    <deprel>IK</deprel>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="13">
          <form>Dei</form>
          <lemma>Dei</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>prop</feats>
          <deprel>KOORD-ELL</deprel>
          <childnodes>
            <LM order="11">
              <form>og</form>
              <lemma>og</lemma>
              <cpostag>konj</cpostag>
              <postag>konj</postag>
              <feats>&lt;ikkje-clb></feats>
              <deprel>KONJ</deprel>
            </LM>
            <LM order="12">
              <form>så</form>
              <lemma>så</lemma>
              <cpostag>adv</cpostag>
              <postag>adv</postag>
              <deprel>ADV</deprel>
            </LM>
            <LM order="14">
              <form>frealause</form>
              <lemma>frealaus</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>pos</LM>
                <LM>fl</LM>
                <LM>samset</LM>
              </feats>
              <deprel>FLAT</deprel>
            </LM>
            <LM order="15">
              <form>menn</form>
              <lemma>mann</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>ub</LM>
                <LM>fl</LM>
              </feats>
              <deprel>FLAT</deprel>
            </LM>
            <LM order="16">
              <form>etter</form>
              <lemma>etter</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="17">
                <form>Svein</form>
                <lemma>Svein</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>prop</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="18">
                    <form>Tveiten</form>
                    <lemma>Tveiten</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>prop</LM>
                                          </feats>
                    <deprel>FLAT</deprel>
                  </LM>
                  <LM order="19">
                    <form>/</form>
                    <lemma>$/</lemma>
                    <cpostag>symb</cpostag>
                    <postag>symb</postag>
                    <deprel>IK</deprel>
                  </LM>
                  <LM order="20">
                    <form>Hovden</form>
                    <lemma>Hovden</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>prop</feats>
                    <deprel>KOORD</deprel>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="21">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>gjorde</form>
      <lemma>gjere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pret</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Det</form>
          <lemma>det</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
          </feats>
          <deprel>DOBJ</deprel>
        </LM>
        <LM order="3">
          <form>ho</form>
          <lemma>ho</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>fem</LM>
            <LM>eint</LM>
            <LM>nom</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="4">
          <form>med</form>
          <lemma>med</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
          <childnodes order="7">
            <form>overtyding</form>
            <lemma>overtyding</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>fem</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
            </feats>
            <deprel>PUTFYLL</deprel>
            <childnodes>
              <LM order="5">
                <form>ei</form>
                <lemma>ein</lemma>
                <cpostag>det</cpostag>
                <postag>det</postag>
                <feats>
                  <LM>kvant</LM>
                  <LM>fem</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>DET</deprel>
              </LM>
              <LM order="6">
                <form>slik</form>
                <lemma>slik</lemma>
                <cpostag>det</cpostag>
                <postag>det</postag>
                <feats>
                  <LM>dem</LM>
                  <LM>fem</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>DET</deprel>
                <childnodes order="10">
                  <form>gav</form>
                  <lemma>gje</lemma>
                  <cpostag>verb</cpostag>
                  <postag>verb</postag>
                  <feats>pret</feats>
                  <deprel>ADV</deprel>
                  <childnodes>
                    <LM order="8">
                      <form>at</form>
                      <lemma>at</lemma>
                      <cpostag>sbu</cpostag>
                      <postag>sbu</postag>
                      <deprel>SBU</deprel>
                    </LM>
                    <LM order="9">
                      <form>domarane</form>
                      <lemma>domar</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>mask</LM>
                        <LM>appell</LM>
                        <LM>fl</LM>
                        <LM>bu</LM>
                      </feats>
                      <deprel>SUBJ</deprel>
                    </LM>
                    <LM order="11">
                      <form>henne</form>
                      <lemma>ho</lemma>
                      <cpostag>pron</cpostag>
                      <postag>pron</postag>
                      <feats>
                        <LM>pers</LM>
                        <LM>3</LM>
                        <LM>fem</LM>
                        <LM>eint</LM>
                        <LM>akk</LM>
                      </feats>
                      <deprel>IOBJ</deprel>
                    </LM>
                    <LM order="13">
                      <form>poeng</form>
                      <lemma>poeng</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>nøyt</LM>
                        <LM>appell</LM>
                        <LM>ub</LM>
                        <LM>fl</LM>
                      </feats>
                      <deprel>DOBJ</deprel>
                      <childnodes order="12">
                        <form>115</form>
                        <lemma>115</lemma>
                        <cpostag>det</cpostag>
                        <postag>det</postag>
                        <feats>
                          <LM>kvant</LM>
                          <LM>fl</LM>
                        </feats>
                        <deprel>DET</deprel>
                      </childnodes>
                    </LM>
                    <LM order="15">
                      <form>kåra</form>
                      <lemma>kåre</lemma>
                      <cpostag>verb</cpostag>
                      <postag>verb</postag>
                      <feats>pret</feats>
                      <deprel>KOORD</deprel>
                      <childnodes>
                        <LM order="14">
                          <form>og</form>
                          <lemma>og</lemma>
                          <cpostag>konj</cpostag>
                          <postag>konj</postag>
                          <feats>clb</feats>
                          <deprel>KONJ</deprel>
                        </LM>
                        <LM order="16">
                          <form>ho</form>
                          <lemma>ho</lemma>
                          <cpostag>pron</cpostag>
                          <postag>pron</postag>
                          <feats>
                            <LM>pers</LM>
                            <LM>3</LM>
                            <LM>fem</LM>
                            <LM>eint</LM>
                            <LM>akk</LM>
                          </feats>
                          <deprel>DOBJ</deprel>
                        </LM>
                        <LM order="17">
                          <form>til</form>
                          <lemma>til</lemma>
                          <cpostag>prep</cpostag>
                          <postag>prep</postag>
                          <deprel>OPRED</deprel>
                          <childnodes order="18">
                            <form>vinnar</form>
                            <lemma>vinnar</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>mask</LM>
                              <LM>appell</LM>
                              <LM>ub</LM>
                              <LM>eint</LM>
                            </feats>
                            <deprel>PUTFYLL</deprel>
                            <childnodes order="19">
                              <form>av</form>
                              <lemma>av</lemma>
                              <cpostag>prep</cpostag>
                              <postag>prep</postag>
                              <deprel>ATR</deprel>
                              <childnodes order="21">
                                <form>klasse</form>
                                <lemma>klasse</lemma>
                                <cpostag>subst</cpostag>
                                <postag>subst</postag>
                                <feats>
                                  <LM>mask</LM>
                                  <LM>appell</LM>
                                  <LM>ub</LM>
                                  <LM>eint</LM>
                                </feats>
                                <deprel>PUTFYLL</deprel>
                                <childnodes order="20">
                                  <form>yngste</form>
                                  <lemma>ung</lemma>
                                  <cpostag>adj</cpostag>
                                  <postag>adj</postag>
                                  <feats>
                                    <LM>sup</LM>
                                    <LM>bu</LM>
                                  </feats>
                                  <deprel>ATR</deprel>
                                </childnodes>
                              </childnodes>
                            </childnodes>
                          </childnodes>
                        </LM>
                      </childnodes>
                    </LM>
                  </childnodes>
                </childnodes>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="22">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="6">
      <form>var</form>
      <lemma>vere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pret</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="3">
          <form>utøvarar</form>
          <lemma>utøvar</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>fl</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes>
            <LM order="1">
              <form>Fleire</form>
              <lemma>mange</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>komp</feats>
              <deprel>ATR</deprel>
            </LM>
            <LM order="2">
              <form>unge</form>
              <lemma>ung</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>pos</LM>
                <LM>fl</LM>
              </feats>
              <deprel>ATR</deprel>
            </LM>
            <LM order="4">
              <form>frå</form>
              <lemma>frå</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ATR</deprel>
              <childnodes order="5">
                <form>vestfylket</form>
                <lemma>vestfylke</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>nøyt</LM>
                  <LM>appell</LM>
                  <LM>eint</LM>
                  <LM>bu</LM>
                  <LM>samset</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="7">
          <form>frampå</form>
          <lemma>frampå</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>SPRED</deprel>
        </LM>
        <LM order="8">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="5">
      <form>spela</form>
      <lemma>spele</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pret</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="2">
          <form>Tone</form>
          <lemma>Tone</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>fem</LM>
            <LM>prop</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes>
            <LM order="1">
              <form>Syster</form>
              <lemma>syster</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>fem</LM>
                <LM>appell</LM>
                <LM>ub</LM>
                <LM>eint</LM>
              </feats>
              <deprel>APP</deprel>
            </LM>
            <LM order="3">
              <form>Harman</form>
              <lemma>Harman</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>prop</feats>
              <deprel>FLAT</deprel>
            </LM>
            <LM order="4">
              <form>Bratland</form>
              <lemma>Bratland</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>prop</feats>
              <deprel>FLAT</deprel>
            </LM>
          </childnodes>
        </LM>
        <LM order="7">
          <form>seljefløyte</form>
          <lemma>seljefløyte</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>DOBJ</deprel>
          <childnodes>
            <LM order="6">
              <form>både</form>
              <lemma>både</lemma>
              <cpostag>konj</cpostag>
              <postag>konj</postag>
              <feats>
                <LM>&lt;ikkje-clb></LM>
                <LM>&lt;adv></LM>
              </feats>
              <deprel>KONJ</deprel>
            </LM>
            <LM order="9">
              <form>blekkfløyte</form>
              <lemma>blekkfløyte</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>fem</LM>
                <LM>appell</LM>
                <LM>ub</LM>
                <LM>eint</LM>
                <LM>samset</LM>
              </feats>
              <deprel>KOORD</deprel>
              <childnodes order="8">
                <form>og</form>
                <lemma>og</lemma>
                <cpostag>konj</cpostag>
                <postag>konj</postag>
                <feats>&lt;ikkje-clb></feats>
                <deprel>KONJ</deprel>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="10">
          <form>,</form>
          <lemma>$,</lemma>
          <cpostag>&lt;komma&gt;</cpostag>
          <postag>&lt;komma&gt;</postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="19">
          <form>spela</form>
          <lemma>spele</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>pret</feats>
          <deprel>ADV</deprel>
          <childnodes>
            <LM order="11">
              <form>medan</form>
              <lemma>medan</lemma>
              <cpostag>sbu</cpostag>
              <postag>sbu</postag>
              <deprel>SBU</deprel>
            </LM>
            <LM order="13">
              <form>Bjønn</form>
              <lemma>Bjønn</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>prop</feats>
              <deprel>SUBJ</deprel>
              <childnodes>
                <LM order="12">
                  <form>flatdølane</form>
                  <lemma>flatdøl</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>mask</LM>
                    <LM>appell</LM>
                    <LM>fl</LM>
                    <LM>bu</LM>
                    <LM>samset</LM>
                  </feats>
                  <deprel>APP</deprel>
                </LM>
                <LM order="14">
                  <form>Raftevold</form>
                  <lemma>Raftevold</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>prop</feats>
                  <deprel>FLAT</deprel>
                </LM>
                <LM order="15">
                  <form>Rue</form>
                  <lemma>Rue</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>prop</feats>
                  <deprel>FLAT</deprel>
                </LM>
                <LM order="17">
                  <form>Anette</form>
                  <lemma>Anette</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>prop</feats>
                  <deprel>KOORD</deprel>
                  <childnodes>
                    <LM order="16">
                      <form>og</form>
                      <lemma>og</lemma>
                      <cpostag>konj</cpostag>
                      <postag>konj</postag>
                      <feats>&lt;ikkje-clb></feats>
                      <deprel>KONJ</deprel>
                    </LM>
                    <LM order="18">
                      <form>Skårnes</form>
                      <lemma>Skårnes</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>prop</feats>
                      <deprel>FLAT</deprel>
                    </LM>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
            <LM order="20">
              <form>seg</form>
              <lemma>seg</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>eint</LM>
                <LM>akk</LM>
              </feats>
              <deprel>DOBJ</deprel>
            </LM>
            <LM order="21">
              <form>til</form>
              <lemma>til</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>OPRED</deprel>
              <childnodes order="23">
                <form>fjerdeplass</form>
                <lemma>fjerdeplass</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                  <LM>samset</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="22">
                    <form>ein</form>
                    <lemma>ein</lemma>
                    <cpostag>det</cpostag>
                    <postag>det</postag>
                    <feats>
                      <LM>kvant</LM>
                      <LM>mask</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>DET</deprel>
                  </LM>
                  <LM order="24">
                    <form>i</form>
                    <lemma>i</lemma>
                    <cpostag>prep</cpostag>
                    <postag>prep</postag>
                    <deprel>ATR</deprel>
                    <childnodes order="25">
                      <form>gruppespel</form>
                      <lemma>gruppespel</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>nøyt</LM>
                        <LM>appell</LM>
                        <LM>ub</LM>
                        <LM>eint</LM>
                        <LM>samset</LM>
                      </feats>
                      <deprel>PUTFYLL</deprel>
                      <childnodes order="26">
                        <form>hardingfele</form>
                        <lemma>hardingfele</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>
                          <LM>fem</LM>
                          <LM>appell</LM>
                          <LM>ub</LM>
                          <LM>eint</LM>
                        </feats>
                        <deprel>ATR</deprel>
                      </childnodes>
                    </childnodes>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="27">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>er</form>
      <lemma>vere</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Rekruttering</form>
          <lemma>rekruttering</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>fem</LM>
            <LM>appell</LM>
            <LM>ub</LM>
            <LM>eint</LM>
          </feats>
          <deprel>PSUBJ</deprel>
        </LM>
        <LM order="3">
          <form>det</form>
          <lemma>det</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>pers</LM>
            <LM>3</LM>
            <LM>nøyt</LM>
            <LM>eint</LM>
          </feats>
          <deprel>FSUBJ</deprel>
        </LM>
        <LM order="4">
          <form>også</form>
          <lemma>også</lemma>
          <cpostag>adv</cpostag>
          <postag>adv</postag>
          <deprel>ADV</deprel>
        </LM>
        <LM order="5">
          <form>i</form>
          <lemma>i</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
          <childnodes order="6">
            <form>lausdansen</form>
            <lemma>lausdans</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>eint</LM>
              <LM>bu</LM>
            </feats>
            <deprel>PUTFYLL</deprel>
          </childnodes>
        </LM>
        <LM order="7">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="5">
      <form>dansa</form>
      <lemma>danse</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pret</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="2">
          <form>Karl</form>
          <lemma>Karl</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>mask</LM>
            <LM>prop</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes>
            <LM order="1">
              <form>Vinbyggjen</form>
              <lemma>vinbyggje</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>mask</LM>
                <LM>appell</LM>
                <LM>eint</LM>
                <LM>bu</LM>
                <LM>samset</LM>
              </feats>
              <deprel>APP</deprel>
            </LM>
            <LM order="3">
              <form>Halvor</form>
              <lemma>Halvor</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>mask</LM>
                <LM>prop</LM>
              </feats>
              <deprel>FLAT</deprel>
            </LM>
            <LM order="4">
              <form>Taraldlien</form>
              <lemma>Taraldlien</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>prop</feats>
              <deprel>FLAT</deprel>
            </LM>
          </childnodes>
        </LM>
        <LM order="6">
          <form>seg</form>
          <lemma>seg</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>eint</LM>
            <LM>akk</LM>
          </feats>
          <deprel>DOBJ</deprel>
        </LM>
        <LM order="7">
          <form>til</form>
          <lemma>til</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>OPRED</deprel>
          <childnodes order="9">
            <form>niandeplass</form>
            <lemma>niandeplass</lemma>
            <cpostag>subst</cpostag>
            <postag>subst</postag>
            <feats>
              <LM>mask</LM>
              <LM>appell</LM>
              <LM>ub</LM>
              <LM>eint</LM>
            </feats>
            <deprel>PUTFYLL</deprel>
            <childnodes order="8">
              <form>ein</form>
              <lemma>ein</lemma>
              <cpostag>det</cpostag>
              <postag>det</postag>
              <feats>
                <LM>kvant</LM>
                <LM>mask</LM>
                <LM>eint</LM>
              </feats>
              <deprel>DET</deprel>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="10">
          <form>,</form>
          <lemma>$,</lemma>
          <cpostag>&lt;komma&gt;</cpostag>
          <postag>&lt;komma&gt;</postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="15">
          <form>dansa</form>
          <lemma>danse</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>pret</feats>
          <deprel>KOORD</deprel>
          <childnodes>
            <LM order="11">
              <form>og</form>
              <lemma>og</lemma>
              <cpostag>konj</cpostag>
              <postag>konj</postag>
              <feats>clb</feats>
              <deprel>KONJ</deprel>
            </LM>
            <LM order="12">
              <form>med</form>
              <lemma>med</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="14">
                <form>springar</form>
                <lemma>springar</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes order="13">
                  <form>ein</form>
                  <lemma>ein</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>kvant</LM>
                    <LM>mask</LM>
                    <LM>eint</LM>
                  </feats>
                  <deprel>DET</deprel>
                </childnodes>
              </childnodes>
            </LM>
            <LM order="16">
              <form>Mari</form>
              <lemma>Mari</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>fem</LM>
                <LM>prop</LM>
              </feats>
              <deprel>SUBJ</deprel>
              <childnodes>
                <LM order="17">
                  <form>Moen</form>
                  <lemma>Moen</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>prop</feats>
                  <deprel>FLAT</deprel>
                </LM>
                <LM order="19">
                  <form>Bjønn</form>
                  <lemma>Bjønn</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>prop</feats>
                  <deprel>KOORD</deprel>
                  <childnodes>
                    <LM order="18">
                      <form>og</form>
                      <lemma>og</lemma>
                      <cpostag>konj</cpostag>
                      <postag>konj</postag>
                      <feats>&lt;ikkje-clb></feats>
                      <deprel>KONJ</deprel>
                    </LM>
                    <LM order="20">
                      <form>Raftevold</form>
                      <lemma>Raftevold</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>prop</feats>
                      <deprel>FLAT</deprel>
                    </LM>
                    <LM order="21">
                      <form>Rue</form>
                      <lemma>Rue</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>prop</feats>
                      <deprel>FLAT</deprel>
                    </LM>
                    <LM order="22">
                      <form>frå</form>
                      <lemma>frå</lemma>
                      <cpostag>prep</cpostag>
                      <postag>prep</postag>
                      <deprel>ATR</deprel>
                      <childnodes order="23">
                        <form>Seljord</form>
                        <lemma>Seljord</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>prop</feats>
                        <deprel>PUTFYLL</deprel>
                        <childnodes order="24">
                          <form>spelemannslag</form>
                          <lemma>spelemannslag</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>nøyt</LM>
                            <LM>appell</LM>
                            <LM>ub</LM>
                            <LM>eint</LM>
                          </feats>
                          <deprel>FLAT</deprel>
                        </childnodes>
                      </childnodes>
                    </LM>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
            <LM order="25">
              <form>seg</form>
              <lemma>seg</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>eint</LM>
                <LM>akk</LM>
              </feats>
              <deprel>DOBJ</deprel>
            </LM>
            <LM order="26">
              <form>til</form>
              <lemma>til</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>OPRED</deprel>
              <childnodes order="28">
                <form>tiandeplass</form>
                <lemma>tiandeplass</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>mask</LM>
                  <LM>appell</LM>
                  <LM>ub</LM>
                  <LM>eint</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="27">
                    <form>ein</form>
                    <lemma>ein</lemma>
                    <cpostag>det</cpostag>
                    <postag>det</postag>
                    <feats>
                      <LM>kvant</LM>
                      <LM>mask</LM>
                      <LM>eint</LM>
                    </feats>
                    <deprel>DET</deprel>
                  </LM>
                  <LM order="29">
                    <form>i</form>
                    <lemma>i</lemma>
                    <cpostag>prep</cpostag>
                    <postag>prep</postag>
                    <deprel>ATR</deprel>
                    <childnodes order="31">
                      <form>danseklassa</form>
                      <lemma>danseklasse</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>fem</LM>
                        <LM>appell</LM>
                        <LM>eint</LM>
                        <LM>bu</LM>
                        <LM>samset</LM>
                      </feats>
                      <deprel>PUTFYLL</deprel>
                      <childnodes order="30">
                        <form>yngste</form>
                        <lemma>ung</lemma>
                        <cpostag>adj</cpostag>
                        <postag>adj</postag>
                        <feats>
                          <LM>sup</LM>
                          <LM>bu</LM>
                        </feats>
                        <deprel>ATR</deprel>
                      </childnodes>
                    </childnodes>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="32">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
  </body>
</conll>
