<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="1">
   <form>Web-TV</form>
   <lemma>web-TV</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>appell</LM>
    <LM>mask</LM>
    <LM>ub</LM>
    <LM>ent</LM>
    <LM>samset</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Se</form>
   <lemma>se</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>imp</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="3">
     <form>hør</form>
     <lemma>høre</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>imp</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="2">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="6">
       <form>kunstgress-angrep</form>
       <lemma>kunstgress-angrep</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
        <LM>samset</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="4">
         <form>Erik</form>
         <lemma>Erik</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
          <LM>mask</LM>
         </feats>
         <deprel>DET</deprel>
         <childnodes>
          <LM order="5">
           <form>Hamréns</form>
           <lemma>Hamrén</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
            <LM>gen</LM>
           </feats>
           <deprel>FLAT</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="2">
     <form>Nordlys</form>
     <lemma>Nordlys</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="1">
       <form>Avisen</form>
       <lemma>avis</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>APP</deprel>
      </LM>
      <LM order="3">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="4">
         <form>Tromsø</form>
         <lemma>Tromsø</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>snakket</form>
     <lemma>snakke</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="7">
       <form>med</form>
       <lemma>med</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="9">
         <form>rekke</form>
         <lemma>rekke</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="8">
           <form>en</form>
           <lemma>en</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>mask</LM>
            <LM>ent</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="10">
           <form>av</form>
           <lemma>av</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="11">
             <form>Tromsø-spillerne</form>
             <lemma>Tromsø-spiller</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>be</LM>
              <LM>fl</LM>
              <LM>samset</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="15">
     <form>hadde</form>
     <lemma>ha</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="13">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="14">
       <form>de</form>
       <lemma>de</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>fl</LM>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="16">
       <form>følgende</form>
       <lemma>følgende</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="17">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="18">
           <form>si</form>
           <lemma>si</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="19">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Tommy</form>
   <lemma>Tommy</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>prop</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>Knarvik</form>
     <lemma>Knarvik</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>FLAT</deprel>
    </LM>
    <LM order="3">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Kunstgresset</form>
     <lemma>kunstgress</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>noe</form>
     <lemma>noe</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="6">
       <form>snakker</form>
       <lemma>snakke</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="5">
         <form>vi</form>
         <lemma>vi</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>fl</LM>
          <LM>pers</LM>
          <LM>hum</LM>
          <LM>nom</LM>
          <LM>1</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="7">
         <form>med</form>
         <lemma>med</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="8">
           <form>hverandre</form>
           <lemma>hverandre</lemma>
           <cpostag>pron</cpostag>
           <postag>pron</postag>
           <feats>
            <LM>fl</LM>
            <LM>hum</LM>
            <LM>res</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="9">
         <form>om</form>
         <lemma>om</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="11">
     <form>ja</form>
     <lemma>ja</lemma>
     <cpostag>interj</cpostag>
     <postag>interj</postag>
     <deprel>INTERJ</deprel>
    </LM>
    <LM order="12">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>kan</form>
   <lemma>kunne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Vi</form>
     <lemma>vi</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>fl</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>skyve</form>
     <lemma>skyve</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="3">
       <form>ikke</form>
       <lemma>ikke</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="5">
       <form>under</form>
       <lemma>under</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="6">
         <form>teppet</form>
         <lemma>teppe</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="9">
       <form>er</form>
       <lemma>være</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="7">
         <form>at</form>
         <lemma>at</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="8">
         <form>forskjellen</form>
         <lemma>forskjell</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="10">
         <form>stor</form>
         <lemma>stor</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>ub</LM>
          <LM>m/f</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>SPRED</deprel>
        </LM>
        <LM order="11">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="12">
           <form>underlaget</form>
           <lemma>underlag</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>be</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="13">
             <form>på</form>
             <lemma>på</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="14">
               <form>Alfheim</form>
               <lemma>Alfheim</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>prop</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
            <LM order="15">
             <form>sammenlignet</form>
             <lemma>sammenligne</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>perf-part</LM>
             </feats>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="16">
               <form>med</form>
               <lemma>med</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="19">
                 <form>Drammen</form>
                 <lemma>Drammen</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>prop</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="17">
                   <form>for</form>
                   <lemma>for</lemma>
                   <cpostag>prep</cpostag>
                   <postag>prep</postag>
                   
                   <deprel>ATR</deprel>
                   <childnodes>
                    <LM order="18">
                     <form>eksempel</form>
                     <lemma>eksempel</lemma>
                     <cpostag>subst</cpostag>
                     <postag>subst</postag>
                     <feats>
                      <LM>appell</LM>
                      <LM>nøyt</LM>
                      <LM>ub</LM>
                      <LM>ent</LM>
                     </feats>
                     <deprel>PUTFYLL</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                  <LM order="20">
                   <form>,</form>
                   <lemma>$,</lemma>
                   <cpostag>&lt;komma&gt;</cpostag>
                   <postag>&lt;komma&gt;</postag>
                   <deprel>IK</deprel>
                  </LM>
                  <LM order="23">
                   <form>var</form>
                   <lemma>være</lemma>
                   <cpostag>verb</cpostag>
                   <postag>verb</postag>
                   <feats>
                    <LM>pret</LM>
                   </feats>
                   <deprel>ATR</deprel>
                   <childnodes>
                    <LM order="21">
                     <form>der</form>
                     <lemma>der</lemma>
                     <cpostag>sbu</cpostag>
                     <postag>sbu</postag>
                     <deprel>SBU</deprel>
                    </LM>
                    <LM order="22">
                     <form>vi</form>
                     <lemma>vi</lemma>
                     <cpostag>pron</cpostag>
                     <postag>pron</postag>
                     <feats>
                      <LM>fl</LM>
                      <LM>pers</LM>
                      <LM>hum</LM>
                      <LM>nom</LM>
                      <LM>1</LM>
                     </feats>
                     <deprel>SUBJ</deprel>
                    </LM>
                    <LM order="25">
                     <form>helg</form>
                     <lemma>helg</lemma>
                     <cpostag>subst</cpostag>
                     <postag>subst</postag>
                     <feats>
                      <LM>appell</LM>
                      <LM>mask</LM>
                      <LM>ub</LM>
                      <LM>ent</LM>
                     </feats>
                     <deprel>ADV</deprel>
                     <childnodes>
                      <LM order="24">
                       <form>forrige</form>
                       <lemma>forrige</lemma>
                       <cpostag>det</cpostag>
                       <postag>det</postag>
                       <feats>
                        <LM>dem</LM>
                        <LM>be</LM>
                        <LM>&lt;adj&gt;</LM>
                       </feats>
                       <deprel>DET</deprel>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="26">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Mot</form>
     <lemma>mot</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="2">
       <form>Lillestrøn</form>
       <lemma>Lillestrøn</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="8">
     <form>raskt</form>
     <lemma>rask</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="5">
       <form>for</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="6">
         <form>eksempel</form>
         <lemma>eksempel</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="7">
       <form>unormalt</form>
       <lemma>unormal</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="4">
   <form>sliter</form>
   <lemma>slite</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Og</form>
     <lemma>og</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="3">
       <form>tillegg</form>
       <lemma>tillegg</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>Alfheim-matta</form>
     <lemma>Alfheim-matte</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>fem</LM>
      <LM>be</LM>
      <LM>ent</LM>
      <LM>samset</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="6">
     <form>mye</form>
     <lemma>mye</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="7">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="8">
       <form>kroppen</form>
       <lemma>kropp</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="9">
         <form>til</form>
         <lemma>til</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="10">
           <form>oss</form>
           <lemma>vi</lemma>
           <cpostag>pron</cpostag>
           <postag>pron</postag>
           <feats>
            <LM>fl</LM>
            <LM>pers</LM>
            <LM>hum</LM>
            <LM>akk</LM>
            <LM>1</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="11">
             <form>spillere</form>
             <lemma>spiller</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>fl</LM>
             </feats>
             <deprel>APP</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>etter</form>
     <lemma>etter</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="13">
       <form>trening</form>
       <lemma>trening</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>fem</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="15">
         <form>kamper</form>
         <lemma>kamp</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="14">
           <form>og</form>
           <lemma>og</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikke-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="16">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Tom</form>
   <lemma>Tom</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>prop</LM>
    <LM>mask</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>Høgli</form>
     <lemma>Høgli</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>FLAT</deprel>
    </LM>
    <LM order="3">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Kunstgresset</form>
     <lemma>kunstgress</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="4">
       <form>har</form>
       <lemma>ha</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="3">
         <form>vi</form>
         <lemma>vi</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>fl</LM>
          <LM>pers</LM>
          <LM>hum</LM>
          <LM>nom</LM>
          <LM>1</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>dårligere</form>
     <lemma>dårlig</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>komp</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="7">
       <form>enn</form>
       <lemma>enn</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="8">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="11">
           <form>arenaene</form>
           <lemma>arena</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>be</LM>
            <LM>fl</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="9">
             <form>de</form>
             <lemma>de</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>dem</LM>
              <LM>fl</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="10">
             <form>andre</form>
             <lemma>annen</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>dem</LM>
              <LM>fl</LM>
              <LM>&lt;adj&gt;</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="12">
             <form>i</form>
             <lemma>i</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="13">
               <form>Tippeligaen</form>
               <lemma>Tippeligaen</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>prop</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="4">
   <form>spilte</form>
   <lemma>spille</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>I</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="3">
       <form>runde</form>
       <lemma>runde</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="2">
         <form>forrige</form>
         <lemma>forrige</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>be</LM>
          <LM>&lt;adj&gt;</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>vi</form>
     <lemma>vi</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>fl</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="6">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="7">
       <form>kunstgresset</form>
       <lemma>kunstgress</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="8">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="9">
           <form>Drammen</form>
           <lemma>Drammen</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>spratt</form>
     <lemma>sprette</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="10">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="11">
       <form>der</form>
       <lemma>der</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="13">
       <form>ballen</form>
       <lemma>ball</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="14">
       <form>normalt</form>
       <lemma>normal</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
      <LM order="15">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="17">
       <form>hadde</form>
       <lemma>ha</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pret</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="16">
         <form>den</form>
         <lemma>den</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>mask</LM>
          <LM>fem</LM>
          <LM>ent</LM>
          <LM>pers</LM>
          <LM>3</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="20">
         <form>stuss</form>
         <lemma>stuss</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="18">
           <form>en</form>
           <lemma>en</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>mask</LM>
            <LM>ent</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="19">
           <form>naturlig</form>
           <lemma>naturlig</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>ub</LM>
            <LM>m/f</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="21">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>skyter</form>
   <lemma>skyte</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>På</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="2">
       <form>Alfheim</form>
       <lemma>Alfheim</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>den</form>
     <lemma>den</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>mask</LM>
      <LM>fem</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="6">
     <form>fart</form>
     <lemma>fart</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="5">
       <form>ekstra</form>
       <lemma>ekstra</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>ub</LM>
        <LM>m/f</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="9">
     <form>gjør</form>
     <lemma>gjøre</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="8">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="10">
       <form>det</form>
       <lemma>det</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ent</LM>
        <LM>pers</LM>
        <LM>3</LM>
       </feats>
       <deprel>FOBJ</deprel>
      </LM>
      <LM order="11">
       <form>vanskeligere</form>
       <lemma>vanskelig</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>komp</LM>
       </feats>
       <deprel>OPRED</deprel>
       <childnodes>
        <LM order="12">
         <form>for</form>
         <lemma>for</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="13">
           <form>spillerne</form>
           <lemma>spiller</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>be</LM>
            <LM>fl</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Kunstgress-debatten</form>
   <lemma>kunstgress-debatt</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>appell</LM>
    <LM>mask</LM>
    <LM>be</LM>
    <LM>ent</LM>
    <LM>samset</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>Fjollete</form>
   <lemma>fjollete</lemma>
   <cpostag>adj</cpostag>
   <postag>adj</postag>
   <feats>
    <LM>ub</LM>
    <LM>m/f</LM>
    <LM>ent</LM>
    <LM>pos</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="3">
     <form>av</form>
     <lemma>av</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="4">
       <form>Hamrén</form>
       <lemma>Hamrén</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>CLS</form>
     <lemma>CLS</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>parodi</form>
     <lemma>parodi</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="3">
       <form>en</form>
       <lemma>en</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>mask</LM>
        <LM>ent</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Miika</form>
   <lemma>Miika</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>prop</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>Koppinen</form>
     <lemma>Koppinen</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>FLAT</deprel>
    </LM>
    <LM order="3">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Nå</form>
     <lemma>nå</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="4">
     <form>kunstgress</form>
     <lemma>kunstgress</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>kunstgress</form>
     <lemma>kunstgress</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SPRED</deprel>
    </LM>
    <LM order="6">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="8">
     <form>blir</form>
     <lemma>bli</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="7">
       <form>det</form>
       <lemma>det</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ent</LM>
        <LM>pers</LM>
        <LM>3</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="9">
       <form>aldri</form>
       <lemma>aldri</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="10">
       <form>som</form>
       <lemma>som</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>SPRED</deprel>
       <childnodes>
        <LM order="11">
         <form>naturgress</form>
         <lemma>naturgress</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="12">
       <form>uansett</form>
       <lemma>uansett</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="6">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Men</form>
     <lemma>men</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>etter</form>
     <lemma>etter</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="3">
       <form>kampen</form>
       <lemma>kamp</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="4">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="5">
           <form>Drammen</form>
           <lemma>Drammen</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>jeg</form>
     <lemma>jeg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="9">
     <form>fin</form>
     <lemma>fin</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>ub</LM>
      <LM>m/f</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="8">
       <form>helt</form>
       <lemma>hel</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
      <LM order="10">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="11">
         <form>kroppen</form>
         <lemma>kropp</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>etterpå</form>
     <lemma>etterpå</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="13">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>stod</form>
   <lemma>stå</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Kunstgresset</form>
     <lemma>kunstgress</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="4">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="6">
       <form>måte</form>
       <lemma>måte</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="5">
         <form>en</form>
         <lemma>en</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>mask</LM>
          <LM>ent</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>oppførte</form>
   <lemma>oppføre</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Og</form>
     <lemma>og</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>ballen</form>
     <lemma>ball</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>seg</form>
     <lemma>seg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>akk</LM>
      <LM>refl</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="5">
     <form>også</form>
     <lemma>også</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="7">
     <form>normalt</form>
     <lemma>normal</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="6">
       <form>mer</form>
       <lemma>mye</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>komp</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Rune</form>
   <lemma>Rune</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>prop</LM>
    <LM>mask</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>Lange</form>
     <lemma>Lange</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>FLAT</deprel>
    </LM>
    <LM order="3">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Underlaget</form>
     <lemma>underlag</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>på</form>
       <lemma>på</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="4">
         <form>Alfheim</form>
         <lemma>Alfheim</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>uvant</form>
     <lemma>uvant</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="7">
       <form>for</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="8">
         <form>meg</form>
         <lemma>jeg</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>ent</LM>
          <LM>pers</LM>
          <LM>hum</LM>
          <LM>akk</LM>
          <LM>1</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="15">
     <form>har</form>
     <lemma>ha</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="10">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="16">
       <form>jeg</form>
       <lemma>jeg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>ent</LM>
        <LM>pers</LM>
        <LM>hum</LM>
        <LM>nom</LM>
        <LM>1</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="17">
       <form>trent</form>
       <lemma>trene</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>perf-part</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="11">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="12">
           <form>grunn</form>
           <lemma>grunn</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="13">
             <form>av</form>
             <lemma>av</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="14">
               <form>det</form>
               <lemma>det</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>nøyt</LM>
                <LM>ent</LM>
                <LM>pers</LM>
                <LM>3</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="20">
         <form>fotballtrening</form>
         <lemma>fotballtrening</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>fem</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="19">
           <form>ren</form>
           <lemma>ren</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>ub</LM>
            <LM>m/f</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="18">
             <form>mindre</form>
             <lemma>liten</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>komp</LM>
             </feats>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="24">
               <form>ville</form>
               <lemma>ville</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>pret</LM>
               </feats>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="21">
                 <form>enn</form>
                 <lemma>enn</lemma>
                 <cpostag>sbu</cpostag>
                 <postag>sbu</postag>
                 <deprel>SBU</deprel>
                </LM>
                <LM order="22">
                 <form>jeg</form>
                 <lemma>jeg</lemma>
                 <cpostag>pron</cpostag>
                 <postag>pron</postag>
                 <feats>
                  <LM>ent</LM>
                  <LM>pers</LM>
                  <LM>hum</LM>
                  <LM>nom</LM>
                  <LM>1</LM>
                 </feats>
                 <deprel>SUBJ</deprel>
                </LM>
                <LM order="25">
                 <form>ha</form>
                 <lemma>ha</lemma>
                 <cpostag>verb</cpostag>
                 <postag>verb</postag>
                 <feats>
                  <LM>inf</LM>
                 </feats>
                 <deprel>INFV</deprel>
                 <childnodes>
                  <LM order="26">
                   <form>gjort</form>
                   <lemma>gjøre</lemma>
                   <cpostag>verb</cpostag>
                   <postag>verb</postag>
                   <feats>
                    <LM>perf-part</LM>
                   </feats>
                   <deprel>INFV</deprel>
                   <childnodes>
                    <LM order="23">
                     <form>normalt</form>
                     <lemma>normal</lemma>
                     <cpostag>adj</cpostag>
                     <postag>adj</postag>
                     <feats>
                      <LM>nøyt</LM>
                      <LM>ub</LM>
                      <LM>ent</LM>
                      <LM>pos</LM>
                     </feats>
                     <deprel>ADV</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="27">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Jeg</form>
     <lemma>jeg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>stått</form>
     <lemma>stå</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="4">
       <form>mindre</form>
       <lemma>liten</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>komp</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
      <LM order="5">
       <form>igjen</form>
       <lemma>igjen</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="6">
       <form>etter</form>
       <lemma>etter</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="7">
         <form>treningene</form>
         <lemma>trening</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>fem</LM>
          <LM>be</LM>
          <LM>fl</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
