<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="9">
   <form>må</form>
   <lemma>måtte</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="10">
     <form>man</form>
     <lemma>man</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="11">
     <form>våkne</form>
     <lemma>våkne</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="1">
       <form>I</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="2">
         <form>stedet</form>
         <lemma>sted</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="3">
           <form>for</form>
           <lemma>for</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="4">
             <form>å</form>
             <lemma>å</lemma>
             <cpostag>inf-merke</cpostag>
             <postag>inf-merke</postag>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="5">
               <form>elske</form>
               <lemma>elske</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>inf</LM>
               </feats>
               <deprel>INFV</deprel>
               <childnodes>
                <LM order="6">
                 <form>i</form>
                 <lemma>i</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="7">
                   <form>skjul</form>
                   <lemma>skjul</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="8">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="12">
       <form>opp</form>
       <lemma>opp</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="14">
       <form>akseptere</form>
       <lemma>akseptere</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="13">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>&lt;ikke-clb&gt;</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="15">
         <form>seg</form>
         <lemma>seg</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>akk</LM>
          <LM>refl</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="16">
           <form>selv</form>
           <lemma>selv</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>&lt;adj&gt;</LM>
            <LM>forst</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="17">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="3">
     <form>kanskje</form>
     <lemma>kanskje</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="4">
     <form>derfor</form>
     <lemma>derfor</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="6">
       <form>skaper</form>
       <lemma>skape</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="5">
         <form>homodebatten</form>
         <lemma>homodebatt</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
          <LM>samset</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="9">
         <form>følelser</form>
         <lemma>følelse</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="8">
           <form>sterke</form>
           <lemma>sterk</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>fl</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="7">
             <form>så</form>
             <lemma>så</lemma>
             <cpostag>adv</cpostag>
             <postag>adv</postag>
             <deprel>ADV</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>vekker</form>
   <lemma>vekke</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Homofilidebatten</form>
     <lemma>homofilidebatt</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>følelser</form>
     <lemma>følelse</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>sterke</form>
       <lemma>sterk</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>fl</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="10">
   <form>må</form>
   <lemma>måtte</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Men</form>
     <lemma>men</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="11">
     <form>man</form>
     <lemma>man</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="12">
     <form>våkne</form>
     <lemma>våkne</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="2">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="3">
         <form>stedet</form>
         <lemma>sted</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="4">
           <form>for</form>
           <lemma>for</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="5">
             <form>å</form>
             <lemma>å</lemma>
             <cpostag>inf-merke</cpostag>
             <postag>inf-merke</postag>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="6">
               <form>elske</form>
               <lemma>elske</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>inf</LM>
               </feats>
               <deprel>INFV</deprel>
               <childnodes>
                <LM order="7">
                 <form>i</form>
                 <lemma>i</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="8">
                   <form>skjul</form>
                   <lemma>skjul</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="9">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="13">
       <form>opp</form>
       <lemma>opp</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="15">
       <form>akseptere</form>
       <lemma>akseptere</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="14">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>&lt;ikke-clb&gt;</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="16">
         <form>seg</form>
         <lemma>seg</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>akk</LM>
          <LM>refl</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="17">
           <form>selv</form>
           <lemma>selv</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>&lt;adj&gt;</LM>
            <LM>forst</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Situasjonen</form>
     <lemma>situasjon</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>uoversiktlig</form>
     <lemma>uoversiktlig</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>ub</LM>
      <LM>m/f</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>SPRED</deprel>
    </LM>
    <LM order="5">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Sammenstøt</form>
   <lemma>sammenstøt</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>appell</LM>
    <LM>nøyt</LM>
    <LM>ub</LM>
    <LM>ent</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="2">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>skal</form>
   <lemma>skulle</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="2">
     <form>nordmenn</form>
     <lemma>nordmann</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="1">
       <form>Ingen</form>
       <lemma>ingen</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>fl</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>befinne</form>
     <lemma>befinne</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="5">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="8">
         <form>områdene</form>
         <lemma>område</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>be</LM>
          <LM>fl</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="6">
           <form>de</form>
           <lemma>de</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>fl</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="7">
           <form>urolige</form>
           <lemma>urolig</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>fl</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>protesterer</form>
   <lemma>protestere</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Demonstranter</form>
     <lemma>demonstrant</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>mot</form>
     <lemma>mot</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="4">
       <form>militærkuppet</form>
       <lemma>militærkupp</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>foran</form>
     <lemma>foran</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="6">
       <form>presidentboligen</form>
       <lemma>presidentbolig</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="7">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="10">
           <form>Tegucigalpa</form>
           <lemma>Tegucigalpa</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="9">
             <form>hovedstad</form>
             <lemma>hovedstad</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>APP</deprel>
             <childnodes>
              <LM order="8">
               <form>Honduras'</form>
               <lemma>Honduras</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>prop</LM>
                <LM>gen</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>søndag</form>
     <lemma>søndag</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="12">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>tar</form>
   <lemma>ta</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Norge</form>
     <lemma>Norge</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>avstand</form>
     <lemma>avstand</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="4">
       <form>fra</form>
       <lemma>fra</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="7">
         <form>maktovertakelsen</form>
         <lemma>maktovertakelse</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="5">
           <form>den</form>
           <lemma>den</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>mask</LM>
            <LM>ent</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="6">
           <form>militære</form>
           <lemma>militær</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>be</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
          <LM order="8">
           <form>i</form>
           <lemma>i</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="9">
             <form>Honduras</form>
             <lemma>Honduras</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="11">
     <form>melder</form>
     <lemma>melde</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="12">
       <form>UD</form>
       <lemma>UD</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>tar</form>
   <lemma>ta</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Fra</form>
     <lemma>fra</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="4">
       <form>side</form>
       <lemma>side</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>fem</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="3">
         <form>norsk</form>
         <lemma>norsk</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>ub</LM>
          <LM>m/f</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>vi</form>
     <lemma>vi</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>fl</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="7">
     <form>avstand</form>
     <lemma>avstand</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="8">
       <form>fra</form>
       <lemma>fra</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="10">
         <form>maktovertakelse</form>
         <lemma>maktovertakelse</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="9">
           <form>militær</form>
           <lemma>militær</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>ub</LM>
            <LM>m/f</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="14">
     <form>oppfordrer</form>
     <lemma>oppfordre</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="12">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="13">
       <form>vi</form>
       <lemma>vi</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>fl</LM>
        <LM>pers</LM>
        <LM>hum</LM>
        <LM>nom</LM>
        <LM>1</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="15">
       <form>sterkt</form>
       <lemma>sterk</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
      <LM order="16">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="22">
         <form>gjeninnsettes</form>
         <lemma>gjeninnsette</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>pres</LM>
          <LM>pass</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="17">
           <form>at</form>
           <lemma>at</lemma>
           <cpostag>sbu</cpostag>
           <postag>sbu</postag>
           <deprel>SBU</deprel>
          </LM>
          <LM order="20">
           <form>myndigheter</form>
           <lemma>myndighet</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>fem</LM>
            <LM>ub</LM>
            <LM>fl</LM>
           </feats>
           <deprel>SUBJ</deprel>
           <childnodes>
            <LM order="18">
             <form>lovlig</form>
             <lemma>lovlig</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>nøyt</LM>
              <LM>ub</LM>
              <LM>ent</LM>
              <LM>pos</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
            <LM order="19">
             <form>valgte</form>
             <lemma>velge</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>fl</LM>
              <LM>&lt;perf-part&gt;</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="21">
           <form>snarest</form>
           <lemma>snar</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>ub</LM>
            <LM>sup</LM>
           </feats>
           <deprel>ADV</deprel>
          </LM>
          <LM order="23">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="28">
           <form>følges</form>
           <lemma>følge</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pres</LM>
            <LM>pass</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="24">
             <form>og</form>
             <lemma>og</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>&lt;ikke-clb&gt;</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
            <LM order="25">
             <form>at</form>
             <lemma>at</lemma>
             <cpostag>sbu</cpostag>
             <postag>sbu</postag>
             <deprel>SBU</deprel>
            </LM>
            <LM order="27">
             <form>prinsipper</form>
             <lemma>prinsipp</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>nøyt</LM>
              <LM>ub</LM>
              <LM>fl</LM>
             </feats>
             <deprel>SUBJ</deprel>
             <childnodes>
              <LM order="26">
               <form>demokratiske</form>
               <lemma>demokratisk</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>fl</LM>
                <LM>pos</LM>
               </feats>
               <deprel>ATR</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="29">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="30">
     <form>sier</form>
     <lemma>si</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="32">
       <form>Marte</form>
       <lemma>Marte</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="31">
         <form>kommunikasjonsrådgiver</form>
         <lemma>kommunikasjonsrådgiver</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
          <LM>samset</LM>
         </feats>
         <deprel>APP</deprel>
         <childnodes>
          <LM order="35">
           <form>i</form>
           <lemma>i</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="36">
             <form>Utenriksdepartementet</form>
             <lemma>Utenriksdepartementet</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="33">
         <form>Lerberg</form>
         <lemma>Lerberg</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
        <LM order="34">
         <form>Koppstad</form>
         <lemma>Koppstad</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="37">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="38">
         <form>NTB</form>
         <lemma>NTB</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="39">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="10">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Ambassaden</form>
     <lemma>ambassade</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="2">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="3">
         <form>Guatemala</form>
         <lemma>Guatemala</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="4">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="7">
       <form>dekker</form>
       <lemma>dekke</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="5">
         <form>som</form>
         <lemma>som</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="6">
         <form>også</form>
         <lemma>også</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="8">
         <form>Honduras</form>
         <lemma>Honduras</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>DOBJ</deprel>
        </LM>
        <LM order="9">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>for</form>
     <lemma>for</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="12">
       <form>øyeblikket</form>
       <lemma>øyeblikk</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="15">
     <form>nordmenn</form>
     <lemma>nordmann</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="13">
       <form>ingen</form>
       <lemma>ingen</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>fl</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="14">
       <form>registrerte</form>
       <lemma>registrere</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>fl</LM>
        <LM>&lt;perf-part&gt;</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
      <LM order="16">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="19">
         <form>Tegucigalpa</form>
         <lemma>Tegucigalpa</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="18">
           <form>hovedstad</form>
           <lemma>hovedstad</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>APP</deprel>
           <childnodes>
            <LM order="17">
             <form>Honduras'</form>
             <lemma>Honduras</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
              <LM>gen</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="20">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="13">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Men</form>
     <lemma>men</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>konsulatet</form>
     <lemma>konsulat</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="9">
         <form>San</form>
         <lemma>San</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="7">
           <form>by</form>
           <lemma>by</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>APP</deprel>
           <childnodes>
            <LM order="4">
             <form>landets</form>
             <lemma>land</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>nøyt</LM>
              <LM>be</LM>
              <LM>ent</LM>
              <LM>gen</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="6">
             <form>største</form>
             <lemma>stor</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>be</LM>
              <LM>sup</LM>
             </feats>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="5">
               <form>nest</form>
               <lemma>nest</lemma>
               <cpostag>adv</cpostag>
               <postag>adv</postag>
               <deprel>ADV</deprel>
              </LM>
             </childnodes>
            </LM>
            <LM order="8">
             <form>,</form>
             <lemma>$,</lemma>
             <cpostag>&lt;komma&gt;</cpostag>
             <postag>&lt;komma&gt;</postag>
             <deprel>IK</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="10">
           <form>Pedro</form>
           <lemma>Pedro</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
            <LM>mask</LM>
           </feats>
           <deprel>FLAT</deprel>
          </LM>
          <LM order="11">
           <form>Sula</form>
           <lemma>Sula</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>FLAT</deprel>
          </LM>
          <LM order="12">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>registert</form>
     <lemma>registrere</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
      <LM>unorm</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="18">
       <form>nordmenn</form>
       <lemma>nordmann</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="17">
         <form>åtte</form>
         <lemma>åtte</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
         <childnodes>
          <LM order="15">
           <form>i</form>
           <lemma>i</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="16">
             <form>alt</form>
             <lemma>alt</lemma>
             <cpostag>pron</cpostag>
             <postag>pron</postag>
             <feats>
              <LM>nøyt</LM>
              <LM>ent</LM>
              <LM>pers</LM>
              <LM>3</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="19">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="20">
           <form>landet</form>
           <lemma>land</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>be</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="21">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Vi</form>
     <lemma>vi</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>fl</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>fulgt</form>
     <lemma>følge</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="5">
       <form>situasjonen</form>
       <lemma>situasjon</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
      <LM order="6">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="8">
         <form>periode</form>
         <lemma>periode</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="7">
           <form>en</form>
           <lemma>en</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>mask</LM>
            <LM>ent</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="9">
       <form>allerede</form>
       <lemma>allerede</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="17">
     <form>holder</form>
     <lemma>holde</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="11">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="15">
       <form>har</form>
       <lemma>ha</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="12">
         <form>når</form>
         <lemma>når</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="13">
         <form>den</form>
         <lemma>den</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>mask</LM>
          <LM>fem</LM>
          <LM>ent</LM>
          <LM>pers</LM>
          <LM>3</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="16">
         <form>eskalert</form>
         <lemma>eskalere</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>perf-part</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="14">
           <form>nå</form>
           <lemma>nå</lemma>
           <cpostag>adv</cpostag>
           <postag>adv</postag>
           <deprel>ADV</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="18">
       <form>vi</form>
       <lemma>vi</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>fl</LM>
        <LM>pers</LM>
        <LM>hum</LM>
        <LM>nom</LM>
        <LM>1</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="21">
       <form>dialog</form>
       <lemma>dialog</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="19">
         <form>en</form>
         <lemma>en</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>mask</LM>
          <LM>ent</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="20">
         <form>fortløpende</form>
         <lemma>fortløpende</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>ub</LM>
          <LM>m/f</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
        <LM order="22">
         <form>med</form>
         <lemma>med</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="24">
           <form>kontakter</form>
           <lemma>kontakt</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>fl</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="23">
             <form>våre</form>
             <lemma>vår</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>fl</LM>
              <LM>poss</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="25">
             <form>i</form>
             <lemma>i</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="26">
               <form>landet</form>
               <lemma>land</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>nøyt</LM>
                <LM>be</LM>
                <LM>ent</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
            <LM order="28">
             <form>UD</form>
             <lemma>UD</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>KOORD</deprel>
             <childnodes>
              <LM order="27">
               <form>og</form>
               <lemma>og</lemma>
               <cpostag>konj</cpostag>
               <postag>konj</postag>
               <feats>
                <LM>&lt;ikke-clb&gt;</LM>
               </feats>
               <deprel>KONJ</deprel>
              </LM>
              <LM order="29">
               <form>hjemme</form>
               <lemma>hjemme</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="30">
                 <form>i</form>
                 <lemma>i</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="31">
                   <form>Norge</form>
                   <lemma>Norge</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>prop</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="32">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="33">
     <form>sier</form>
     <lemma>si</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="35">
       <form>Idar</form>
       <lemma>Idar</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="34">
         <form>ambassadesekretær</form>
         <lemma>ambassadesekretær</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>APP</deprel>
        </LM>
        <LM order="36">
         <form>Instefjord</form>
         <lemma>Instefjord</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="37">
       <form>til</form>
       <lemma>til</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="38">
         <form>Aftenposten.no</form>
         <lemma>Aftenposten.no</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="39">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>ble</form>
   <lemma>bli</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Militærkuppet</form>
     <lemma>militærkupp</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>igangsatt</form>
     <lemma>igangsette</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="4">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="5">
         <form>forbindelse</form>
         <lemma>forbindelse</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="6">
           <form>med</form>
           <lemma>med</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="10">
             <form>skulle</form>
             <lemma>skulle</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pret</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="7">
               <form>at</form>
               <lemma>at</lemma>
               <cpostag>sbu</cpostag>
               <postag>sbu</postag>
               <deprel>SBU</deprel>
              </LM>
              <LM order="9">
               <form>folkeavstemning</form>
               <lemma>folkeavstemning</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>ub</LM>
                <LM>ent</LM>
               </feats>
               <deprel>SUBJ</deprel>
               <childnodes>
                <LM order="8">
                 <form>en</form>
                 <lemma>en</lemma>
                 <cpostag>det</cpostag>
                 <postag>det</postag>
                 <feats>
                  <LM>mask</LM>
                  <LM>ent</LM>
                  <LM>kvant</LM>
                 </feats>
                 <deprel>DET</deprel>
                </LM>
               </childnodes>
              </LM>
              <LM order="11">
               <form>holdes</form>
               <lemma>holde</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>inf</LM>
                <LM>pass</LM>
               </feats>
               <deprel>INFV</deprel>
               <childnodes>
                <LM order="12">
                 <form>søndag</form>
                 <lemma>søndag</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>appell</LM>
                  <LM>mask</LM>
                  <LM>ub</LM>
                  <LM>ent</LM>
                 </feats>
                 <deprel>ADV</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Ifølge</form>
     <lemma>ifølge</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="2">
       <form>Instefjord</form>
       <lemma>Instefjord</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>stemmegivningen</form>
     <lemma>stemmegivning</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>allerede</form>
     <lemma>allerede</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="6">
     <form>igang</form>
     <lemma>igang</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>SPRED</deprel>
    </LM>
    <LM order="7">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="12">
     <form>var</form>
     <lemma>være</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="8">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="9">
       <form>stemmelokaler</form>
       <lemma>stemmelokale</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="11">
         <form>urner</form>
         <lemma>urne</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>fem</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="10">
           <form>og</form>
           <lemma>og</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikke-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="13">
       <form>blitt</form>
       <lemma>bli</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>perf-part</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="14">
         <form>installert</form>
         <lemma>installere</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>perf-part</LM>
         </feats>
         <deprel>INFV</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="15">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>endret</form>
   <lemma>endre</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Så</form>
     <lemma>så</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="3">
     <form>situasjonen</form>
     <lemma>situasjon</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>seg</form>
     <lemma>seg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>akk</LM>
      <LM>refl</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="6">
     <form>brått</form>
     <lemma>brå</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="5">
       <form>ganske</form>
       <lemma>ganske</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>ble</form>
     <lemma>bli</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="7">
       <form>da</form>
       <lemma>da</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="8">
       <form>presidenten</form>
       <lemma>president</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="11">
       <form>pågrepet</form>
       <lemma>pågripe</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>perf-part</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="9">
         <form>plutselig</form>
         <lemma>plutselig</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ADV</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="6">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="3">
     <form>kontakter</form>
     <lemma>kontakt</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="2">
       <form>Våre</form>
       <lemma>vår</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>fl</LM>
        <LM>poss</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="4">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="5">
         <form>landet</form>
         <lemma>land</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>betegnet</form>
     <lemma>betegne</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="9">
       <form>hele</form>
       <lemma>hel</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>be</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="8">
         <form>det</form>
         <lemma>det</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>nøyt</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="10">
       <form>som</form>
       <lemma>som</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>OPRED</deprel>
       <childnodes>
        <LM order="11">
         <form>uoversiktlig</form>
         <lemma>uoversiktlig</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="3">
     <form>vært</form>
     <lemma>være</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="7">
       <form>demonstrasjoner</form>
       <lemma>demonstrasjon</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>PSUBJ</deprel>
       <childnodes>
        <LM order="6">
         <form>del</form>
         <lemma>del</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DET</deprel>
         <childnodes>
          <LM order="4">
           <form>en</form>
           <lemma>en</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>mask</LM>
            <LM>ent</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="5">
           <form>god</form>
           <lemma>god</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>ub</LM>
            <LM>m/f</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="10">
         <form>sammenstøt</form>
         <lemma>sammenstøt</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="8">
           <form>og</form>
           <lemma>og</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikke-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
          <LM order="9">
           <form>enkelte</form>
           <lemma>enkelt</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>fl</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
          <LM order="11">
           <form>med</form>
           <lemma>med</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="12">
             <form>militæret</form>
             <lemma>militær</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>nøyt</LM>
              <LM>be</LM>
              <LM>ent</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="14">
     <form>sier</form>
     <lemma>si</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="15">
       <form>Instefjord</form>
       <lemma>Instefjord</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="16">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
