<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="2">
   <form>kan</form>
   <lemma>kunne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="3">
     <form>være</form>
     <lemma>være</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="6">
       <form>idé</form>
       <lemma>idé</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>SPRED</deprel>
       <childnodes>
        <LM order="4">
         <form>en</form>
         <lemma>en</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>mask</LM>
          <LM>ent</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="5">
         <form>god</form>
         <lemma>god</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>ub</LM>
          <LM>m/f</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="7">
       <form>å</form>
       <lemma>å</lemma>
       <cpostag>inf-merke</cpostag>
       <postag>inf-merke</postag>
       <deprel>PSUBJ</deprel>
       <childnodes>
        <LM order="8">
         <form>snakke</form>
         <lemma>snakke</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>inf</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="9">
           <form>med</form>
           <lemma>med</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="11">
             <form>A</form>
             <lemma>A</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="10">
               <form>både</form>
               <lemma>både</lemma>
               <cpostag>konj</cpostag>
               <postag>konj</postag>
               <feats>
                <LM>&lt;ikke-clb&gt;</LM>
                <LM>&lt;adv&gt;</LM>
               </feats>
               <deprel>KONJ</deprel>
              </LM>
              <LM order="13">
               <form>B</form>
               <lemma>B</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>prop</LM>
               </feats>
               <deprel>KOORD</deprel>
               <childnodes>
                <LM order="12">
                 <form>og</form>
                 <lemma>og</lemma>
                 <cpostag>konj</cpostag>
                 <postag>konj</postag>
                 <feats>
                  <LM>&lt;ikke-clb&gt;</LM>
                 </feats>
                 <deprel>KONJ</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>kan</form>
   <lemma>kunne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Jeg</form>
     <lemma>jeg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>formidle</form>
     <lemma>formidle</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="3">
       <form>gjerne</form>
       <lemma>gjerne</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="5">
       <form>kontakt</form>
       <lemma>kontakt</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
