<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="2">
   <form>må</form>
   <lemma>måtte</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Bjørnstad</form>
     <lemma>Bjørnstad</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="6">
     <form>spille</form>
     <lemma>spille</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="5">
       <form>sesong</form>
       <lemma>sesong</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="3">
         <form>nok</form>
         <lemma>nok</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ATR</deprel>
        </LM>
        <LM order="4">
         <form>en</form>
         <lemma>en</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>mask</LM>
          <LM>ent</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="7">
       <form>på</form>
       <lemma>på</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="9">
         <form>B-tour</form>
         <lemma>B-tour</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>unorm</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="8">
           <form>PGAs</form>
           <lemma>PGA</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
            <LM>gen</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>åpnet</form>
   <lemma>åpne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>mask</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>3</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>finalerunden</form>
     <lemma>finalerunde</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
      <LM>samset</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="3">
       <form>den</form>
       <lemma>den</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>dem</LM>
        <LM>mask</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="4">
       <form>viktige</form>
       <lemma>viktig</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>be</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>mandag</form>
     <lemma>mandag</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="7">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="10">
       <form>måte</form>
       <lemma>måte</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="8">
         <form>en</form>
         <lemma>en</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>mask</LM>
          <LM>ent</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="9">
         <form>dårlig</form>
         <lemma>dårlig</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>ub</LM>
          <LM>m/f</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="7">
   <form>satte</form>
   <lemma>sette</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="2">
     <form>bogey</form>
     <lemma>bogey</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="1">
       <form>En</form>
       <lemma>en</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>mask</LM>
        <LM>ent</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="3">
       <form>på</form>
       <lemma>på</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="6">
         <form>hull</form>
         <lemma>hull</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="4">
           <form>det</form>
           <lemma>det</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>nøyt</LM>
            <LM>ent</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="5">
           <form>første</form>
           <lemma>første</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>be</LM>
            <LM>ent</LM>
            <LM>pos</LM>
            <LM>&lt;ordenstall&gt;</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>dessverre</form>
     <lemma>dessverre</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="9">
     <form>standarden</form>
     <lemma>standard</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="10">
     <form>for</form>
     <lemma>for</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="11">
       <form>runden</form>
       <lemma>runde</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>klarte</form>
   <lemma>klare</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>mask</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>3</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>aldri</form>
     <lemma>aldri</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="4">
     <form>å</form>
     <lemma>å</lemma>
     <cpostag>inf-merke</cpostag>
     <postag>inf-merke</postag>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="5">
       <form>komme</form>
       <lemma>komme</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="6">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="7">
           <form>offensiven</form>
           <lemma>offensiv</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>be</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>slet</form>
     <lemma>slite</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="8">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="10">
       <form>med</form>
       <lemma>med</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="11">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="12">
           <form>klare</form>
           <lemma>klare</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="13">
             <form>par</form>
             <lemma>par</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
             </feats>
             <deprel>DOBJ</deprel>
            </LM>
            <LM order="14">
             <form>på</form>
             <lemma>på</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="15">
               <form>hullene</form>
               <lemma>hull</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>nøyt</LM>
                <LM>be</LM>
                <LM>fl</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="16">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="9">
   <form>gikk</form>
   <lemma>gå</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>På</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="4">
       <form>banen</form>
       <lemma>bane</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="2">
         <form>den</form>
         <lemma>den</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>mask</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="3">
         <form>samme</form>
         <lemma>samme</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>be</LM>
          <LM>&lt;adj&gt;</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="5">
         <form>for</form>
         <lemma>for</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="7">
           <form>dager</form>
           <lemma>dag</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>fl</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="6">
             <form>to</form>
             <lemma>to</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>fl</LM>
              <LM>kvant</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="8">
             <form>siden</form>
             <lemma>siden</lemma>
             <cpostag>adv</cpostag>
             <postag>adv</postag>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>mask</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>3</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="11">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="13">
       <form>slag</form>
       <lemma>slag</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="12">
         <form>66</form>
         <lemma>66</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>ble</form>
   <lemma>bli</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Når</form>
     <lemma>nå</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <feats>
      <LM>unorm</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="3">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="4">
     <form>bare</form>
     <lemma>bare</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="5">
     <form>72</form>
     <lemma>72</lemma>
     <cpostag>det</cpostag>
     <postag>det</postag>
     <feats>
      <LM>fl</LM>
      <LM>kvant</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="7">
       <form>par</form>
       <lemma>par</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="6">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>&lt;ikke-clb&gt;</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="8">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="9">
           <form>runden</form>
           <lemma>runde</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>be</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>mask</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>3</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>tilbake</form>
     <lemma>tilbake</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="4">
       <form>på</form>
       <lemma>på</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="5">
         <form>par</form>
         <lemma>par</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>med</form>
     <lemma>med</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="8">
       <form>birdie</form>
       <lemma>birdie</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="7">
         <form>en</form>
         <lemma>en</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>mask</LM>
          <LM>ent</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="9">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="10">
           <form>hull</form>
           <lemma>hull</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="11">
             <form>fire</form>
             <lemma>fire</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>fl</LM>
              <LM>kvant</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="17">
     <form>måtte</form>
     <lemma>måtte</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="13">
       <form>mens</form>
       <lemma>mens</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="18">
       <form>han</form>
       <lemma>han</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>mask</LM>
        <LM>ent</LM>
        <LM>pers</LM>
        <LM>hum</LM>
        <LM>3</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="19">
       <form>tåle</form>
       <lemma>tåle</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="14">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="15">
           <form>hull</form>
           <lemma>hull</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="16">
             <form>seks</form>
             <lemma>seks</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>fl</LM>
              <LM>kvant</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="22">
         <form>bogey</form>
         <lemma>bogey</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="20">
           <form>en</form>
           <lemma>en</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>mask</LM>
            <LM>ent</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="21">
           <form>ny</form>
           <lemma>ny</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>ub</LM>
            <LM>m/f</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="23">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="4">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Etter</form>
     <lemma>etter</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="2">
       <form>hull</form>
       <lemma>hull</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="3">
         <form>elleve</form>
         <lemma>elleve</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>mask</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>3</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="6">
     <form>igjen</form>
     <lemma>igjen</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="7">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="8">
       <form>par</form>
       <lemma>par</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>etter</form>
     <lemma>etter</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="12">
       <form>birdie</form>
       <lemma>birdie</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="10">
         <form>dagens</form>
         <lemma>dag</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
          <LM>gen</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="11">
         <form>annen</form>
         <lemma>annen</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
          <LM>&lt;adj&gt;</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="16">
     <form>var</form>
     <lemma>være</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="14">
       <form>men</form>
       <lemma>men</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="17">
       <form>det</form>
       <lemma>det</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ent</LM>
        <LM>pers</LM>
        <LM>3</LM>
       </feats>
       <deprel>FSUBJ</deprel>
      </LM>
      <LM order="18">
       <form>blitt</form>
       <lemma>bli</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>perf-part</LM>
       </feats>
       <deprel>INFV</deprel>
       <childnodes>
        <LM order="15">
         <form>dessverre</form>
         <lemma>dessverre</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="21">
         <form>fram</form>
         <lemma>fram</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>SPRED</deprel>
         <childnodes>
          <LM order="20">
           <form>langt</form>
           <lemma>lang</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="19">
             <form>for</form>
             <lemma>for</lemma>
             <cpostag>adv</cpostag>
             <postag>adv</postag>
             <deprel>ADV</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="22">
           <form>til</form>
           <lemma>til</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="23">
             <form>25.-plassen</form>
             <lemma>25.-plass</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>be</LM>
              <LM>ent</LM>
              <LM>samset</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="24">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
        <LM order="28">
         <form>hull</form>
         <lemma>hull</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>KOORD-ELL</deprel>
         <childnodes>
          <LM order="25">
           <form>og</form>
           <lemma>og</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikke-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
          <LM order="27">
           <form>få</form>
           <lemma>få</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>fl</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="26">
             <form>for</form>
             <lemma>for</lemma>
             <cpostag>adv</cpostag>
             <postag>adv</postag>
             <deprel>ADV</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="29">
           <form>igjen</form>
           <lemma>igjen</lemma>
           <cpostag>adv</cpostag>
           <postag>adv</postag>
           <deprel>ADV</deprel>
          </LM>
          <LM order="30">
           <form>å</form>
           <lemma>å</lemma>
           <cpostag>inf-merke</cpostag>
           <postag>inf-merke</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="31">
             <form>spille</form>
             <lemma>spille</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>inf</LM>
             </feats>
             <deprel>INFV</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="32">
           <form>for</form>
           <lemma>for</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="33">
             <form>nordmannen</form>
             <lemma>nordmann</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>be</LM>
              <LM>ent</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="34">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
