<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="4">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Stavanger</form>
     <lemma>Stavanger</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="2">
       <form>på</form>
       <lemma>på</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="3">
         <form>femteplass</form>
         <lemma>femteplass</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>fortsatt</form>
     <lemma>fortsatt</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="8">
     <form>hjemmestatistikk</form>
     <lemma>hjemmestatistikk</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="6">
       <form>en</form>
       <lemma>en</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>mask</LM>
        <LM>ent</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="7">
       <form>knallsterk</form>
       <lemma>knallsterk</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>ub</LM>
        <LM>m/f</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="12">
     <form>fikk</form>
     <lemma>få</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="10">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="11">
       <form>søndag</form>
       <lemma>søndag</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
      <LM order="13">
       <form>de</form>
       <lemma>de</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>fl</LM>
        <LM>pers</LM>
        <LM>3</LM>
        <LM>nom</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="16">
       <form>poeng</form>
       <lemma>poeng</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="14">
         <form>nye</form>
         <lemma>ny</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>fl</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
        <LM order="15">
         <form>fortjente</form>
         <lemma>fortjent</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>fl</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="17">
       <form>etter</form>
       <lemma>etter</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="18">
         <form>4</form>
         <lemma>4</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
          
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="19">
           <form>-</form>
           <lemma>$-</lemma>
           <cpostag>&lt;strek&gt;</cpostag>
           <postag>&lt;strek&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="20">
           <form>3</form>
           <lemma>3</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>fl</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>KOORD</deprel>
          </LM>
          <LM order="21">
           <form>mot</form>
           <lemma>mot</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="22">
             <form>Lillehammer</form>
             <lemma>Lillehammer</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="23">
           <form>i</form>
           <lemma>i</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="24">
             <form>Siddishallen</form>
             <lemma>Siddishallen</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="25">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Stjernen</form>
     <lemma>stjerne</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>kommet</form>
     <lemma>komme</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="4">
       <form>tilbake</form>
       <lemma>tilbake</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="5">
       <form>etter</form>
       <lemma>etter</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="8">
         <form>uker</form>
         <lemma>uke</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>fem</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="6">
           <form>noen</form>
           <lemma>noen</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>fl</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="7">
           <form>trøblete</form>
           <lemma>trøblet</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>fl</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>vant</form>
     <lemma>vinne</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="9">
       <form>og</form>
       <lemma>og</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="11">
       <form>bortemøtet</form>
       <lemma>bortemøte</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
        <LM>samset</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="12">
         <form>mot</form>
         <lemma>mot</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="13">
           <form>Storhamar</form>
           <lemma>Storhamar</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="14">
       <form>med</form>
       <lemma>med</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="15">
         <form>5</form>
         <lemma>5</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
          
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="16">
           <form>-</form>
           <lemma>$-</lemma>
           <cpostag>&lt;strek&gt;</cpostag>
           <postag>&lt;strek&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="17">
           <form>2</form>
           <lemma>2</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>fl</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>KOORD</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="7">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>I</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="2">
       <form>bunnoppgjøret</form>
       <lemma>bunnoppgjør</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="3">
         <form>mellom</form>
         <lemma>mellom</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="4">
           <form>Comet</form>
           <lemma>Comet</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="6">
             <form>Furuset</form>
             <lemma>Furuset</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>KOORD</deprel>
             <childnodes>
              <LM order="5">
               <form>og</form>
               <lemma>og</lemma>
               <cpostag>konj</cpostag>
               <postag>konj</postag>
               <feats>
                <LM>&lt;ikke-clb&gt;</LM>
               </feats>
               <deprel>KONJ</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="9">
     <form>til</form>
     <lemma>til</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="10">
       <form>slutt</form>
       <lemma>slutt</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>Marius</form>
     <lemma>Marius</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
      <LM>mask</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="12">
       <form>Mathisrud</form>
       <lemma>Mathisrud</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="14">
       <form>slo</form>
       <lemma>slå</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pret</LM>
       </feats>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="13">
         <form>som</form>
         <lemma>som</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="15">
         <form>inn</form>
         <lemma>inn</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
        </LM>
        <LM order="18">
         <form>straffen</form>
         <lemma>straffe</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="16">
           <form>den</form>
           <lemma>den</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>mask</LM>
            <LM>ent</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="17">
           <form>avgjørende</form>
           <lemma>avgjørende</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>be</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="19">
         <form>etter</form>
         <lemma>etter</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="23">
           <form>ga</form>
           <lemma>gi</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pret</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="20">
             <form>at</form>
             <lemma>at</lemma>
             <cpostag>sbu</cpostag>
             <postag>sbu</postag>
             <deprel>SBU</deprel>
            </LM>
            <LM order="21">
             <form>forlengningen</form>
             <lemma>forlengning</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>be</LM>
              <LM>ent</LM>
             </feats>
             <deprel>SUBJ</deprel>
            </LM>
            <LM order="22">
             <form>ikke</form>
             <lemma>ikke</lemma>
             <cpostag>adv</cpostag>
             <postag>adv</postag>
             <deprel>ADV</deprel>
            </LM>
            <LM order="25">
             <form>vinner</form>
             <lemma>vinner</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>DOBJ</deprel>
             <childnodes>
              <LM order="24">
               <form>noen</form>
               <lemma>noen</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>mask</LM>
                <LM>ent</LM>
                <LM>kvant</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="26">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>sto</form>
   <lemma>stå</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="3">
     <form>5</form>
     <lemma>5</lemma>
     <cpostag>det</cpostag>
     <postag>det</postag>
     <feats>
      <LM>fl</LM>
      <LM>kvant</LM>
      
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="4">
       <form>-</form>
       <lemma>$-</lemma>
       <cpostag>&lt;strek&gt;</cpostag>
       <postag>&lt;strek&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="5">
       <form>5</form>
       <lemma>5</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>fl</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>KOORD</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>etter</form>
     <lemma>etter</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="8">
       <form>perioder</form>
       <lemma>periode</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="7">
         <form>tre</form>
         <lemma>tre</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>raknet</form>
   <lemma>rakne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Norge</form>
     <lemma>Norge</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>mot</form>
     <lemma>mot</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="4">
       <form>Sveits</form>
       <lemma>Sveits</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>|</form>
     <lemma>$|</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;overskrift&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="1">
   <form>Tapte</form>
   <lemma>tape</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="2">
     <form>kamp</form>
     <lemma>kamp</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>to</form>
       <lemma>to</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>fl</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="5">
       <form>VM</form>
       <lemma>VM</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>&lt;romertall&gt;</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>så</form>
   <lemma>se</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Norge</form>
     <lemma>Norge</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>ut</form>
     <lemma>ut</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="4">
     <form>til</form>
     <lemma>til</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="5">
       <form>å</form>
       <lemma>å</lemma>
       <cpostag>inf-merke</cpostag>
       <postag>inf-merke</postag>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="6">
         <form>gjøre</form>
         <lemma>gjøre</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>inf</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="10">
           <form>kamp</form>
           <lemma>kamp</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>DOBJ</deprel>
           <childnodes>
            <LM order="8">
             <form>en</form>
             <lemma>en</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>mask</LM>
              <LM>ent</LM>
              <LM>kvant</LM>
             </feats>
             <deprel>DET</deprel>
             <childnodes>
              <LM order="7">
               <form>nok</form>
               <lemma>nok</lemma>
               <cpostag>adv</cpostag>
               <postag>adv</postag>
               <deprel>ADV</deprel>
              </LM>
             </childnodes>
            </LM>
            <LM order="9">
             <form>god</form>
             <lemma>god</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>ub</LM>
              <LM>m/f</LM>
              <LM>ent</LM>
              <LM>pos</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
            <LM order="11">
             <form>i</form>
             <lemma>i</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="12">
               <form>innebandy-VM</form>
               <lemma>innebandy-VM</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>ent</LM>
                <LM>samset</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
               <childnodes>
                <LM order="13">
                 <form>i</form>
                 <lemma>i</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ATR</deprel>
                 <childnodes>
                  <LM order="14">
                   <form>Ostrava</form>
                   <lemma>Ostrava</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>prop</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="15">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="17">
     <form>raknet</form>
     <lemma>rakne</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="16">
       <form>men</form>
       <lemma>men</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="18">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="20">
         <form>periode</form>
         <lemma>periode</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="19">
           <form>siste</form>
           <lemma>sist</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>be</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="22">
       <form>tapte</form>
       <lemma>tape</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pret</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="21">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>clb</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="23">
         <form>6</form>
         <lemma>6</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
          
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="24">
           <form>-</form>
           <lemma>$-</lemma>
           <cpostag>&lt;strek&gt;</cpostag>
           <postag>&lt;strek&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="25">
           <form>9</form>
           <lemma>9</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>fl</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>KOORD</deprel>
          </LM>
          <LM order="26">
           <form>for</form>
           <lemma>for</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="27">
             <form>Sveits</form>
             <lemma>Sveits</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="28">
         <form>søndag</form>
         <lemma>søndag</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>ADV</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="29">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>spiller</form>
   <lemma>spille</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Vi</form>
     <lemma>vi</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>fl</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>bra</form>
     <lemma>bra</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="4">
       <form>veldig</form>
       <lemma>veldig</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="8">
       <form>perioder</form>
       <lemma>periode</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="7">
         <form>to</form>
         <lemma>to</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="12">
     <form>gjør</form>
     <lemma>gjøre</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>KOORD</deprel>
     <childnodes>
      <LM order="10">
       <form>men</form>
       <lemma>men</lemma>
       <cpostag>konj</cpostag>
       <postag>konj</postag>
       <feats>
        <LM>clb</LM>
       </feats>
       <deprel>KONJ</deprel>
      </LM>
      <LM order="11">
       <form>så</form>
       <lemma>så</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="13">
       <form>vi</form>
       <lemma>vi</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>fl</LM>
        <LM>pers</LM>
        <LM>hum</LM>
        <LM>nom</LM>
        <LM>1</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="17">
       <form>feil</form>
       <lemma>feil</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="15">
         <form>del</form>
         <lemma>del</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DET</deprel>
         <childnodes>
          <LM order="14">
           <form>en</form>
           <lemma>en</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>mask</LM>
            <LM>ent</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="16">
         <form>dumme</form>
         <lemma>dum</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>fl</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="18">
       <form>innimellom</form>
       <lemma>innimellom</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="19">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
        <LM order="21">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>APP</deprel>
         <childnodes>
          <LM order="20">
           <form>spesielt</form>
           <lemma>spesiell</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ADV</deprel>
          </LM>
          <LM order="22">
           <form>starten</form>
           <lemma>start</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>be</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="23">
             <form>av</form>
             <lemma>av</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="25">
               <form>periode</form>
               <lemma>periode</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>ub</LM>
                <LM>ent</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
               <childnodes>
                <LM order="24">
                 <form>tredje</form>
                 <lemma>tredje</lemma>
                 <cpostag>adj</cpostag>
                 <postag>adj</postag>
                 <feats>
                  <LM>be</LM>
                  <LM>ent</LM>
                  <LM>pos</LM>
                  <LM>&lt;ordenstall&gt;</LM>
                 </feats>
                 <deprel>ATR</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="26">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="27">
     <form>sa</form>
     <lemma>si</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="30">
       <form>Ketil</form>
       <lemma>Ketil</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="29">
         <form>stjernespiller</form>
         <lemma>stjernespiller</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>APP</deprel>
         <childnodes>
          <LM order="28">
           <form>Norges</form>
           <lemma>Norge</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
            <LM>gen</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
        <LM order="31">
         <form>Kronberg</form>
         <lemma>Kronberg</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="32">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>ble</form>
   <lemma>bli</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Han</form>
     <lemma>han</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>mask</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>3</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>toppscorer</form>
     <lemma>toppscorer</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="3">
       <form>Norges</form>
       <lemma>Norge</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>gen</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>med</form>
     <lemma>med</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="7">
       <form>mål</form>
       <lemma>mål</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="6">
         <form>to</form>
         <lemma>to</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="13">
   <form>tegnet</form>
   <lemma>tegne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="2">
     <form>Tommy</form>
     <lemma>Tommy</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="1">
       <form>Også</form>
       <lemma>også</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ATR</deprel>
      </LM>
      <LM order="3">
       <form>Midtsveen</form>
       <lemma>Midtsveen</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="4">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="5">
       <form>Willy</form>
       <lemma>Willy</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>mask</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="6">
         <form>Fauskanger</form>
         <lemma>Fauskanger</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
        <LM order="7">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="8">
       <form>Raymond</form>
       <lemma>Raymond</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>mask</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="9">
         <form>Evensen</form>
         <lemma>Evensen</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="11">
       <form>Thomas</form>
       <lemma>Thomas</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>mask</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="10">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>&lt;ikke-clb&gt;</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="12">
         <form>Stræte</form>
         <lemma>Stræte</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>seg</form>
     <lemma>seg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>akk</LM>
      <LM>refl</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="15">
     <form>på</form>
     <lemma>på</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="16">
       <form>scoringslisten</form>
       <lemma>scoringsliste</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="17">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Men</form>
     <lemma>men</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>ikke</form>
     <lemma>ikke</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="5">
     <form>nok</form>
     <lemma>nok</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>SPRED</deprel>
    </LM>
    <LM order="6">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="7">
       <form>møtet</form>
       <lemma>møte</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="8">
         <form>med</form>
         <lemma>med</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="9">
           <form>sveitserne</form>
           <lemma>sveitser</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>be</LM>
            <LM>fl</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="10">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="14">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Etter</form>
     <lemma>etter</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="4">
       <form>perioder</form>
       <lemma>periode</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="2">
         <form>to</form>
         <lemma>to</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="3">
         <form>jevne</form>
         <lemma>jevn</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>fl</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
        <LM order="6">
         <form>2</form>
         <lemma>2</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>fl</LM>
          <LM>kvant</LM>
          
         </feats>
         <deprel>APP</deprel>
         <childnodes>
          <LM order="5">
           <form>(</form>
           <lemma>$(</lemma>
           <cpostag>&lt;parentes-beg&gt;</cpostag>
           <postag>&lt;parentes-beg&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="7">
           <form>-</form>
           <lemma>$-</lemma>
           <cpostag>&lt;strek&gt;</cpostag>
           <postag>&lt;strek&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="8">
           <form>2</form>
           <lemma>2</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>fl</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>KOORD</deprel>
          </LM>
          <LM order="9">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="10">
           <form>3</form>
           <lemma>3</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>fl</LM>
            <LM>kvant</LM>
            
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="11">
             <form>-</form>
             <lemma>$-</lemma>
             <cpostag>&lt;strek&gt;</cpostag>
             <postag>&lt;strek&gt;</postag>
             <deprel>IK</deprel>
            </LM>
            <LM order="12">
             <form>3</form>
             <lemma>3</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>fl</LM>
              <LM>kvant</LM>
             </feats>
             <deprel>KOORD</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="13">
           <form>)</form>
           <lemma>$)</lemma>
           <cpostag>&lt;parentes-slutt&gt;</cpostag>
           <postag>&lt;parentes-slutt&gt;</postag>
           <deprel>IK</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="15">
     <form>Sveits</form>
     <lemma>Sveits</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="17">
     <form>best</form>
     <lemma>god</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>ub</LM>
      <LM>sup</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="16">
       <form>klart</form>
       <lemma>klar</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ADV</deprel>
      </LM>
      <LM order="18">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="19">
         <form>tredjeperioden</form>
         <lemma>tredjeperiode</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
          <LM>samset</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="20">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>vant</form>
   <lemma>vinne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Sveitserne</form>
     <lemma>sveitser</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>fl</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>periode</form>
     <lemma>periode</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>den</form>
       <lemma>den</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>dem</LM>
        <LM>mask</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="4">
       <form>siste</form>
       <lemma>sist</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>be</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>4</form>
     <lemma>4</lemma>
     <cpostag>det</cpostag>
     <postag>det</postag>
     <feats>
      <LM>fl</LM>
      <LM>kvant</LM>
      
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="7">
       <form>-</form>
       <lemma>$-</lemma>
       <cpostag>&lt;strek&gt;</cpostag>
       <postag>&lt;strek&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="8">
       <form>1</form>
       <lemma>1</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>fl</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>KOORD</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>slo</form>
   <lemma>slå</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Lørdag</form>
     <lemma>lørdag</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="3">
     <form>Norge</form>
     <lemma>Norge</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>Danmark</form>
     <lemma>Danmark</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="5">
     <form>7</form>
     <lemma>7</lemma>
     <cpostag>det</cpostag>
     <postag>det</postag>
     <feats>
      <LM>fl</LM>
      <LM>kvant</LM>
      
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="6">
       <form>-</form>
       <lemma>$-</lemma>
       <cpostag>&lt;strek&gt;</cpostag>
       <postag>&lt;strek&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="7">
       <form>3</form>
       <lemma>3</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>fl</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>KOORD</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="11">
       <form>VM-kampen</form>
       <lemma>VM-kamp</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="9">
         <form>den</form>
         <lemma>den</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>mask</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="10">
         <form>første</form>
         <lemma>første</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>be</LM>
          <LM>ent</LM>
          <LM>pos</LM>
          <LM>&lt;ordenstall&gt;</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>venter</form>
   <lemma>vente</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Mandag</form>
     <lemma>mandag</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="3">
     <form>Estland</form>
     <lemma>Estland</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
