<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="2">
   <form>bør</form>
   <lemma>burde</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="3">
     <form>vi</form>
     <lemma>vi</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>fl</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>ha</form>
     <lemma>ha</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="1">
       <form>Derfor</form>
       <lemma>derfor</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="4">
       <form>også</form>
       <lemma>også</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="7">
       <form>regler</form>
       <lemma>regel</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="6">
         <form>konkurransedyktige</form>
         <lemma>konkurransedyktig</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>fl</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="8">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="9">
       <form>for</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="10">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="11">
           <form>kunne</form>
           <lemma>kunne</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="12">
             <form>beholde</form>
             <lemma>beholde</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>inf</LM>
             </feats>
             <deprel>INFV</deprel>
             <childnodes>
              <LM order="14">
               <form>del</form>
               <lemma>del</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>ub</LM>
                <LM>ent</LM>
               </feats>
               <deprel>DOBJ</deprel>
               <childnodes>
                <LM order="13">
                 <form>en</form>
                 <lemma>en</lemma>
                 <cpostag>det</cpostag>
                 <postag>det</postag>
                 <feats>
                  <LM>mask</LM>
                  <LM>ent</LM>
                  <LM>kvant</LM>
                 </feats>
                 <deprel>DET</deprel>
                </LM>
                <LM order="15">
                 <form>av</form>
                 <lemma>av</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ATR</deprel>
                 <childnodes>
                  <LM order="17">
                   <form>hjernene</form>
                   <lemma>hjerne</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>mask</LM>
                    <LM>be</LM>
                    <LM>fl</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                   <childnodes>
                    <LM order="16">
                     <form>disse</form>
                     <lemma>disse</lemma>
                     <cpostag>det</cpostag>
                     <postag>det</postag>
                     <feats>
                      <LM>dem</LM>
                      <LM>fl</LM>
                     </feats>
                     <deprel>DET</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="38">
   <form>vil</form>
   <lemma>ville</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="39">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="41">
     <form>være</form>
     <lemma>være</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="3">
       <form>sier</form>
       <lemma>si</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="1">
         <form>Når</form>
         <lemma>når</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="2">
         <form>finansministeren</form>
         <lemma>finansminister</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="6">
         <form>vil</form>
         <lemma>ville</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>pres</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="4">
           <form>at</form>
           <lemma>at</lemma>
           <cpostag>sbu</cpostag>
           <postag>sbu</postag>
           <deprel>SBU</deprel>
          </LM>
          <LM order="5">
           <form>man</form>
           <lemma>man</lemma>
           <cpostag>pron</cpostag>
           <postag>pron</postag>
           <feats>
            <LM>ent</LM>
            <LM>pers</LM>
            <LM>hum</LM>
            <LM>nom</LM>
           </feats>
           <deprel>SUBJ</deprel>
          </LM>
          <LM order="7">
           <form>fremme</form>
           <lemma>fremme</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="9">
             <form>sak</form>
             <lemma>sak</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>DOBJ</deprel>
             <childnodes>
              <LM order="8">
               <form>en</form>
               <lemma>en</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>mask</LM>
                <LM>ent</LM>
                <LM>kvant</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
              <LM order="10">
               <form>om</form>
               <lemma>om</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="11">
                 <form>endringer</form>
                 <lemma>endring</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>appell</LM>
                  <LM>fem</LM>
                  <LM>ub</LM>
                  <LM>fl</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="12">
                   <form>i</form>
                   <lemma>i</lemma>
                   <cpostag>prep</cpostag>
                   <postag>prep</postag>
                   <deprel>ATR</deprel>
                   <childnodes>
                    <LM order="13">
                     <form>opsjonsbeskatningsreglene</form>
                     <lemma>opsjonsbeskatningsregel</lemma>
                     <cpostag>subst</cpostag>
                     <postag>subst</postag>
                     <feats>
                      <LM>appell</LM>
                      <LM>mask</LM>
                      <LM>be</LM>
                      <LM>fl</LM>
                      <LM>samset</LM>
                     </feats>
                     <deprel>PUTFYLL</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
            <LM order="14">
             <form>til</form>
             <lemma>til</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="15">
               <form>våren</form>
               <lemma>vår</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>be</LM>
                <LM>ent</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
          <LM order="16">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="20">
           <form>holder</form>
           <lemma>holde</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pres</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="17">
             <form>og</form>
             <lemma>og</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>&lt;ikke-clb&gt;</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
            <LM order="18">
             <form>at</form>
             <lemma>at</lemma>
             <cpostag>sbu</cpostag>
             <postag>sbu</postag>
             <deprel>SBU</deprel>
            </LM>
            <LM order="19">
             <form>han</form>
             <lemma>han</lemma>
             <cpostag>pron</cpostag>
             <postag>pron</postag>
             <feats>
              <LM>mask</LM>
              <LM>ent</LM>
              <LM>pers</LM>
              <LM>hum</LM>
              <LM>3</LM>
              <LM>nom</LM>
             </feats>
             <deprel>SUBJ</deprel>
            </LM>
            <LM order="21">
             <form>fast</form>
             <lemma>fast</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>nøyt</LM>
              <LM>ub</LM>
              <LM>ent</LM>
              <LM>pos</LM>
             </feats>
             <deprel>ADV</deprel>
            </LM>
            <LM order="22">
             <form>ved</form>
             <lemma>ved</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="23">
               <form>det</form>
               <lemma>det</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>nøyt</LM>
                <LM>ent</LM>
                <LM>pers</LM>
                <LM>3</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
               <childnodes>
                <LM order="25">
                 <form>sa</form>
                 <lemma>si</lemma>
                 <cpostag>verb</cpostag>
                 <postag>verb</postag>
                 <feats>
                  <LM>pret</LM>
                 </feats>
                 <deprel>ATR</deprel>
                 <childnodes>
                  <LM order="24">
                   <form>statsministeren</form>
                   <lemma>statsminister</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>mask</LM>
                    <LM>be</LM>
                    <LM>ent</LM>
                   </feats>
                   <deprel>SUBJ</deprel>
                  </LM>
                 </childnodes>
                </LM>
                <LM order="26">
                 <form>,</form>
                 <lemma>$,</lemma>
                 <cpostag>&lt;komma&gt;</cpostag>
                 <postag>&lt;komma&gt;</postag>
                 <deprel>IK</deprel>
                </LM>
                <LM order="29">
                 <form>skal</form>
                 <lemma>skulle</lemma>
                 <cpostag>verb</cpostag>
                 <postag>verb</postag>
                 <feats>
                  <LM>pres</LM>
                 </feats>
                 <deprel>APP</deprel>
                 <childnodes>
                  <LM order="27">
                   <form>at</form>
                   <lemma>at</lemma>
                   <cpostag>sbu</cpostag>
                   <postag>sbu</postag>
                   <deprel>SBU</deprel>
                  </LM>
                  <LM order="28">
                   <form>vi</form>
                   <lemma>vi</lemma>
                   <cpostag>pron</cpostag>
                   <postag>pron</postag>
                   <feats>
                    <LM>fl</LM>
                    <LM>pers</LM>
                    <LM>hum</LM>
                    <LM>nom</LM>
                    <LM>1</LM>
                   </feats>
                   <deprel>SUBJ</deprel>
                  </LM>
                  <LM order="30">
                   <form>være</form>
                   <lemma>være</lemma>
                   <cpostag>verb</cpostag>
                   <postag>verb</postag>
                   <feats>
                    <LM>inf</LM>
                   </feats>
                   <deprel>INFV</deprel>
                   <childnodes>
                    <LM order="32">
                     <form>på</form>
                     <lemma>på</lemma>
                     <cpostag>prep</cpostag>
                     <postag>prep</postag>
                     <deprel>SPRED</deprel>
                     <childnodes>
                      <LM order="31">
                       <form>mer</form>
                       <lemma>mye</lemma>
                       <cpostag>adj</cpostag>
                       <postag>adj</postag>
                       <feats>
                        <LM>komp</LM>
                       </feats>
                       <deprel>ADV</deprel>
                      </LM>
                      <LM order="33">
                       <form>linje</form>
                       <lemma>linje</lemma>
                       <cpostag>subst</cpostag>
                       <postag>subst</postag>
                       <feats>
                        <LM>appell</LM>
                        <LM>fem</LM>
                        <LM>ub</LM>
                        <LM>ent</LM>
                       </feats>
                       <deprel>PUTFYLL</deprel>
                       <childnodes>
                        <LM order="34">
                         <form>med</form>
                         <lemma>med</lemma>
                         <cpostag>prep</cpostag>
                         <postag>prep</postag>
                         <deprel>ATR</deprel>
                         <childnodes>
                          <LM order="36">
                           <form>land</form>
                           <lemma>land</lemma>
                           <cpostag>subst</cpostag>
                           <postag>subst</postag>
                           <feats>
                            <LM>appell</LM>
                            <LM>nøyt</LM>
                            <LM>ub</LM>
                            <LM>fl</LM>
                           </feats>
                           <deprel>PUTFYLL</deprel>
                           <childnodes>
                            <LM order="35">
                             <form>andre</form>
                             <lemma>annen</lemma>
                             <cpostag>det</cpostag>
                             <postag>det</postag>
                             <feats>
                              <LM>dem</LM>
                              <LM>fl</LM>
                              <LM>&lt;adj&gt;</LM>
                             </feats>
                             <deprel>DET</deprel>
                            </LM>
                           </childnodes>
                          </LM>
                         </childnodes>
                        </LM>
                       </childnodes>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="37">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="40">
       <form>da</form>
       <lemma>da</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="42">
       <form>beskatningen</form>
       <lemma>beskatning</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>SPRED</deprel>
       <childnodes>
        <LM order="43">
         <form>på</form>
         <lemma>på</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="45">
           <form>tidspunktet</form>
           <lemma>tidspunkt</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>be</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="44">
             <form>det</form>
             <lemma>det</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>dem</LM>
              <LM>nøyt</LM>
              <LM>ent</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="49">
             <form>bruker</form>
             <lemma>bruke</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pres</LM>
             </feats>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="46">
               <form>hvor</form>
               <lemma>hvor</lemma>
               <cpostag>adv</cpostag>
               <postag>adv</postag>
               <deprel>ADV</deprel>
              </LM>
              <LM order="47">
               <form>man</form>
               <lemma>man</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>ent</LM>
                <LM>pers</LM>
                <LM>hum</LM>
                <LM>nom</LM>
               </feats>
               <deprel>SUBJ</deprel>
              </LM>
              <LM order="48">
               <form>faktisk</form>
               <lemma>faktisk</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>ent</LM>
                <LM>pos</LM>
               </feats>
               <deprel>ADV</deprel>
              </LM>
              <LM order="50">
               <form>disse</form>
               <lemma>disse</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>fl</LM>
                <LM>pers</LM>
                <LM>3</LM>
               </feats>
               <deprel>DOBJ</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="51">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
        <LM order="53">
         <form>vil</form>
         <lemma>ville</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>pres</LM>
         </feats>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="52">
           <form>som</form>
           <lemma>som</lemma>
           <cpostag>sbu</cpostag>
           <postag>sbu</postag>
           <deprel>SBU</deprel>
          </LM>
          <LM order="54">
           <form>være</form>
           <lemma>være</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="56">
             <form>vurdering</form>
             <lemma>vurdering</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>fem</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>SPRED</deprel>
             <childnodes>
              <LM order="55">
               <form>aktuell</form>
               <lemma>aktuell</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>ub</LM>
                <LM>m/f</LM>
                <LM>ent</LM>
                <LM>pos</LM>
               </feats>
               <deprel>ATR</deprel>
              </LM>
             </childnodes>
            </LM>
            <LM order="57">
             <form>fra</form>
             <lemma>fra</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="59">
               <form>side</form>
               <lemma>side</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>fem</LM>
                <LM>ub</LM>
                <LM>ent</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
               <childnodes>
                <LM order="58">
                 <form>Regjeringens</form>
                 <lemma>Regjeringen</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>prop</LM>
                  <LM>gen</LM>
                 </feats>
                 <deprel>DET</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="60">
     <form>?</form>
     <lemma>$?</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;spm&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>Gudmund</form>
   <lemma>Gudmund</lemma>
   <cpostag>subst</cpostag>
   <postag>subst</postag>
   <feats>
    <LM>prop</LM>
    <LM>mask</LM>
   </feats>
   <deprel>FRAG</deprel>
   <childnodes>
    <LM order="1">
     <form>Statsråd</form>
     <lemma>statsråd</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>APP</deprel>
    </LM>
    <LM order="3">
     <form>Restad</form>
     <lemma>Restad</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>FLAT</deprel>
    </LM>
    <LM order="4">
     <form>:</form>
     <lemma>$:</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;kolon&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Jeg</form>
     <lemma>jeg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>enig</form>
     <lemma>enig</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>ub</LM>
      <LM>m/f</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>SPRED</deprel>
    </LM>
    <LM order="4">
     <form>med</form>
     <lemma>med</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="6">
       <form>Børge</form>
       <lemma>Børge</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>mask</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="5">
         <form>representanten</form>
         <lemma>representant</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>APP</deprel>
        </LM>
        <LM order="7">
         <form>Brende</form>
         <lemma>Brende</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="8">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="11">
       <form>må</form>
       <lemma>måtte</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="9">
         <form>at</form>
         <lemma>at</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="10">
         <form>vi</form>
         <lemma>vi</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>fl</LM>
          <LM>pers</LM>
          <LM>hum</LM>
          <LM>nom</LM>
          <LM>1</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="12">
         <form>sørge</form>
         <lemma>sørge</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>inf</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="13">
           <form>for</form>
           <lemma>for</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="16">
             <form>har</form>
             <lemma>ha</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pres</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="14">
               <form>at</form>
               <lemma>at</lemma>
               <cpostag>sbu</cpostag>
               <postag>sbu</postag>
               <deprel>SBU</deprel>
              </LM>
              <LM order="15">
               <form>vi</form>
               <lemma>vi</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>fl</LM>
                <LM>pers</LM>
                <LM>hum</LM>
                <LM>nom</LM>
                <LM>1</LM>
               </feats>
               <deprel>SUBJ</deprel>
              </LM>
              <LM order="17">
               <form>regler</form>
               <lemma>regel</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>ub</LM>
                <LM>fl</LM>
               </feats>
               <deprel>DOBJ</deprel>
               <childnodes>
                <LM order="27">
                 <form>gjør</form>
                 <lemma>gjøre</lemma>
                 <cpostag>verb</cpostag>
                 <postag>verb</postag>
                 <feats>
                  <LM>pres</LM>
                 </feats>
                 <deprel>ATR</deprel>
                 <childnodes>
                  <LM order="26">
                   <form>som</form>
                   <lemma>som</lemma>
                   <cpostag>sbu</cpostag>
                   <postag>sbu</postag>
                   <deprel>SBU</deprel>
                  </LM>
                  <LM order="30">
                   <form>er</form>
                   <lemma>være</lemma>
                   <cpostag>verb</cpostag>
                   <postag>verb</postag>
                   <feats>
                    <LM>pres</LM>
                   </feats>
                   <deprel>DOBJ</deprel>
                   <childnodes>
                    <LM order="28">
                     <form>at</form>
                     <lemma>at</lemma>
                     <cpostag>sbu</cpostag>
                     <postag>sbu</postag>
                     <deprel>SBU</deprel>
                    </LM>
                    <LM order="29">
                     <form>vi</form>
                     <lemma>vi</lemma>
                     <cpostag>pron</cpostag>
                     <postag>pron</postag>
                     <feats>
                      <LM>fl</LM>
                      <LM>pers</LM>
                      <LM>hum</LM>
                      <LM>nom</LM>
                      <LM>1</LM>
                     </feats>
                     <deprel>SUBJ</deprel>
                    </LM>
                    <LM order="31">
                     <form>konkurransedyktige</form>
                     <lemma>konkurransedyktig</lemma>
                     <cpostag>adj</cpostag>
                     <postag>adj</postag>
                     <feats>
                      <LM>fl</LM>
                      <LM>pos</LM>
                     </feats>
                     <deprel>SPRED</deprel>
                    </LM>
                    <LM order="32">
                     <form>,</form>
                     <lemma>$,</lemma>
                     <cpostag>&lt;komma&gt;</cpostag>
                     <postag>&lt;komma&gt;</postag>
                     <deprel>IK</deprel>
                    </LM>
                    <LM order="37">
                     <form>kan</form>
                     <lemma>kunne</lemma>
                     <cpostag>verb</cpostag>
                     <postag>verb</postag>
                     <feats>
                      <LM>pres</LM>
                     </feats>
                     <deprel>KOORD</deprel>
                     <childnodes>
                      <LM order="33">
                       <form>og</form>
                       <lemma>og</lemma>
                       <cpostag>konj</cpostag>
                       <postag>konj</postag>
                       <feats>
                        <LM>&lt;ikke-clb&gt;</LM>
                       </feats>
                       <deprel>KONJ</deprel>
                      </LM>
                      <LM order="34">
                       <form>at</form>
                       <lemma>at</lemma>
                       <cpostag>sbu</cpostag>
                       <postag>sbu</postag>
                       <deprel>SBU</deprel>
                      </LM>
                      <LM order="36">
                       <form>bedrifter</form>
                       <lemma>bedrift</lemma>
                       <cpostag>subst</cpostag>
                       <postag>subst</postag>
                       <feats>
                        <LM>appell</LM>
                        <LM>mask</LM>
                        <LM>ub</LM>
                        <LM>fl</LM>
                       </feats>
                       <deprel>SUBJ</deprel>
                       <childnodes>
                        <LM order="35">
                         <form>norske</form>
                         <lemma>norsk</lemma>
                         <cpostag>adj</cpostag>
                         <postag>adj</postag>
                         <feats>
                          <LM>fl</LM>
                          <LM>pos</LM>
                         </feats>
                         <deprel>ATR</deprel>
                        </LM>
                       </childnodes>
                      </LM>
                      <LM order="38">
                       <form>tiltrekke</form>
                       <lemma>tiltrekke</lemma>
                       <cpostag>verb</cpostag>
                       <postag>verb</postag>
                       <feats>
                        <LM>inf</LM>
                       </feats>
                       <deprel>INFV</deprel>
                       <childnodes>
                        <LM order="39">
                         <form>seg</form>
                         <lemma>seg</lemma>
                         <cpostag>pron</cpostag>
                         <postag>pron</postag>
                         <feats>
                          <LM>akk</LM>
                          <LM>refl</LM>
                         </feats>
                         <deprel>IOBJ</deprel>
                        </LM>
                        <LM order="40">
                         <form>nøkkelpersonell</form>
                         <lemma>nøkkelpersonell</lemma>
                         <cpostag>subst</cpostag>
                         <postag>subst</postag>
                         <feats>
                          <LM>appell</LM>
                          <LM>nøyt</LM>
                          <LM>ub</LM>
                          <LM>fl</LM>
                         </feats>
                         <deprel>DOBJ</deprel>
                        </LM>
                        <LM order="41">
                         <form>på</form>
                         <lemma>på</lemma>
                         <cpostag>prep</cpostag>
                         <postag>prep</postag>
                         <deprel>ADV</deprel>
                         <childnodes>
                          <LM order="42">
                           <form>linje</form>
                           <lemma>linje</lemma>
                           <cpostag>subst</cpostag>
                           <postag>subst</postag>
                           <feats>
                            <LM>appell</LM>
                            <LM>fem</LM>
                            <LM>ub</LM>
                            <LM>ent</LM>
                           </feats>
                           <deprel>PUTFYLL</deprel>
                           <childnodes>
                            <LM order="43">
                             <form>med</form>
                             <lemma>med</lemma>
                             <cpostag>prep</cpostag>
                             <postag>prep</postag>
                             <deprel>ATR</deprel>
                             <childnodes>
                              <LM order="44">
                               <form>bedrifter</form>
                               <lemma>bedrift</lemma>
                               <cpostag>subst</cpostag>
                               <postag>subst</postag>
                               <feats>
                                <LM>appell</LM>
                                <LM>mask</LM>
                                <LM>ub</LM>
                                <LM>fl</LM>
                               </feats>
                               <deprel>PUTFYLL</deprel>
                               <childnodes>
                                <LM order="45">
                                 <form>i</form>
                                 <lemma>i</lemma>
                                 <cpostag>prep</cpostag>
                                 <postag>prep</postag>
                                 <deprel>ATR</deprel>
                                 <childnodes>
                                  <LM order="46">
                                   <form>utlandet</form>
                                   <lemma>utland</lemma>
                                   <cpostag>subst</cpostag>
                                   <postag>subst</postag>
                                   <feats>
                                    <LM>appell</LM>
                                    <LM>nøyt</LM>
                                    <LM>be</LM>
                                    <LM>ent</LM>
                                   </feats>
                                   <deprel>PUTFYLL</deprel>
                                  </LM>
                                 </childnodes>
                                </LM>
                               </childnodes>
                              </LM>
                             </childnodes>
                            </LM>
                           </childnodes>
                          </LM>
                         </childnodes>
                        </LM>
                       </childnodes>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
              <LM order="18">
               <form>i</form>
               <lemma>i</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="19">
                 <form>Norge</form>
                 <lemma>Norge</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>prop</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                </LM>
               </childnodes>
              </LM>
              <LM order="23">
               <form>gjelder</form>
               <lemma>gjelde</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>pres</LM>
               </feats>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="20">
                 <form>også</form>
                 <lemma>også</lemma>
                 <cpostag>adv</cpostag>
                 <postag>adv</postag>
                 <deprel>ADV</deprel>
                </LM>
                <LM order="21">
                 <form>når</form>
                 <lemma>når</lemma>
                 <cpostag>sbu</cpostag>
                 <postag>sbu</postag>
                 <deprel>SBU</deprel>
                </LM>
                <LM order="22">
                 <form>det</form>
                 <lemma>det</lemma>
                 <cpostag>pron</cpostag>
                 <postag>pron</postag>
                 <feats>
                  <LM>nøyt</LM>
                  <LM>ent</LM>
                  <LM>pers</LM>
                  <LM>3</LM>
                 </feats>
                 <deprel>SUBJ</deprel>
                </LM>
                <LM order="24">
                 <form>opsjonsbeskatning</form>
                 <lemma>opsjonsbeskatning</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>appell</LM>
                  <LM>fem</LM>
                  <LM>ub</LM>
                  <LM>ent</LM>
                 </feats>
                 <deprel>DOBJ</deprel>
                </LM>
                <LM order="25">
                 <form>,</form>
                 <lemma>$,</lemma>
                 <cpostag>&lt;komma&gt;</cpostag>
                 <postag>&lt;komma&gt;</postag>
                 <deprel>IK</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="47">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>klarer</form>
   <lemma>klare</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Ellers</form>
     <lemma>ellers</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="3">
     <form>vi</form>
     <lemma>vi</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>fl</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>ikke</form>
     <lemma>ikke</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="5">
     <form>konkurransen</form>
     <lemma>konkurranse</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
    </LM>
    <LM order="6">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="3">
     <form>også</form>
     <lemma>også</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="4">
     <form>derfor</form>
     <lemma>derfor</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="11">
       <form>har</form>
       <lemma>ha</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="6">
         <form>statsministeren</form>
         <lemma>statsminister</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>SUBJ</deprel>
         <childnodes>
          <LM order="5">
           <form>både</form>
           <lemma>både</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikke-clb&gt;</LM>
            <LM>&lt;adv&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
          <LM order="8">
           <form>undertegnede</form>
           <lemma>undertegne</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>be</LM>
            <LM>ent</LM>
            <LM>&lt;perf-part&gt;</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="7">
             <form>og</form>
             <lemma>og</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>&lt;ikke-clb&gt;</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="12">
         <form>annonsert</form>
         <lemma>annonsere</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>perf-part</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="9">
           <form>i</form>
           <lemma>i</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="10">
             <form>offentlighet</form>
             <lemma>offentlighet</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>fem</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
          <LM order="13">
           <form>i</form>
           <lemma>i</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="14">
             <form>jule-</form>
             <lemma>jule-</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>ufl</feats>
             
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="15">
               <form>/</form>
               <lemma>$/</lemma>
               <cpostag>symb</cpostag>
               <postag>symb</postag>
               <deprel>IK</deprel>
              </LM>
              <LM order="16">
               <form>nyttårstiden</form>
               <lemma>nyttårstid</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>be</LM>
                <LM>ent</LM>
                <LM>samset</LM>
               </feats>
               <deprel>KOORD</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
          <LM order="19">
           <form>vil</form>
           <lemma>ville</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pres</LM>
           </feats>
           <deprel>DOBJ</deprel>
           <childnodes>
            <LM order="17">
             <form>at</form>
             <lemma>at</lemma>
             <cpostag>sbu</cpostag>
             <postag>sbu</postag>
             <deprel>SBU</deprel>
            </LM>
            <LM order="18">
             <form>vi</form>
             <lemma>vi</lemma>
             <cpostag>pron</cpostag>
             <postag>pron</postag>
             <feats>
              <LM>fl</LM>
              <LM>pers</LM>
              <LM>hum</LM>
              <LM>nom</LM>
              <LM>1</LM>
             </feats>
             <deprel>SUBJ</deprel>
            </LM>
            <LM order="20">
             <form>fremme</form>
             <lemma>fremme</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>inf</LM>
             </feats>
             <deprel>INFV</deprel>
             <childnodes>
              <LM order="21">
               <form>forslag</form>
               <lemma>forslag</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>ent</LM>
               </feats>
               <deprel>DOBJ</deprel>
               <childnodes>
                <LM order="22">
                 <form>om</form>
                 <lemma>om</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ATR</deprel>
                 <childnodes>
                  <LM order="24">
                   <form>forbedring</form>
                   <lemma>forbedring</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>fem</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                   <childnodes>
                    <LM order="23">
                     <form>ytterligere</form>
                     <lemma>ytterligere</lemma>
                     <cpostag>adj</cpostag>
                     <postag>adj</postag>
                     <feats>
                      <LM>ub</LM>
                      <LM>m/f</LM>
                      <LM>ent</LM>
                      <LM>pos</LM>
                     </feats>
                     <deprel>ATR</deprel>
                    </LM>
                    <LM order="25">
                     <form>av</form>
                     <lemma>av</lemma>
                     <cpostag>prep</cpostag>
                     <postag>prep</postag>
                     <deprel>ATR</deprel>
                     <childnodes>
                      <LM order="26">
                       <form>opsjonsreglene</form>
                       <lemma>opsjonsregel</lemma>
                       <cpostag>subst</cpostag>
                       <postag>subst</postag>
                       <feats>
                        <LM>appell</LM>
                        <LM>mask</LM>
                        <LM>be</LM>
                        <LM>fl</LM>
                        <LM>samset</LM>
                       </feats>
                       <deprel>PUTFYLL</deprel>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
              <LM order="27">
               <form>,</form>
               <lemma>$,</lemma>
               <cpostag>&lt;komma&gt;</cpostag>
               <postag>&lt;komma&gt;</postag>
               <deprel>IK</deprel>
              </LM>
              <LM order="32">
               <form>er</form>
               <lemma>være</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>pres</LM>
               </feats>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="29">
                 <form>om</form>
                 <lemma>om</lemma>
                 <cpostag>sbu</cpostag>
                 <postag>sbu</postag>
                 <deprel>SBU</deprel>
                 <childnodes>
                  <LM order="28">
                   <form>selv</form>
                   <lemma>selv</lemma>
                   <cpostag>adv</cpostag>
                   <postag>adv</postag>
                   <deprel>ADV</deprel>
                  </LM>
                 </childnodes>
                </LM>
                <LM order="30">
                 <form>det</form>
                 <lemma>det</lemma>
                 <cpostag>pron</cpostag>
                 <postag>pron</postag>
                 <feats>
                  <LM>nøyt</LM>
                  <LM>ent</LM>
                  <LM>pers</LM>
                  <LM>3</LM>
                 </feats>
                 <deprel>FSUBJ</deprel>
                </LM>
                <LM order="31">
                 <form>ikke</form>
                 <lemma>ikke</lemma>
                 <cpostag>adv</cpostag>
                 <postag>adv</postag>
                 <deprel>ADV</deprel>
                </LM>
                <LM order="33">
                 <form>mer</form>
                 <lemma>mye</lemma>
                 <cpostag>adj</cpostag>
                 <postag>adj</postag>
                 <feats>
                  <LM>komp</LM>
                 </feats>
                 <deprel>SPRED</deprel>
                 <childnodes>
                  <LM order="34">
                   <form>enn</form>
                   <lemma>enn</lemma>
                   <cpostag>prep</cpostag>
                   <postag>prep</postag>
                   <deprel>ADV</deprel>
                   <childnodes>
                    <LM order="37">
                     <form>år</form>
                     <lemma>år</lemma>
                     <cpostag>subst</cpostag>
                     <postag>subst</postag>
                     <feats>
                      <LM>appell</LM>
                      <LM>nøyt</LM>
                      <LM>ub</LM>
                      <LM>ent</LM>
                     </feats>
                     <deprel>PUTFYLL</deprel>
                     <childnodes>
                      <LM order="36">
                       <form>ett</form>
                       <lemma>én</lemma>
                       <cpostag>det</cpostag>
                       <postag>det</postag>
                       <feats>
                        <LM>nøyt</LM>
                        <LM>ent</LM>
                        <LM>kvant</LM>
                       </feats>
                       <deprel>DET</deprel>
                       <childnodes>
                        <LM order="35">
                         <form>vel</form>
                         <lemma>vel</lemma>
                         <cpostag>adv</cpostag>
                         <postag>adv</postag>
                         <deprel>ADV</deprel>
                        </LM>
                       </childnodes>
                      </LM>
                      <LM order="40">
                       <form>fikk</form>
                       <lemma>få</lemma>
                       <cpostag>verb</cpostag>
                       <postag>verb</postag>
                       <feats>
                        <LM>pret</LM>
                       </feats>
                       <deprel>ATR</deprel>
                       <childnodes>
                        <LM order="38">
                         <form>siden</form>
                         <lemma>siden</lemma>
                         <cpostag>sbu</cpostag>
                         <postag>sbu</postag>
                         <deprel>SBU</deprel>
                        </LM>
                        <LM order="39">
                         <form>vi</form>
                         <lemma>vi</lemma>
                         <cpostag>pron</cpostag>
                         <postag>pron</postag>
                         <feats>
                          <LM>fl</LM>
                          <LM>pers</LM>
                          <LM>hum</LM>
                          <LM>nom</LM>
                          <LM>1</LM>
                         </feats>
                         <deprel>SUBJ</deprel>
                        </LM>
                        <LM order="43">
                         <form>forbedringene</form>
                         <lemma>forbedring</lemma>
                         <cpostag>subst</cpostag>
                         <postag>subst</postag>
                         <feats>
                          <LM>appell</LM>
                          <LM>fem</LM>
                          <LM>be</LM>
                          <LM>fl</LM>
                         </feats>
                         <deprel>DOBJ</deprel>
                         <childnodes>
                          <LM order="41">
                           <form>de</form>
                           <lemma>de</lemma>
                           <cpostag>det</cpostag>
                           <postag>det</postag>
                           <feats>
                            <LM>dem</LM>
                            <LM>fl</LM>
                           </feats>
                           <deprel>DET</deprel>
                          </LM>
                          <LM order="42">
                           <form>siste</form>
                           <lemma>sist</lemma>
                           <cpostag>adj</cpostag>
                           <postag>adj</postag>
                           <feats>
                            <LM>fl</LM>
                            <LM>pos</LM>
                           </feats>
                           <deprel>ATR</deprel>
                          </LM>
                         </childnodes>
                        </LM>
                       </childnodes>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="44">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="14">
   <form>vil</form>
   <lemma>ville</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="15">
     <form>jeg</form>
     <lemma>jeg</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="17">
     <form>røpe</form>
     <lemma>røpe</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="9">
       <form>skal</form>
       <lemma>skulle</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="3">
         <form>forslaget</form>
         <lemma>forslag</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>SUBJ</deprel>
         <childnodes>
          <LM order="5">
           <form>fremmes</form>
           <lemma>fremme</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pres</LM>
            <LM>pass</LM>
           </feats>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="4">
             <form>som</form>
             <lemma>som</lemma>
             <cpostag>sbu</cpostag>
             <postag>sbu</postag>
             <deprel>SBU</deprel>
            </LM>
            <LM order="6">
             <form>til</form>
             <lemma>til</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ADV</deprel>
             <childnodes>
              <LM order="7">
               <form>våren</form>
               <lemma>vår</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>be</LM>
                <LM>ent</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
            <LM order="8">
             <form>,</form>
             <lemma>$,</lemma>
             <cpostag>&lt;komma&gt;</cpostag>
             <postag>&lt;komma&gt;</postag>
             <deprel>IK</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="10">
         <form>gå</form>
         <lemma>gå</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>inf</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="11">
           <form>ut</form>
           <lemma>ut</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="12">
             <form>på</form>
             <lemma>på</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="2">
               <form>hva</form>
               <lemma>hva</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>sp</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
               <childnodes>
                <LM order="1">
                 <form>Nøyaktig</form>
                 <lemma>nøyaktig</lemma>
                 <cpostag>adj</cpostag>
                 <postag>adj</postag>
                 <feats>
                  <LM>nøyt</LM>
                  <LM>ub</LM>
                  <LM>ent</LM>
                  <LM>pos</LM>
                 </feats>
                 <deprel>ATR</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="13">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="16">
       <form>ikke</form>
       <lemma>ikke</lemma>
       <cpostag>adv</cpostag>
       <postag>adv</postag>
       <deprel>ADV</deprel>
      </LM>
      <LM order="18">
       <form>her</form>
       <lemma>her</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="20">
         <form>nå</form>
         <lemma>nå</lemma>
         <cpostag>adv</cpostag>
         <postag>adv</postag>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="19">
           <form>og</form>
           <lemma>og</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikke-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="21">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>står</form>
   <lemma>stå</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Men</form>
     <lemma>men</lemma>
     <cpostag>konj</cpostag>
     <postag>konj</postag>
     <feats>
      <LM>clb</LM>
     </feats>
     <deprel>KONJ</deprel>
    </LM>
    <LM order="2">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="4">
     <form>fast</form>
     <lemma>fast</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>ADV</deprel>
    </LM>
    <LM order="5">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="8">
     <form>sa</form>
     <lemma>si</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="6">
       <form>som</form>
       <lemma>som</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="7">
       <form>jeg</form>
       <lemma>jeg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>ent</LM>
        <LM>pers</LM>
        <LM>hum</LM>
        <LM>nom</LM>
        <LM>1</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="9">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>akter</form>
     <lemma>akte</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PSUBJ</deprel>
     <childnodes>
      <LM order="10">
       <form>at</form>
       <lemma>at</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="11">
       <form>vi</form>
       <lemma>vi</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>fl</LM>
        <LM>pers</LM>
        <LM>hum</LM>
        <LM>nom</LM>
        <LM>1</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="13">
       <form>å</form>
       <lemma>å</lemma>
       <cpostag>inf-merke</cpostag>
       <postag>inf-merke</postag>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="14">
         <form>følge</form>
         <lemma>følge</lemma>
         <cpostag>verb</cpostag>
         <postag>verb</postag>
         <feats>
          <LM>inf</LM>
         </feats>
         <deprel>INFV</deprel>
         <childnodes>
          <LM order="15">
           <form>opp</form>
           <lemma>opp</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
          </LM>
          <LM order="16">
           <form>det</form>
           <lemma>det</lemma>
           <cpostag>pron</cpostag>
           <postag>pron</postag>
           <feats>
            <LM>nøyt</LM>
            <LM>ent</LM>
            <LM>pers</LM>
            <LM>3</LM>
           </feats>
           <deprel>DOBJ</deprel>
           <childnodes>
            <LM order="18">
             <form>sa</form>
             <lemma>si</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pret</LM>
             </feats>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="17">
               <form>statsministeren</form>
               <lemma>statsminister</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>be</LM>
                <LM>ent</LM>
               </feats>
               <deprel>SUBJ</deprel>
              </LM>
              <LM order="19">
               <form>i</form>
               <lemma>i</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="21">
                 <form>foredrag</form>
                 <lemma>foredrag</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>appell</LM>
                  <LM>nøyt</LM>
                  <LM>ub</LM>
                  <LM>ent</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="20">
                   <form>sitt</form>
                   <lemma>sin</lemma>
                   <cpostag>det</cpostag>
                   <postag>det</postag>
                   <feats>
                    <LM>nøyt</LM>
                    <LM>ent</LM>
                    <LM>poss</LM>
                   </feats>
                   <deprel>DET</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
              <LM order="22">
               <form>på</form>
               <lemma>på</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="23">
                 <form>NHO-konferansen</form>
                 <lemma>NHO-konferanse</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>appell</LM>
                  <LM>mask</LM>
                  <LM>be</LM>
                  <LM>ent</LM>
                  <LM>samset</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                </LM>
               </childnodes>
              </LM>
              <LM order="24">
               <form>,</form>
               <lemma>$,</lemma>
               <cpostag>&lt;komma&gt;</cpostag>
               <postag>&lt;komma&gt;</postag>
               <deprel>IK</deprel>
              </LM>
              <LM order="27">
               <form>siterte</form>
               <lemma>sitere</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>pret</LM>
               </feats>
               <deprel>KOORD</deprel>
               <childnodes>
                <LM order="25">
                 <form>som</form>
                 <lemma>som</lemma>
                 <cpostag>sbu</cpostag>
                 <postag>sbu</postag>
                 <deprel>SBU</deprel>
                </LM>
                <LM order="26">
                 <form>jeg</form>
                 <lemma>jeg</lemma>
                 <cpostag>pron</cpostag>
                 <postag>pron</postag>
                 <feats>
                  <LM>ent</LM>
                  <LM>pers</LM>
                  <LM>hum</LM>
                  <LM>nom</LM>
                  <LM>1</LM>
                 </feats>
                 <deprel>SUBJ</deprel>
                </LM>
                <LM order="28">
                 <form>i</form>
                 <lemma>i</lemma>
                 <cpostag>prep</cpostag>
                 <postag>prep</postag>
                 <deprel>ADV</deprel>
                 <childnodes>
                  <LM order="31">
                   <form>svar</form>
                   <lemma>svar</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                   </feats>
                   <deprel>PUTFYLL</deprel>
                   <childnodes>
                    <LM order="29">
                     <form>mitt</form>
                     <lemma>min</lemma>
                     <cpostag>det</cpostag>
                     <postag>det</postag>
                     <feats>
                      <LM>nøyt</LM>
                      <LM>ent</LM>
                      <LM>poss</LM>
                     </feats>
                     <deprel>DET</deprel>
                    </LM>
                    <LM order="30">
                     <form>forrige</form>
                     <lemma>forrige</lemma>
                     <cpostag>det</cpostag>
                     <postag>det</postag>
                     <feats>
                      <LM>dem</LM>
                      <LM>be</LM>
                      <LM>&lt;adj&gt;</LM>
                     </feats>
                     <deprel>DET</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="32">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
