<?xml version="1.0" encoding="UTF-8"?>
<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
  <head>
    <schema href="out_schema.xml" />
  </head>
  <body>
    <LM order="2">
      <form>vet</form>
      <lemma>vite</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pres</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Vi</form>
          <lemma>vi</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>fl</LM>
            <LM>pers</LM>
            <LM>hum</LM>
            <LM>nom</LM>
            <LM>1</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="8">
          <form>sitter</form>
          <lemma>sitte</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>pres</feats>
          <deprel>DOBJ</deprel>
          <childnodes>
            <LM order="3">
              <form>at</form>
              <lemma>at</lemma>
              <cpostag>sbu</cpostag>
              <postag>sbu</postag>
              <deprel>SBU</deprel>
            </LM>
            <LM order="4">
              <form>representantene</form>
              <lemma>representant</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>be</LM>
                <LM>fl</LM>
              </feats>
              <deprel>SUBJ</deprel>
              <childnodes order="5">
                <form>i</form>
                <lemma>i</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ATR</deprel>
                <childnodes order="7">
                  <form>sal</form>
                  <lemma>sal</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>appell</LM>
                    <LM>mask</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                  </feats>
                  <deprel>PUTFYLL</deprel>
                  <childnodes order="6">
                    <form>denne</form>
                    <lemma>denne</lemma>
                    <cpostag>det</cpostag>
                    <postag>det</postag>
                    <feats>
                      <LM>dem</LM>
                      <LM>mask</LM>
                      <LM>ent</LM>
                    </feats>
                    <deprel>DET</deprel>
                  </childnodes>
                </childnodes>
              </childnodes>
            </LM>
            <LM order="9">
              <form>med</form>
              <lemma>med</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="11">
                <form>erfaringer</form>
                <lemma>erfaring</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>appell</LM>
                  <LM>fem</LM>
                  <LM>ub</LM>
                  <LM>fl</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="10">
                    <form>verdifulle</form>
                    <lemma>verdifull</lemma>
                    <cpostag>adj</cpostag>
                    <postag>adj</postag>
                    <feats>
                      <LM>fl</LM>
                      <LM>pos</LM>
                    </feats>
                    <deprel>ATR</deprel>
                  </LM>
                  <LM order="13">
                    <form>kunnskaper</form>
                    <lemma>kunnskap</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>appell</LM>
                      <LM>mask</LM>
                      <LM>ub</LM>
                      <LM>fl</LM>
                    </feats>
                    <deprel>KOORD</deprel>
                    <childnodes order="12">
                      <form>og</form>
                      <lemma>og</lemma>
                      <cpostag>konj</cpostag>
                      <postag>konj</postag>
                      <feats>&lt;ikke-clb></feats>
                      <deprel>KONJ</deprel>
                    </childnodes>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
            <LM order="14">
              <form>-</form>
              <lemma>$-</lemma>
              <cpostag>&lt;strek></cpostag>
              <postag>&lt;strek></postag>
              <deprel>IK</deprel>
            </LM>
            <LM order="15">
              <form>mange</form>
              <lemma>mange</lemma>
              <cpostag>adj</cpostag>
              <postag>adj</postag>
              <feats>
                <LM>fl</LM>
                <LM>pos</LM>
              </feats>
              <deprel>KOORD-ELL</deprel>
              <childnodes>
                <LM order="16">
                  <form>fra</form>
                  <lemma>fra</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>ADV</deprel>
                  <childnodes order="19">
                    <form>arbeid</form>
                    <lemma>arbeid</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>appell</LM>
                      <LM>nøyt</LM>
                      <LM>ub</LM>
                      <LM>ent</LM>
                    </feats>
                    <deprel>PUTFYLL</deprel>
                    <childnodes>
                      <LM order="17">
                        <form>langvarig</form>
                        <lemma>langvarig</lemma>
                        <cpostag>adj</cpostag>
                        <postag>adj</postag>
                        <feats>
                          <LM>nøyt</LM>
                          <LM>ub</LM>
                          <LM>ent</LM>
                          <LM>pos</LM>
                        </feats>
                        <deprel>ATR</deprel>
                      </LM>
                      <LM order="18">
                        <form>politisk</form>
                        <lemma>politisk</lemma>
                        <cpostag>adj</cpostag>
                        <postag>adj</postag>
                        <feats>
                          <LM>nøyt</LM>
                          <LM>ub</LM>
                          <LM>ent</LM>
                          <LM>pos</LM>
                        </feats>
                        <deprel>ATR</deprel>
                      </LM>
                    </childnodes>
                  </childnodes>
                </LM>
                <LM order="20">
                  <form>,</form>
                  <lemma>$,</lemma>
                  <cpostag>&lt;komma&gt;</cpostag>
                  <postag>&lt;komma&gt;</postag>
                  <deprel>IK</deprel>
                </LM>
              </childnodes>
            </LM>
            <LM order="21">
              <form>andre</form>
              <lemma>annen</lemma>
              <cpostag>det</cpostag>
              <postag>det</postag>
              <feats>
                <LM>dem</LM>
                <LM>fl</LM>
                <LM>&lt;adj></LM>
              </feats>
              <deprel>KOORD-ELL</deprel>
              <childnodes order="22">
                <form>fra</form>
                <lemma>fra</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ADV</deprel>
                <childnodes order="24">
                  <form>sektorer</form>
                  <lemma>sektor</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>appell</LM>
                    <LM>mask</LM>
                    <LM>ub</LM>
                    <LM>fl</LM>
                  </feats>
                  <deprel>PUTFYLL</deprel>
                  <childnodes>
                    <LM order="23">
                      <form>ulike</form>
                      <lemma>ulik</lemma>
                      <cpostag>adj</cpostag>
                      <postag>adj</postag>
                      <feats>
                        <LM>fl</LM>
                        <LM>pos</LM>
                      </feats>
                      <deprel>ATR</deprel>
                    </LM>
                    <LM order="25">
                      <form>i</form>
                      <lemma>i</lemma>
                      <cpostag>prep</cpostag>
                      <postag>prep</postag>
                      <deprel>ATR</deprel>
                      <childnodes order="26">
                        <form>samfunnet</form>
                        <lemma>samfunn</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>
                          <LM>appell</LM>
                          <LM>nøyt</LM>
                          <LM>be</LM>
                          <LM>ent</LM>
                        </feats>
                        <deprel>PUTFYLL</deprel>
                        <childnodes>
                          <LM order="27">
                            <form>,</form>
                            <lemma>$,</lemma>
                            <cpostag>&lt;komma&gt;</cpostag>
                            <postag>&lt;komma&gt;</postag>
                            <deprel>IK</deprel>
                          </LM>
                          <LM order="28">
                            <form>landsdeler</form>
                            <lemma>landsdel</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>appell</LM>
                              <LM>mask</LM>
                              <LM>ub</LM>
                              <LM>fl</LM>
                            </feats>
                            <deprel>KOORD</deprel>
                          </LM>
                          <LM order="30">
                            <form>kommuner</form>
                            <lemma>kommune</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>appell</LM>
                              <LM>mask</LM>
                              <LM>ub</LM>
                              <LM>fl</LM>
                            </feats>
                            <deprel>KOORD</deprel>
                            <childnodes order="29">
                              <form>og</form>
                              <lemma>og</lemma>
                              <cpostag>konj</cpostag>
                              <postag>konj</postag>
                              <feats>&lt;ikke-clb></feats>
                              <deprel>KONJ</deprel>
                            </childnodes>
                          </LM>
                        </childnodes>
                      </childnodes>
                    </LM>
                  </childnodes>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="31">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>har</form>
      <lemma>ha</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Vi</form>
          <lemma>vi</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>fl</LM>
            <LM>pers</LM>
            <LM>hum</LM>
            <LM>nom</LM>
            <LM>1</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>bruk</form>
          <lemma>bruk</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>ent</LM>
          </feats>
          <deprel>DOBJ</deprel>
          <childnodes order="4">
            <form>for</form>
            <lemma>for</lemma>
            <cpostag>prep</cpostag>
            <postag>prep</postag>
            <deprel>ATR</deprel>
            <childnodes order="6">
              <form>innsikt</form>
              <lemma>innsikt</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>appell</LM>
                <LM>fem</LM>
                <LM>ub</LM>
                <LM>ent</LM>
              </feats>
              <deprel>PUTFYLL</deprel>
              <childnodes>
                <LM order="5">
                  <form>alles</form>
                  <lemma>alle</lemma>
                  <cpostag>pron</cpostag>
                  <postag>pron</postag>
                  <feats>
                    <LM>fl</LM>
                    <LM>pers</LM>
                    <LM>3</LM>
                    <LM>gen</LM>
                  </feats>
                  <deprel>DET</deprel>
                </LM>
                <LM order="9">
                  <form>kompetanse</form>
                  <lemma>kompetanse</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>appell</LM>
                    <LM>mask</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                  </feats>
                  <deprel>KOORD</deprel>
                  <childnodes>
                    <LM order="7">
                      <form>og</form>
                      <lemma>og</lemma>
                      <cpostag>konj</cpostag>
                      <postag>konj</postag>
                      <feats>&lt;ikke-clb></feats>
                      <deprel>KONJ</deprel>
                    </LM>
                    <LM order="8">
                      <form>alles</form>
                      <lemma>alle</lemma>
                      <cpostag>pron</cpostag>
                      <postag>pron</postag>
                      <feats>
                        <LM>fl</LM>
                        <LM>pers</LM>
                        <LM>3</LM>
                        <LM>gen</LM>
                      </feats>
                      <deprel>DET</deprel>
                    </LM>
                  </childnodes>
                </LM>
              </childnodes>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="10">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="7">
      <form>må</form>
      <lemma>måtte</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="2">
          <form>organisasjoner</form>
          <lemma>organisasjon</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>fl</LM>
          </feats>
          <deprel>SUBJ</deprel>
          <childnodes>
            <LM order="1">
              <form>Også</form>
              <lemma>også</lemma>
              <cpostag>adv</cpostag>
              <postag>adv</postag>
              <deprel>ATR</deprel>
            </LM>
            <LM order="3">
              <form>,</form>
              <lemma>$,</lemma>
              <cpostag>&lt;komma&gt;</cpostag>
              <postag>&lt;komma&gt;</postag>
              <deprel>IK</deprel>
            </LM>
            <LM order="4">
              <form>bedrifter</form>
              <lemma>bedrift</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>ub</LM>
                <LM>fl</LM>
              </feats>
              <deprel>KOORD</deprel>
            </LM>
            <LM order="6">
              <form>enkeltpersoner</form>
              <lemma>enkeltperson</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>ub</LM>
                <LM>fl</LM>
              </feats>
              <deprel>KOORD</deprel>
              <childnodes order="5">
                <form>og</form>
                <lemma>og</lemma>
                <cpostag>konj</cpostag>
                <postag>konj</postag>
                <feats>&lt;ikke-clb></feats>
                <deprel>KONJ</deprel>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="8">
          <form>engasjere</form>
          <lemma>engasjere</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>inf</feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="9">
              <form>seg</form>
              <lemma>seg</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>akk</LM>
                <LM>refl</LM>
              </feats>
              <deprel>DOBJ</deprel>
            </LM>
            <LM order="10">
              <form>i</form>
              <lemma>i</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="13">
                <form>skal</form>
                <lemma>skulle</lemma>
                <cpostag>verb</cpostag>
                <postag>verb</postag>
                <feats>
                  <LM>pres</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="12">
                    <form>vi</form>
                    <lemma>vi</lemma>
                    <cpostag>pron</cpostag>
                    <postag>pron</postag>
                    <feats>
                      <LM>fl</LM>
                      <LM>pers</LM>
                      <LM>hum</LM>
                      <LM>nom</LM>
                      <LM>1</LM>
                    </feats>
                    <deprel>SUBJ</deprel>
                  </LM>
                  <LM order="14">
                    <form>utvikle</form>
                    <lemma>utvikle</lemma>
                    <cpostag>verb</cpostag>
                    <postag>verb</postag>
                    <feats>inf</feats>
                    <deprel>INFV</deprel>
                    <childnodes>
                      <LM order="11">
                        <form>hvordan</form>
                        <lemma>hvordan</lemma>
                        <cpostag>adv</cpostag>
                        <postag>adv</postag>
                        <deprel>ADV</deprel>
                      </LM>
                      <LM order="15">
                        <form>Norge</form>
                        <lemma>Norge</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>prop</feats>
                        <deprel>DOBJ</deprel>
                      </LM>
                      <LM order="17">
                        <form>ta</form>
                        <lemma>ta</lemma>
                        <cpostag>verb</cpostag>
                        <postag>verb</postag>
                        <feats>inf</feats>
                        <deprel>KOORD</deprel>
                        <childnodes>
                          <LM order="16">
                            <form>og</form>
                            <lemma>og</lemma>
                            <cpostag>konj</cpostag>
                            <postag>konj</postag>
                            <feats>&lt;ikke-clb></feats>
                            <deprel>KONJ</deprel>
                          </LM>
                          <LM order="18">
                            <form>mulighetene</form>
                            <lemma>mulighet</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>appell</LM>
                              <LM>fem</LM>
                              <LM>be</LM>
                              <LM>fl</LM>
                            </feats>
                            <deprel>DOBJ</deprel>
                          </LM>
                          <LM order="19">
                            <form>i</form>
                            <lemma>i</lemma>
                            <cpostag>prep</cpostag>
                            <postag>prep</postag>
                            <deprel>ADV</deprel>
                            <childnodes order="20">
                              <form>bruk</form>
                              <lemma>bruk</lemma>
                              <cpostag>subst</cpostag>
                              <postag>subst</postag>
                              <feats>
                                <LM>appell</LM>
                                <LM>mask</LM>
                                <LM>ub</LM>
                                <LM>ent</LM>
                              </feats>
                              <deprel>PUTFYLL</deprel>
                            </childnodes>
                          </LM>
                        </childnodes>
                      </LM>
                    </childnodes>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="21">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>vil</form>
      <lemma>ville</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Vi</form>
          <lemma>vi</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>fl</LM>
            <LM>pers</LM>
            <LM>hum</LM>
            <LM>nom</LM>
            <LM>1</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>være</form>
          <lemma>være</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>
            <LM>inf</LM>
          </feats>
          <deprel>INFV</deprel>
          <childnodes order="4">
            <form>åpne</form>
            <lemma>åpen</lemma>
            <cpostag>adj</cpostag>
            <postag>adj</postag>
            <feats>
              <LM>fl</LM>
              <LM>pos</LM>
            </feats>
            <deprel>SPRED</deprel>
          </childnodes>
        </LM>
        <LM order="5">
          <form>,</form>
          <lemma>$,</lemma>
          <cpostag>&lt;komma&gt;</cpostag>
          <postag>&lt;komma&gt;</postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="8">
          <form>vil</form>
          <lemma>ville</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>
            <LM>pres</LM>
          </feats>
          <deprel>KOORD</deprel>
          <childnodes>
            <LM order="6">
              <form>og</form>
              <lemma>og</lemma>
              <cpostag>konj</cpostag>
              <postag>konj</postag>
              <feats>clb</feats>
              <deprel>KONJ</deprel>
            </LM>
            <LM order="7">
              <form>vi</form>
              <lemma>vi</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>fl</LM>
                <LM>pers</LM>
                <LM>hum</LM>
                <LM>nom</LM>
                <LM>1</LM>
              </feats>
              <deprel>SUBJ</deprel>
            </LM>
            <LM order="9">
              <form>ha</form>
              <lemma>ha</lemma>
              <cpostag>verb</cpostag>
              <postag>verb</postag>
              <feats>
                <LM>inf</LM>
              </feats>
              <deprel>INFV</deprel>
              <childnodes>
                <LM order="10">
                  <form>dialog</form>
                  <lemma>dialog</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>appell</LM>
                    <LM>mask</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                  </feats>
                  <deprel>DOBJ</deprel>
                  <childnodes order="11">
                    <form>med</form>
                    <lemma>med</lemma>
                    <cpostag>prep</cpostag>
                    <postag>prep</postag>
                    <deprel>ATR</deprel>
                    <childnodes>
                      <LM order="12">
                        <form>folk</form>
                        <lemma>folk</lemma>
                        <cpostag>subst</cpostag>
                        <postag>subst</postag>
                        <feats>
                          <LM>appell</LM>
                          <LM>nøyt</LM>
                          <LM>ub</LM>
                          <LM>fl</LM>
                        </feats>
                        <deprel>PUTFYLL</deprel>
                        <childnodes order="13">
                          <form>i</form>
                          <lemma>i</lemma>
                          <cpostag>prep</cpostag>
                          <postag>prep</postag>
                          <deprel>ATR</deprel>
                          <childnodes order="15">
                            <form>landet</form>
                            <lemma>land</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>appell</LM>
                              <LM>nøyt</LM>
                              <LM>be</LM>
                              <LM>ent</LM>
                            </feats>
                            <deprel>PUTFYLL</deprel>
                            <childnodes order="14">
                              <form>hele</form>
                              <lemma>hel</lemma>
                              <cpostag>adj</cpostag>
                              <postag>adj</postag>
                              <feats>
                                <LM>be</LM>
                                <LM>ent</LM>
                                <LM>pos</LM>
                              </feats>
                              <deprel>ATR</deprel>
                            </childnodes>
                          </childnodes>
                        </childnodes>
                      </LM>
                      <LM order="17">
                        <form>med</form>
                        <lemma>med</lemma>
                        <cpostag>prep</cpostag>
                        <postag>prep</postag>
                        <deprel>KOORD</deprel>
                        <childnodes>
                          <LM order="16">
                            <form>og</form>
                            <lemma>og</lemma>
                            <cpostag>konj</cpostag>
                            <postag>konj</postag>
                            <feats>&lt;ikke-clb></feats>
                            <deprel>KONJ</deprel>
                          </LM>
                          <LM order="18">
                            <form>mangfoldet</form>
                            <lemma>mangfold</lemma>
                            <cpostag>subst</cpostag>
                            <postag>subst</postag>
                            <feats>
                              <LM>appell</LM>
                              <LM>nøyt</LM>
                              <LM>be</LM>
                              <LM>ent</LM>
                            </feats>
                            <deprel>PUTFYLL</deprel>
                            <childnodes order="19">
                              <form>av</form>
                              <lemma>av</lemma>
                              <cpostag>prep</cpostag>
                              <postag>prep</postag>
                              <deprel>ATR</deprel>
                              <childnodes order="20">
                                <form>organisasjoner</form>
                                <lemma>organisasjon</lemma>
                                <cpostag>subst</cpostag>
                                <postag>subst</postag>
                                <feats>
                                  <LM>appell</LM>
                                  <LM>mask</LM>
                                  <LM>ub</LM>
                                  <LM>fl</LM>
                                </feats>
                                <deprel>PUTFYLL</deprel>
                              </childnodes>
                            </childnodes>
                          </LM>
                        </childnodes>
                      </LM>
                    </childnodes>
                  </childnodes>
                </LM>
                <LM order="21">
                  <form>,</form>
                  <lemma>$,</lemma>
                  <cpostag>&lt;komma&gt;</cpostag>
                  <postag>&lt;komma&gt;</postag>
                  <deprel>IK</deprel>
                </LM>
                <LM order="26">
                  <form>kan</form>
                  <lemma>kunne</lemma>
                  <cpostag>verb</cpostag>
                  <postag>verb</postag>
                  <feats>
                    <LM>pres</LM>
                  </feats>
                  <deprel>ADV</deprel>
                  <childnodes>
                    <LM order="23">
                      <form>at</form>
                      <lemma>at</lemma>
                      <cpostag>sbu</cpostag>
                      <postag>sbu</postag>
                      <deprel>SBU</deprel>
                      <childnodes order="22">
                        <form>slik</form>
                        <lemma>slik</lemma>
                        <cpostag>adv</cpostag>
                        <postag>adv</postag>
                        <deprel>ADV</deprel>
                      </childnodes>
                    </LM>
                    <LM order="24">
                      <form>vi</form>
                      <lemma>vi</lemma>
                      <cpostag>pron</cpostag>
                      <postag>pron</postag>
                      <feats>
                        <LM>fl</LM>
                        <LM>pers</LM>
                        <LM>hum</LM>
                        <LM>nom</LM>
                        <LM>1</LM>
                      </feats>
                      <deprel>SUBJ</deprel>
                    </LM>
                    <LM order="27">
                      <form>få</form>
                      <lemma>få</lemma>
                      <cpostag>verb</cpostag>
                      <postag>verb</postag>
                      <feats>
                        <LM>inf</LM>
                      </feats>
                      <deprel>INFV</deprel>
                      <childnodes>
                        <LM order="25">
                          <form>sammen</form>
                          <lemma>sammen</lemma>
                          <cpostag>adv</cpostag>
                          <postag>adv</postag>
                          <deprel>ADV</deprel>
                        </LM>
                        <LM order="28">
                          <form>til</form>
                          <lemma>til</lemma>
                          <cpostag>prep</cpostag>
                          <postag>prep</postag>
                          <deprel>ADV</deprel>
                        </LM>
                        <LM order="30">
                          <form>resultater</form>
                          <lemma>resultat</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>appell</LM>
                            <LM>nøyt</LM>
                            <LM>ub</LM>
                            <LM>fl</LM>
                          </feats>
                          <deprel>DOBJ</deprel>
                          <childnodes order="29">
                            <form>store</form>
                            <lemma>stor</lemma>
                            <cpostag>adj</cpostag>
                            <postag>adj</postag>
                            <feats>
                              <LM>fl</LM>
                              <LM>pos</LM>
                            </feats>
                            <deprel>ATR</deprel>
                          </childnodes>
                        </LM>
                      </childnodes>
                    </LM>
                  </childnodes>
                </LM>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="31">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>vil</form>
      <lemma>ville</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Regjeringen</form>
          <lemma>Regjeringen</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>prop</feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="7">
          <form>arbeide</form>
          <lemma>arbeide</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>inf</feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="6">
              <form>årene</form>
              <lemma>år</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>appell</LM>
                <LM>nøyt</LM>
                <LM>be</LM>
                <LM>fl</LM>
              </feats>
              <deprel>ADV</deprel>
              <childnodes>
                <LM order="3">
                  <form>de</form>
                  <lemma>de</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>dem</LM>
                    <LM>fl</LM>
                  </feats>
                  <deprel>DET</deprel>
                </LM>
                <LM order="4">
                  <form>neste</form>
                  <lemma>neste</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>dem</LM>
                    <LM>fl</LM>
                    <LM>&lt;adj></LM>
                  </feats>
                  <deprel>DET</deprel>
                </LM>
                <LM order="5">
                  <form>fire</form>
                  <lemma>fire</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>fl</LM>
                    <LM>kvant</LM>
                  </feats>
                  <deprel>DET</deprel>
                </LM>
              </childnodes>
            </LM>
            <LM order="8">
              <form>for</form>
              <lemma>for</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="10">
                <form>Norge</form>
                <lemma>Norge</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>prop</feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="9">
                    <form>et</form>
                    <lemma>en</lemma>
                    <cpostag>det</cpostag>
                    <postag>det</postag>
                    <feats>
                      <LM>nøyt</LM>
                      <LM>ent</LM>
                      <LM>kvant</LM>
                    </feats>
                    <deprel>DET</deprel>
                  </LM>
                  <LM order="11">
                    <form>med</form>
                    <lemma>med</lemma>
                    <cpostag>prep</cpostag>
                    <postag>prep</postag>
                    <deprel>ATR</deprel>
                    <childnodes order="13">
                      <form>fellesskap</form>
                      <lemma>fellesskap</lemma>
                      <cpostag>subst</cpostag>
                      <postag>subst</postag>
                      <feats>
                        <LM>appell</LM>
                        <LM>nøyt</LM>
                        <LM>ub</LM>
                        <LM>ent</LM>
                      </feats>
                      <deprel>PUTFYLL</deprel>
                      <childnodes>
                        <LM order="12">
                          <form>mer</form>
                          <lemma>mye</lemma>
                          <cpostag>adj</cpostag>
                          <postag>adj</postag>
                          <feats>komp</feats>
                          <deprel>ATR</deprel>
                        </LM>
                        <LM order="16">
                          <form>rettferdighet</form>
                          <lemma>rettferdighet</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>appell</LM>
                            <LM>fem</LM>
                            <LM>ub</LM>
                            <LM>ent</LM>
                          </feats>
                          <deprel>KOORD</deprel>
                          <childnodes>
                            <LM order="14">
                              <form>og</form>
                              <lemma>og</lemma>
                              <cpostag>konj</cpostag>
                              <postag>konj</postag>
                              <feats>&lt;ikke-clb></feats>
                              <deprel>KONJ</deprel>
                            </LM>
                            <LM order="15">
                              <form>mer</form>
                              <lemma>mye</lemma>
                              <cpostag>adj</cpostag>
                              <postag>adj</postag>
                              <feats>komp</feats>
                              <deprel>ATR</deprel>
                            </LM>
                          </childnodes>
                        </LM>
                      </childnodes>
                    </childnodes>
                  </LM>
                  <LM order="17">
                    <form>,</form>
                    <lemma>$,</lemma>
                    <cpostag>&lt;komma&gt;</cpostag>
                    <postag>&lt;komma&gt;</postag>
                    <deprel>IK</deprel>
                  </LM>
                  <LM order="19">
                    <form>Norge</form>
                    <lemma>Norge</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>prop</feats>
                    <deprel>APP</deprel>
                    <childnodes>
                      <LM order="18">
                        <form>et</form>
                        <lemma>en</lemma>
                        <cpostag>det</cpostag>
                        <postag>det</postag>
                        <feats>
                          <LM>nøyt</LM>
                          <LM>ent</LM>
                          <LM>kvant</LM>
                        </feats>
                        <deprel>DET</deprel>
                      </LM>
                      <LM order="21">
                        <form>er</form>
                        <lemma>være</lemma>
                        <cpostag>verb</cpostag>
                        <postag>verb</postag>
                        <feats>
                          <LM>pres</LM>
                        </feats>
                        <deprel>ATR</deprel>
                        <childnodes>
                          <LM order="20">
                            <form>som</form>
                            <lemma>som</lemma>
                            <cpostag>sbu</cpostag>
                            <postag>sbu</postag>
                            <deprel>SBU</deprel>
                          </LM>
                          <LM order="23">
                            <form>bærekraftig</form>
                            <lemma>bærekraftig</lemma>
                            <cpostag>adj</cpostag>
                            <postag>adj</postag>
                            <feats>
                              <LM>ub</LM>
                              <LM>m/f</LM>
                              <LM>ent</LM>
                              <LM>pos</LM>
                            </feats>
                            <deprel>SPRED</deprel>
                            <childnodes>
                              <LM order="22">
                                <form>mer</form>
                                <lemma>mye</lemma>
                                <cpostag>adj</cpostag>
                                <postag>adj</postag>
                                <feats>komp</feats>
                                <deprel>ADV</deprel>
                              </LM>
                              <LM order="24">
                                <form>,</form>
                                <lemma>$,</lemma>
                                <cpostag>&lt;komma&gt;</cpostag>
                                <postag>&lt;komma&gt;</postag>
                                <deprel>IK</deprel>
                              </LM>
                              <LM order="27">
                                <form>engasjert</form>
                                <lemma>engasjere</lemma>
                                <cpostag>adj</cpostag>
                                <postag>adj</postag>
                                <feats>
                                  <LM>nøyt</LM>
                                  <LM>ub</LM>
                                  <LM>ent</LM>
                                  <LM>&lt;perf-part></LM>
                                </feats>
                                <deprel>KOORD</deprel>
                                <childnodes>
                                  <LM order="26">
                                    <form>internasjonalt</form>
                                    <lemma>internasjonal</lemma>
                                    <cpostag>adj</cpostag>
                                    <postag>adj</postag>
                                    <feats>
                                      <LM>nøyt</LM>
                                      <LM>ub</LM>
                                      <LM>ent</LM>
                                      <LM>pos</LM>
                                    </feats>
                                    <deprel>ADV</deprel>
                                    <childnodes order="25">
                                      <form>sterkere</form>
                                      <lemma>sterk</lemma>
                                      <cpostag>adj</cpostag>
                                      <postag>adj</postag>
                                      <feats>komp</feats>
                                      <deprel>ADV</deprel>
                                    </childnodes>
                                  </LM>
                                  <LM order="28">
                                    <form>,</form>
                                    <lemma>$,</lemma>
                                    <cpostag>&lt;komma&gt;</cpostag>
                                    <postag>&lt;komma&gt;</postag>
                                    <deprel>IK</deprel>
                                  </LM>
                                </childnodes>
                              </LM>
                              <LM order="29">
                                <form>bedre</form>
                                <lemma>god</lemma>
                                <cpostag>adj</cpostag>
                                <postag>adj</postag>
                                <feats>komp</feats>
                                <deprel>KOORD</deprel>
                                <childnodes>
                                  <LM order="30">
                                    <form>å</form>
                                    <lemma>å</lemma>
                                    <cpostag>inf-merke</cpostag>
                                    <postag>inf-merke</postag>
                                    <deprel>ADV</deprel>
                                    <childnodes order="31">
                                      <form>leve</form>
                                      <lemma>leve</lemma>
                                      <cpostag>verb</cpostag>
                                      <postag>verb</postag>
                                      <feats>inf</feats>
                                      <deprel>INFV</deprel>
                                      <childnodes order="32">
                                        <form>i</form>
                                        <lemma>i</lemma>
                                        <cpostag>prep</cpostag>
                                        <postag>prep</postag>
                                        <deprel>ADV</deprel>
                                      </childnodes>
                                    </childnodes>
                                  </LM>
                                  <LM order="33">
                                    <form>enn</form>
                                    <lemma>enn</lemma>
                                    <cpostag>prep</cpostag>
                                    <postag>prep</postag>
                                    <deprel>ADV</deprel>
                                    <childnodes order="35">
                                      <form>Norge</form>
                                      <lemma>Norge</lemma>
                                      <cpostag>subst</cpostag>
                                      <postag>subst</postag>
                                      <feats>prop</feats>
                                      <deprel>PUTFYLL</deprel>
                                      <childnodes>
                                        <LM order="34">
                                          <form>det</form>
                                          <lemma>det</lemma>
                                          <cpostag>det</cpostag>
                                          <postag>det</postag>
                                          <feats>
                                            <LM>dem</LM>
                                            <LM>nøyt</LM>
                                            <LM>ent</LM>
                                          </feats>
                                          <deprel>DET</deprel>
                                        </LM>
                                        <LM order="37">
                                          <form>overtok</form>
                                          <lemma>overta</lemma>
                                          <cpostag>verb</cpostag>
                                          <postag>verb</postag>
                                          <feats>pret</feats>
                                          <deprel>ATR</deprel>
                                          <childnodes>
                                            <LM order="36">
                                              <form>vi</form>
                                              <lemma>vi</lemma>
                                              <cpostag>pron</cpostag>
                                              <postag>pron</postag>
                                              <feats>
                                                <LM>fl</LM>
                                                <LM>pers</LM>
                                                <LM>hum</LM>
                                                <LM>nom</LM>
                                                <LM>1</LM>
                                              </feats>
                                              <deprel>SUBJ</deprel>
                                            </LM>
                                            <LM order="38">
                                              <form>styringen</form>
                                              <lemma>styring</lemma>
                                              <cpostag>subst</cpostag>
                                              <postag>subst</postag>
                                              <feats>
                                                <LM>appell</LM>
                                                <LM>mask</LM>
                                                <LM>be</LM>
                                                <LM>ent</LM>
                                              </feats>
                                              <deprel>DOBJ</deprel>
                                              <childnodes order="39">
                                                <form>av</form>
                                                <lemma>av</lemma>
                                                <cpostag>prep</cpostag>
                                                <postag>prep</postag>
                                                <deprel>ATR</deprel>
                                              </childnodes>
                                            </LM>
                                          </childnodes>
                                        </LM>
                                      </childnodes>
                                    </childnodes>
                                  </LM>
                                </childnodes>
                              </LM>
                            </childnodes>
                          </LM>
                        </childnodes>
                      </LM>
                    </childnodes>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="40">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="9">
      <form>vil</form>
      <lemma>ville</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="10">
          <form>Regjeringen</form>
          <lemma>Regjeringen</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>prop</feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="11">
          <form>strekke</form>
          <lemma>strekke</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>inf</feats>
          <deprel>INFV</deprel>
          <childnodes>
            <LM order="12">
              <form>seg</form>
              <lemma>seg</lemma>
              <cpostag>pron</cpostag>
              <postag>pron</postag>
              <feats>
                <LM>akk</LM>
                <LM>refl</LM>
              </feats>
              <deprel>DOBJ</deprel>
            </LM>
            <LM order="13">
              <form>etter</form>
              <lemma>etter</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="3">
                <form>utfordringer</form>
                <lemma>utfordring</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>appell</LM>
                  <LM>fem</LM>
                  <LM>ub</LM>
                  <LM>fl</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes>
                  <LM order="2">
                    <form>store</form>
                    <lemma>stor</lemma>
                    <cpostag>adj</cpostag>
                    <postag>adj</postag>
                    <feats>
                      <LM>fl</LM>
                      <LM>pos</LM>
                    </feats>
                    <deprel>ATR</deprel>
                    <childnodes order="1">
                      <form>Så</form>
                      <lemma>så</lemma>
                      <cpostag>adv</cpostag>
                      <postag>adv</postag>
                      <deprel>ADV</deprel>
                    </childnodes>
                  </LM>
                  <LM order="4">
                    <form>,</form>
                    <lemma>$,</lemma>
                    <cpostag>&lt;komma&gt;</cpostag>
                    <postag>&lt;komma&gt;</postag>
                    <deprel>IK</deprel>
                  </LM>
                  <LM order="7">
                    <form>mål</form>
                    <lemma>mål</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>appell</LM>
                      <LM>nøyt</LM>
                      <LM>ub</LM>
                      <LM>fl</LM>
                    </feats>
                    <deprel>KOORD</deprel>
                    <childnodes>
                      <LM order="6">
                        <form>store</form>
                        <lemma>stor</lemma>
                        <cpostag>adj</cpostag>
                        <postag>adj</postag>
                        <feats>
                          <LM>fl</LM>
                          <LM>pos</LM>
                        </feats>
                        <deprel>ATR</deprel>
                        <childnodes order="5">
                          <form>så</form>
                          <lemma>så</lemma>
                          <cpostag>adv</cpostag>
                          <postag>adv</postag>
                          <deprel>ADV</deprel>
                        </childnodes>
                      </LM>
                      <LM order="8">
                        <form>,</form>
                        <lemma>$,</lemma>
                        <cpostag>&lt;komma&gt;</cpostag>
                        <postag>&lt;komma&gt;</postag>
                        <deprel>IK</deprel>
                      </LM>
                    </childnodes>
                  </LM>
                </childnodes>
              </childnodes>
            </LM>
            <LM order="14">
              <form>i</form>
              <lemma>i</lemma>
              <cpostag>prep</cpostag>
              <postag>prep</postag>
              <deprel>ADV</deprel>
              <childnodes order="16">
                <form>arbeid</form>
                <lemma>arbeid</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>appell</LM>
                  <LM>nøyt</LM>
                  <LM>ub</LM>
                  <LM>ent</LM>
                </feats>
                <deprel>PUTFYLL</deprel>
                <childnodes order="15">
                  <form>sitt</form>
                  <lemma>sin</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>nøyt</LM>
                    <LM>ent</LM>
                    <LM>poss</LM>
                  </feats>
                  <deprel>DET</deprel>
                </childnodes>
              </childnodes>
            </LM>
          </childnodes>
        </LM>
        <LM order="17">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="2">
      <form>ser</form>
      <lemma>se</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>pres</feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Vi</form>
          <lemma>vi</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>fl</LM>
            <LM>pers</LM>
            <LM>hum</LM>
            <LM>nom</LM>
            <LM>1</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>fram</form>
          <lemma>fram</lemma>
          <cpostag>prep</cpostag>
          <postag>prep</postag>
          <deprel>ADV</deprel>
          <childnodes order="4">
            <form>til</form>
            <lemma>til</lemma>
            <cpostag>prep</cpostag>
            <postag>prep</postag>
            <deprel>PUTFYLL</deprel>
            <childnodes order="7">
              <form>samarbeid</form>
              <lemma>samarbeid</lemma>
              <cpostag>subst</cpostag>
              <postag>subst</postag>
              <feats>
                <LM>appell</LM>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>ent</LM>
              </feats>
              <deprel>PUTFYLL</deprel>
              <childnodes>
                <LM order="5">
                  <form>et</form>
                  <lemma>en</lemma>
                  <cpostag>det</cpostag>
                  <postag>det</postag>
                  <feats>
                    <LM>nøyt</LM>
                    <LM>ent</LM>
                    <LM>kvant</LM>
                  </feats>
                  <deprel>DET</deprel>
                </LM>
                <LM order="6">
                  <form>godt</form>
                  <lemma>god</lemma>
                  <cpostag>adj</cpostag>
                  <postag>adj</postag>
                  <feats>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                    <LM>pos</LM>
                  </feats>
                  <deprel>ATR</deprel>
                </LM>
                <LM order="8">
                  <form>med</form>
                  <lemma>med</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>ATR</deprel>
                  <childnodes order="10">
                    <form>partiene</form>
                    <lemma>parti</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>appell</LM>
                      <LM>nøyt</LM>
                      <LM>be</LM>
                      <LM>fl</LM>
                    </feats>
                    <deprel>PUTFYLL</deprel>
                    <childnodes>
                      <LM order="9">
                        <form>alle</form>
                        <lemma>all</lemma>
                        <cpostag>det</cpostag>
                        <postag>det</postag>
                        <feats>
                          <LM>fl</LM>
                          <LM>kvant</LM>
                        </feats>
                        <deprel>DET</deprel>
                      </LM>
                      <LM order="11">
                        <form>i</form>
                        <lemma>i</lemma>
                        <cpostag>prep</cpostag>
                        <postag>prep</postag>
                        <deprel>ATR</deprel>
                        <childnodes order="12">
                          <form>Stortinget</form>
                          <lemma>Stortinget</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>prop</LM>
                            <LM>nøyt</LM>
                          </feats>
                          <deprel>PUTFYLL</deprel>
                        </childnodes>
                      </LM>
                    </childnodes>
                  </childnodes>
                </LM>
                <LM order="13">
                  <form>for</form>
                  <lemma>for</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>ATR</deprel>
                  <childnodes>
                    <LM order="14">
                      <form>å</form>
                      <lemma>å</lemma>
                      <cpostag>inf-merke</cpostag>
                      <postag>inf-merke</postag>
                      <deprel>PUTFYLL</deprel>
                      <childnodes order="15">
                        <form>nå</form>
                        <lemma>nå</lemma>
                        <cpostag>verb</cpostag>
                        <postag>verb</postag>
                        <feats>inf</feats>
                        <deprel>INFV</deprel>
                        <childnodes order="17">
                          <form>målene</form>
                          <lemma>mål</lemma>
                          <cpostag>subst</cpostag>
                          <postag>subst</postag>
                          <feats>
                            <LM>appell</LM>
                            <LM>nøyt</LM>
                            <LM>be</LM>
                            <LM>fl</LM>
                          </feats>
                          <deprel>DOBJ</deprel>
                          <childnodes order="16">
                            <form>disse</form>
                            <lemma>disse</lemma>
                            <cpostag>det</cpostag>
                            <postag>det</postag>
                            <feats>
                              <LM>dem</LM>
                              <LM>fl</LM>
                            </feats>
                            <deprel>DET</deprel>
                          </childnodes>
                        </childnodes>
                      </childnodes>
                    </LM>
                    <LM order="18">
                      <form>,</form>
                      <lemma>$,</lemma>
                      <cpostag>&lt;komma&gt;</cpostag>
                      <postag>&lt;komma&gt;</postag>
                      <deprel>IK</deprel>
                    </LM>
                    <LM order="19">
                      <form>for</form>
                      <lemma>for</lemma>
                      <cpostag>prep</cpostag>
                      <postag>prep</postag>
                      <deprel>KOORD</deprel>
                      <childnodes order="20">
                        <form>å</form>
                        <lemma>å</lemma>
                        <cpostag>inf-merke</cpostag>
                        <postag>inf-merke</postag>
                        <deprel>PUTFYLL</deprel>
                        <childnodes order="21">
                          <form>ta</form>
                          <lemma>ta</lemma>
                          <cpostag>verb</cpostag>
                          <postag>verb</postag>
                          <feats>inf</feats>
                          <deprel>INFV</deprel>
                          <childnodes>
                            <LM order="22">
                              <form>mulighetene</form>
                              <lemma>mulighet</lemma>
                              <cpostag>subst</cpostag>
                              <postag>subst</postag>
                              <feats>
                                <LM>appell</LM>
                                <LM>fem</LM>
                                <LM>be</LM>
                                <LM>fl</LM>
                              </feats>
                              <deprel>DOBJ</deprel>
                            </LM>
                            <LM order="23">
                              <form>i</form>
                              <lemma>i</lemma>
                              <cpostag>prep</cpostag>
                              <postag>prep</postag>
                              <deprel>ADV</deprel>
                              <childnodes order="24">
                                <form>bruk</form>
                                <lemma>bruk</lemma>
                                <cpostag>subst</cpostag>
                                <postag>subst</postag>
                                <feats>
                                  <LM>appell</LM>
                                  <LM>mask</LM>
                                  <LM>ub</LM>
                                  <LM>ent</LM>
                                </feats>
                                <deprel>PUTFYLL</deprel>
                              </childnodes>
                            </LM>
                          </childnodes>
                        </childnodes>
                      </childnodes>
                    </LM>
                  </childnodes>
                </LM>
              </childnodes>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="25">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="1">
      <form>Presidenten</form>
      <lemma>president</lemma>
      <cpostag>subst</cpostag>
      <postag>subst</postag>
      <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>be</LM>
        <LM>ent</LM>
      </feats>
      <deprel>FRAG</deprel>
      <childnodes order="2">
        <form>:</form>
        <lemma>$:</lemma>
        <cpostag>clb</cpostag>
        <postag>clb</postag>
        <feats>&lt;kolon></feats>
        <deprel>IP</deprel>
      </childnodes>
    </LM>
    <LM order="2">
      <form>vil</form>
      <lemma>ville</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>Presidenten</form>
          <lemma>president</lemma>
          <cpostag>subst</cpostag>
          <postag>subst</postag>
          <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>be</LM>
            <LM>ent</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="3">
          <form>foreslå</form>
          <lemma>foreslå</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>inf</feats>
          <deprel>INFV</deprel>
          <childnodes order="7">
            <form>legges</form>
            <lemma>legge</lemma>
            <cpostag>verb</cpostag>
            <postag>verb</postag>
            <feats>
              <LM>pres</LM>
              <LM>pass</LM>
            </feats>
            <deprel>DOBJ</deprel>
            <childnodes>
              <LM order="4">
                <form>at</form>
                <lemma>at</lemma>
                <cpostag>sbu</cpostag>
                <postag>sbu</postag>
                <deprel>SBU</deprel>
              </LM>
              <LM order="6">
                <form>erklæring</form>
                <lemma>erklæring</lemma>
                <cpostag>subst</cpostag>
                <postag>subst</postag>
                <feats>
                  <LM>appell</LM>
                  <LM>fem</LM>
                  <LM>ub</LM>
                  <LM>ent</LM>
                </feats>
                <deprel>SUBJ</deprel>
                <childnodes order="5">
                  <form>Regjeringens</form>
                  <lemma>Regjeringen</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>prop</LM>
                    <LM>gen</LM>
                  </feats>
                  <deprel>DET</deprel>
                </childnodes>
              </LM>
              <LM order="8">
                <form>ut</form>
                <lemma>ut</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ADV</deprel>
                <childnodes order="9">
                  <form>til</form>
                  <lemma>til</lemma>
                  <cpostag>prep</cpostag>
                  <postag>prep</postag>
                  <deprel>PUTFYLL</deprel>
                  <childnodes order="10">
                    <form>behandling</form>
                    <lemma>behandling</lemma>
                    <cpostag>subst</cpostag>
                    <postag>subst</postag>
                    <feats>
                      <LM>appell</LM>
                      <LM>fem</LM>
                      <LM>ub</LM>
                      <LM>ent</LM>
                    </feats>
                    <deprel>PUTFYLL</deprel>
                  </childnodes>
                </childnodes>
              </LM>
              <LM order="11">
                <form>i</form>
                <lemma>i</lemma>
                <cpostag>prep</cpostag>
                <postag>prep</postag>
                <deprel>ADV</deprel>
                <childnodes order="14">
                  <form>møte</form>
                  <lemma>møte</lemma>
                  <cpostag>subst</cpostag>
                  <postag>subst</postag>
                  <feats>
                    <LM>appell</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                  </feats>
                  <deprel>PUTFYLL</deprel>
                  <childnodes>
                    <LM order="12">
                      <form>et</form>
                      <lemma>en</lemma>
                      <cpostag>det</cpostag>
                      <postag>det</postag>
                      <feats>
                        <LM>nøyt</LM>
                        <LM>ent</LM>
                        <LM>kvant</LM>
                      </feats>
                      <deprel>DET</deprel>
                    </LM>
                    <LM order="13">
                      <form>senere</form>
                      <lemma>sen</lemma>
                      <cpostag>adj</cpostag>
                      <postag>adj</postag>
                      <feats>komp</feats>
                      <deprel>ATR</deprel>
                    </LM>
                  </childnodes>
                </childnodes>
              </LM>
            </childnodes>
          </childnodes>
        </LM>
        <LM order="15">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
    <LM order="3">
      <form>anses</form>
      <lemma>anse</lemma>
      <cpostag>verb</cpostag>
      <postag>verb</postag>
      <feats>
        <LM>pres</LM>
        <LM>pass</LM>
      </feats>
      <deprel>FINV</deprel>
      <childnodes>
        <LM order="1">
          <form>-</form>
          <lemma>$-</lemma>
          <cpostag>&lt;strek></cpostag>
          <postag>&lt;strek></postag>
          <deprel>IK</deprel>
        </LM>
        <LM order="2">
          <form>Det</form>
          <lemma>det</lemma>
          <cpostag>pron</cpostag>
          <postag>pron</postag>
          <feats>
            <LM>nøyt</LM>
            <LM>ent</LM>
            <LM>pers</LM>
            <LM>3</LM>
          </feats>
          <deprel>SUBJ</deprel>
        </LM>
        <LM order="4">
          <form>vedtatt</form>
          <lemma>vedta</lemma>
          <cpostag>verb</cpostag>
          <postag>verb</postag>
          <feats>perf-part</feats>
          <deprel>INFV</deprel>
        </LM>
        <LM order="5">
          <form>.</form>
          <lemma>$.</lemma>
          <cpostag>clb</cpostag>
          <postag>clb</postag>
          <feats>&lt;punkt></feats>
          <deprel>IP</deprel>
        </LM>
      </childnodes>
    </LM>
  </body>
</conll>
