<conll xmlns="http://ufal.mff.cuni.cz/pdt/pml/">
 <head>
  <schema href="out_schema.xml" />
 </head>
 <body>
  <LM order="7">
   <form>må</form>
   <lemma>måtte</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="8">
     <form>man</form>
     <lemma>man</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="9">
     <form>bruke</form>
     <lemma>bruke</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="1">
       <form>For</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="2">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="3">
           <form>få</form>
           <lemma>få</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="4">
             <form>modulene</form>
             <lemma>modul</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>be</LM>
              <LM>fl</LM>
             </feats>
             <deprel>DOBJ</deprel>
            </LM>
            <LM order="5">
             <form>på</form>
             <lemma>på</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>OPRED</deprel>
             <childnodes>
              <LM order="6">
               <form>land</form>
               <lemma>land</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>ent</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="10">
       <form>helikopter</form>
       <lemma>helikopter</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>vil</form>
   <lemma>ville</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="2">
     <form>Frakten</form>
     <lemma>frakt</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>komme</form>
     <lemma>komme</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="5">
       <form>på</form>
       <lemma>på</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="8">
         <form>samme</form>
         <lemma>samme</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>be</LM>
          <LM>&lt;adj&gt;</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="6">
           <form>omtrent</form>
           <lemma>omtrent</lemma>
           <cpostag>adv</cpostag>
           <postag>adv</postag>
           <deprel>ATR</deprel>
          </LM>
          <LM order="7">
           <form>det</form>
           <lemma>det</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>nøyt</LM>
            <LM>ent</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="11">
           <form>kostet</form>
           <lemma>koste</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>pret</LM>
           </feats>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="9">
             <form>som</form>
             <lemma>som</lemma>
             <cpostag>sbu</cpostag>
             <postag>sbu</postag>
             <deprel>SBU</deprel>
            </LM>
            <LM order="10">
             <form>det</form>
             <lemma>det</lemma>
             <cpostag>pron</cpostag>
             <postag>pron</postag>
             <feats>
              <LM>nøyt</LM>
              <LM>ent</LM>
              <LM>pers</LM>
              <LM>3</LM>
             </feats>
             <deprel>FSUBJ</deprel>
            </LM>
            <LM order="12">
             <form>å</form>
             <lemma>å</lemma>
             <cpostag>inf-merke</cpostag>
             <postag>inf-merke</postag>
             <deprel>DOBJ</deprel>
             <childnodes>
              <LM order="13">
               <form>bygge</form>
               <lemma>bygge</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>inf</LM>
               </feats>
               <deprel>INFV</deprel>
               <childnodes>
                <LM order="14">
                 <form>forskningsstasjonen</form>
                 <lemma>forskningsstasjon</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>appell</LM>
                  <LM>mask</LM>
                  <LM>be</LM>
                  <LM>ent</LM>
                 </feats>
                 <deprel>DOBJ</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="15">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="16">
     <form>opplyser</form>
     <lemma>opplyse</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="17">
       <form>Øystein</form>
       <lemma>Øystein</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>mask</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="18">
         <form>Mikelborg</form>
         <lemma>Mikelborg</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
        <LM order="19">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
        <LM order="20">
         <form>direktør</form>
         <lemma>direktør</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>APP</deprel>
         <childnodes>
          <LM order="21">
           <form>ved</form>
           <lemma>ved</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="22">
             <form>avdeling</form>
             <lemma>avdeling</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>fem</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="23">
               <form>for</form>
               <lemma>for</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="24">
                 <form>operasjon</form>
                 <lemma>operasjon</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>appell</LM>
                  <LM>mask</LM>
                  <LM>ub</LM>
                  <LM>ent</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="26">
                   <form>logistikk</form>
                   <lemma>logistikk</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>mask</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                   </feats>
                   <deprel>KOORD</deprel>
                   <childnodes>
                    <LM order="25">
                     <form>og</form>
                     <lemma>og</lemma>
                     <cpostag>konj</cpostag>
                     <postag>konj</postag>
                     <feats>
                      <LM>&lt;ikke-clb&gt;</LM>
                     </feats>
                     <deprel>KONJ</deprel>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
              <LM order="27">
               <form>ved</form>
               <lemma>ved</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="28">
                 <form>Norsk</form>
                 <lemma>Norsk</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>prop</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="29">
                   <form>Polarinstitutt</form>
                   <lemma>Polarinstitutt</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>prop</LM>
                   </feats>
                   <deprel>FLAT</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="30">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="2">
     <form>ekspedisjon</form>
     <lemma>ekspedisjon</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="1">
       <form>Hver</form>
       <lemma>hver</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>mask</LM>
        <LM>ent</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>med</form>
     <lemma>med</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="5">
       <form>seg</form>
       <lemma>seg</lemma>
       <cpostag>pron</cpostag>
       <postag>pron</postag>
       <feats>
        <LM>akk</LM>
        <LM>refl</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>lege</form>
     <lemma>lege</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="10">
       <form>helsepersonell</form>
       <lemma>helsepersonell</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="7">
         <form>eller</form>
         <lemma>eller</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>&lt;ikke-clb&gt;</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="8">
         <form>annet</form>
         <lemma>annen</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
          <LM>&lt;adj&gt;</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="9">
         <form>kyndig</form>
         <lemma>kyndig</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="11">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>kan</form>
   <lemma>kunne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="6">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="7">
     <form>ta</form>
     <lemma>ta</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="1">
       <form>Skjer</form>
       <lemma>skje</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="2">
         <form>det</form>
         <lemma>det</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>ent</LM>
          <LM>pers</LM>
          <LM>3</LM>
         </feats>
         <deprel>FSUBJ</deprel>
        </LM>
        <LM order="3">
         <form>noe</form>
         <lemma>noe</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>nøyt</LM>
          <LM>ent</LM>
          <LM>pers</LM>
          <LM>3</LM>
         </feats>
         <deprel>PSUBJ</deprel>
        </LM>
        <LM order="4">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="8">
       <form>uker</form>
       <lemma>uke</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>fem</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
      <LM order="11">
       <form>får</form>
       <lemma>få</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="9">
         <form>før</form>
         <lemma>før</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="10">
         <form>man</form>
         <lemma>man</lemma>
         <cpostag>pron</cpostag>
         <postag>pron</postag>
         <feats>
          <LM>ent</LM>
          <LM>pers</LM>
          <LM>hum</LM>
          <LM>nom</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="12">
         <form>hjelp</form>
         <lemma>hjelp</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>fem</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DOBJ</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="13">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Norsk</form>
     <lemma>Norsk</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="2">
       <form>Polarinstitutt</form>
       <lemma>Polarinstitutt</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>forsket</form>
     <lemma>forske</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="4">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="6">
         <form>år</form>
         <lemma>år</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="5">
           <form>mange</form>
           <lemma>mange</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>fl</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="8">
       <form>på</form>
       <lemma>på</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="9">
         <form>sel</form>
         <lemma>sel</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="10">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="11">
           <form>pingviner</form>
           <lemma>pingvin</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>fl</LM>
           </feats>
           <deprel>KOORD</deprel>
          </LM>
          <LM order="13">
           <form>sjøfugl</form>
           <lemma>sjøfugl</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="12">
             <form>og</form>
             <lemma>og</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>&lt;ikke-clb&gt;</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
            <LM order="14">
             <form>på</form>
             <lemma>på</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="15">
               <form>øya</form>
               <lemma>øy</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>fem</LM>
                <LM>be</LM>
                <LM>ent</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="16">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Krillen</form>
     <lemma>krill</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="4">
     <form>nøkkelart</form>
     <lemma>nøkkelart</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
      <LM>samset</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="3">
       <form>en</form>
       <lemma>en</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>mask</LM>
        <LM>ent</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="5">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="8">
       <form>økosystemet</form>
       <lemma>økosystem</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="6">
         <form>det</form>
         <lemma>det</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>nøyt</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="7">
         <form>antarktiske</form>
         <lemma>antarktisk</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>be</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="9">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="5">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Kunnskapen</form>
     <lemma>kunnskap</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="2">
       <form>om</form>
       <lemma>om</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="4">
         <form>ressursen</form>
         <lemma>ressurs</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="3">
           <form>denne</form>
           <lemma>denne</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>mask</LM>
            <LM>ent</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="6">
     <form>minimal</form>
     <lemma>minimal</lemma>
     <cpostag>adj</cpostag>
     <postag>adj</postag>
     <feats>
      <LM>ub</LM>
      <LM>m/f</LM>
      <LM>ent</LM>
      <LM>pos</LM>
     </feats>
     <deprel>SPRED</deprel>
    </LM>
    <LM order="7">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="13">
   <form>ble</form>
   <lemma>bli</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Konvensjonen</form>
     <lemma>Konvensjonen</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="2">
       <form>for</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="3">
       <form>bevaring</form>
       <lemma>bevaring</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>fem</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="4">
       <form>av</form>
       <lemma>av</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="5">
       <form>marine</form>
       <lemma>marin</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>fl</LM>
        <LM>pos</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="6">
       <form>levende</form>
       <lemma>levende</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>fl</LM>
        <LM>pos</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="7">
       <form>ressurser</form>
       <lemma>ressurs</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="8">
       <form>i</form>
       <lemma>i</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="9">
       <form>Antarktis</form>
       <lemma>Antarktis</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
      <LM order="11">
       <form>CCAMLR</form>
       <lemma>CCAMLR</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>APP</deprel>
       <childnodes>
        <LM order="10">
         <form>(</form>
         <lemma>$(</lemma>
         <cpostag>&lt;parentes-beg&gt;</cpostag>
         <postag>&lt;parentes-beg&gt;</postag>
         <deprel>IK</deprel>
        </LM>
        <LM order="12">
         <form>)</form>
         <lemma>$)</lemma>
         <cpostag>&lt;parentes-slutt&gt;</cpostag>
         <postag>&lt;parentes-slutt&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>inngått</form>
     <lemma>inngå</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>perf-part</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="15">
       <form>mellom</form>
       <lemma>mellom</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="17">
         <form>stater</form>
         <lemma>stat</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>fl</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="16">
           <form>25</form>
           <lemma>25</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>fl</LM>
            <LM>kvant</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="18">
       <form>for</form>
       <lemma>for</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="19">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="20">
           <form>koordinere</form>
           <lemma>koordinere</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="21">
             <form>forskningsaktiviteter</form>
             <lemma>forskningsaktivitet</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>fl</LM>
             </feats>
             <deprel>DOBJ</deprel>
             <childnodes>
              <LM order="22">
               <form>,</form>
               <lemma>$,</lemma>
               <cpostag>&lt;komma&gt;</cpostag>
               <postag>&lt;komma&gt;</postag>
               <deprel>IK</deprel>
              </LM>
              <LM order="25">
               <form>skal</form>
               <lemma>skulle</lemma>
               <cpostag>verb</cpostag>
               <postag>verb</postag>
               <feats>
                <LM>pres</LM>
               </feats>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="23">
                 <form>som</form>
                 <lemma>som</lemma>
                 <cpostag>sbu</cpostag>
                 <postag>sbu</postag>
                 <deprel>SBU</deprel>
                </LM>
                <LM order="26">
                 <form>gi</form>
                 <lemma>gi</lemma>
                 <cpostag>verb</cpostag>
                 <postag>verb</postag>
                 <feats>
                  <LM>inf</LM>
                 </feats>
                 <deprel>INFV</deprel>
                 <childnodes>
                  <LM order="24">
                   <form>igjen</form>
                   <lemma>igjen</lemma>
                   <cpostag>adv</cpostag>
                   <postag>adv</postag>
                   <deprel>ADV</deprel>
                  </LM>
                  <LM order="27">
                   <form>grunnlag</form>
                   <lemma>grunnlag</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>nøyt</LM>
                    <LM>ub</LM>
                    <LM>ent</LM>
                   </feats>
                   <deprel>DOBJ</deprel>
                   <childnodes>
                    <LM order="28">
                     <form>for</form>
                     <lemma>for</lemma>
                     <cpostag>prep</cpostag>
                     <postag>prep</postag>
                     <deprel>ATR</deprel>
                     <childnodes>
                      <LM order="29">
                       <form>retningslinjer</form>
                       <lemma>retningslinje</lemma>
                       <cpostag>subst</cpostag>
                       <postag>subst</postag>
                       <feats>
                        <LM>appell</LM>
                        <LM>fem</LM>
                        <LM>ub</LM>
                        <LM>fl</LM>
                       </feats>
                       <deprel>PUTFYLL</deprel>
                       <childnodes>
                        <LM order="30">
                         <form>for</form>
                         <lemma>for</lemma>
                         <cpostag>prep</cpostag>
                         <postag>prep</postag>
                         <deprel>ATR</deprel>
                         <childnodes>
                          <LM order="31">
                           <form>fangst</form>
                           <lemma>fangst</lemma>
                           <cpostag>subst</cpostag>
                           <postag>subst</postag>
                           <feats>
                            <LM>appell</LM>
                            <LM>mask</LM>
                            <LM>ub</LM>
                            <LM>ent</LM>
                           </feats>
                           <deprel>PUTFYLL</deprel>
                           <childnodes>
                            <LM order="33">
                             <form>kvotesetting</form>
                             <lemma>kvotesetting</lemma>
                             <cpostag>subst</cpostag>
                             <postag>subst</postag>
                             <feats>
                              <LM>appell</LM>
                              <LM>fem</LM>
                              <LM>ub</LM>
                              <LM>ent</LM>
                              <LM>samset</LM>
                             </feats>
                             <deprel>KOORD</deprel>
                             <childnodes>
                              <LM order="32">
                               <form>og</form>
                               <lemma>og</lemma>
                               <cpostag>konj</cpostag>
                               <postag>konj</postag>
                               <feats>
                                <LM>&lt;ikke-clb&gt;</LM>
                               </feats>
                               <deprel>KONJ</deprel>
                              </LM>
                             </childnodes>
                            </LM>
                           </childnodes>
                          </LM>
                         </childnodes>
                        </LM>
                       </childnodes>
                      </LM>
                     </childnodes>
                    </LM>
                   </childnodes>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="34">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="6">
   <form>er</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="4">
     <form>Aker</form>
     <lemma>Aker</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
     </feats>
     <deprel>SUBJ</deprel>
     <childnodes>
      <LM order="1">
       <form>Kjell</form>
       <lemma>Kjell</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>mask</LM>
       </feats>
       <deprel>DET</deprel>
       <childnodes>
        <LM order="2">
         <form>Inge</form>
         <lemma>Inge</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
        <LM order="3">
         <form>Røkkes</form>
         <lemma>Røkke</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
          <LM>gen</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="5">
       <form>Biomarine</form>
       <lemma>Biomarine</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
       </feats>
       <deprel>FLAT</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>nå</form>
     <lemma>nå</lemma>
     <cpostag>adv</cpostag>
     <postag>adv</postag>
     <deprel>ADV</deprel>
    </LM>
    <LM order="11">
     <form>krillaktøren</form>
     <lemma>krillaktør</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>be</LM>
      <LM>ent</LM>
      <LM>samset</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="8">
       <form>den</form>
       <lemma>den</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>dem</LM>
        <LM>mask</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
      <LM order="9">
       <form>største</form>
       <lemma>stor</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>be</LM>
        <LM>sup</LM>
       </feats>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="12">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="13">
           <form>Sørishavet</form>
           <lemma>Sørishavet</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="10">
       <form>kommersielle</form>
       <lemma>kommersiell</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>be</LM>
        <LM>ent</LM>
        <LM>pos</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="14">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="12">
   <form>vil</form>
   <lemma>ville</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>-</form>
     <lemma>$-</lemma>
     <cpostag>&lt;strek&gt;</cpostag>
     <postag>&lt;strek&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="13">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="14">
     <form>ha</form>
     <lemma>ha</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="9">
       <form>reduserer</form>
       <lemma>redusere</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="2">
         <form>Hvis</form>
         <lemma>hvis</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="3">
         <form>fisket</form>
         <lemma>fiske</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>SUBJ</deprel>
         <childnodes>
          <LM order="4">
           <form>,</form>
           <lemma>$,</lemma>
           <cpostag>&lt;komma&gt;</cpostag>
           <postag>&lt;komma&gt;</postag>
           <deprel>IK</deprel>
          </LM>
          <LM order="5">
           <form>klimaendringer</form>
           <lemma>klimaendring</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>fem</LM>
            <LM>ub</LM>
            <LM>fl</LM>
           </feats>
           <deprel>KOORD</deprel>
          </LM>
          <LM order="8">
           <form>forhold</form>
           <lemma>forhold</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>fl</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="6">
             <form>eller</form>
             <lemma>eller</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>&lt;ikke-clb&gt;</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
            <LM order="7">
             <form>andre</form>
             <lemma>annen</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>dem</LM>
              <LM>fl</LM>
              <LM>&lt;adj&gt;</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="10">
         <form>krillbestanden</form>
         <lemma>krillbestand</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
          <LM>samset</LM>
         </feats>
         <deprel>DOBJ</deprel>
        </LM>
        <LM order="11">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="16">
       <form>konsekvenser</form>
       <lemma>konsekvens</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>mask</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="15">
         <form>enorme</form>
         <lemma>enorm</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>fl</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
        <LM order="17">
         <form>for</form>
         <lemma>for</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="19">
           <form>økosystemet</form>
           <lemma>økosystem</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>be</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="18">
             <form>hele</form>
             <lemma>hel</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>be</LM>
              <LM>ent</LM>
              <LM>pos</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="20">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>kan</form>
   <lemma>kunne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="4">
     <form>vi</form>
     <lemma>vi</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>fl</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
      <LM>1</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>sikre</form>
     <lemma>sikre</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="1">
       <form>Gjennom</form>
       <lemma>gjennom</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="2">
         <form>kunnskap</form>
         <lemma>kunnskap</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="7">
       <form>forvaltning</form>
       <lemma>forvaltning</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>fem</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="6">
         <form>god</form>
         <lemma>god</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>ub</LM>
          <LM>m/f</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
        <LM order="8">
         <form>gjennom</form>
         <lemma>gjennom</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="11">
           <form>kvoteregulering</form>
           <lemma>kvoteregulering</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>fem</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="9">
             <form>blant</form>
             <lemma>blant</lemma>
             <cpostag>prep</cpostag>
             <postag>prep</postag>
             
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="10">
               <form>annet</form>
               <lemma>annen</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>dem</LM>
                <LM>nøyt</LM>
                <LM>ub</LM>
                <LM>ent</LM>
                <LM>&lt;adj&gt;</LM>
               </feats>
               <deprel>PUTFYLL</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="12">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="13">
     <form>sier</form>
     <lemma>si</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>PAR</deprel>
     <childnodes>
      <LM order="14">
       <form>Birgit</form>
       <lemma>Birgit</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>fem</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="15">
         <form>Njåstad</form>
         <lemma>Njåstad</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
        <LM order="16">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
        <LM order="17">
         <form>leder</form>
         <lemma>leder</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>APP</deprel>
         <childnodes>
          <LM order="18">
           <form>for</form>
           <lemma>for</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ATR</deprel>
           <childnodes>
            <LM order="20">
             <form>seksjon</form>
             <lemma>seksjon</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
             <childnodes>
              <LM order="19">
               <form>miljørådgivende</form>
               <lemma>miljørådgivende</lemma>
               <cpostag>adj</cpostag>
               <postag>adj</postag>
               <feats>
                <LM>ub</LM>
                <LM>m/f</LM>
                <LM>ent</LM>
                <LM>pos</LM>
                <LM>samset</LM>
               </feats>
               <deprel>ATR</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="21">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="8">
   <form>kan</form>
   <lemma>kunne</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="9">
     <form>man</form>
     <lemma>man</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>hum</LM>
      <LM>nom</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="10">
     <form>gjøre</form>
     <lemma>gjøre</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>inf</LM>
     </feats>
     <deprel>INFV</deprel>
     <childnodes>
      <LM order="3">
       <form>er</form>
       <lemma>være</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pres</LM>
       </feats>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="1">
         <form>Siden</form>
         <lemma>siden</lemma>
         <cpostag>sbu</cpostag>
         <postag>sbu</postag>
         <deprel>SBU</deprel>
        </LM>
        <LM order="2">
         <form>forskningsstasjonen</form>
         <lemma>forskningsstasjon</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>SUBJ</deprel>
        </LM>
        <LM order="4">
         <form>selvberget</form>
         <lemma>selvberget</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>ub</LM>
          <LM>m/f</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>SPRED</deprel>
         <childnodes>
          <LM order="5">
           <form>med</form>
           <lemma>med</lemma>
           <cpostag>prep</cpostag>
           <postag>prep</postag>
           <deprel>ADV</deprel>
           <childnodes>
            <LM order="6">
             <form>strøm</form>
             <lemma>strøm</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>PUTFYLL</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="7">
         <form>,</form>
         <lemma>$,</lemma>
         <cpostag>&lt;komma&gt;</cpostag>
         <postag>&lt;komma&gt;</postag>
         <deprel>IK</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="11">
       <form>målinger</form>
       <lemma>måling</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>fem</LM>
        <LM>ub</LM>
        <LM>fl</LM>
       </feats>
       <deprel>DOBJ</deprel>
      </LM>
      <LM order="12">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="13">
       <form>overføre</form>
       <lemma>overføre</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>inf</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="14">
         <form>data</form>
         <lemma>data</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DOBJ</deprel>
         <childnodes>
          <LM order="16">
           <form>videobilder</form>
           <lemma>videobilde</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>fl</LM>
           </feats>
           <deprel>KOORD</deprel>
           <childnodes>
            <LM order="15">
             <form>og</form>
             <lemma>og</lemma>
             <cpostag>konj</cpostag>
             <postag>konj</postag>
             <feats>
              <LM>&lt;ikke-clb&gt;</LM>
             </feats>
             <deprel>KONJ</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
        <LM order="18">
         <form>i</form>
         <lemma>i</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ADV</deprel>
         <childnodes>
          <LM order="17">
           <form>også</form>
           <lemma>også</lemma>
           <cpostag>adv</cpostag>
           <postag>adv</postag>
           <deprel>ADV</deprel>
          </LM>
          <LM order="21">
           <form>periodene</form>
           <lemma>periode</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>mask</LM>
            <LM>be</LM>
            <LM>fl</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="19">
             <form>de</form>
             <lemma>de</lemma>
             <cpostag>det</cpostag>
             <postag>det</postag>
             <feats>
              <LM>dem</LM>
              <LM>fl</LM>
             </feats>
             <deprel>DET</deprel>
            </LM>
            <LM order="20">
             <form>lange</form>
             <lemma>lang</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>fl</LM>
              <LM>pos</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
            <LM order="24">
             <form>er</form>
             <lemma>være</lemma>
             <cpostag>verb</cpostag>
             <postag>verb</postag>
             <feats>
              <LM>pres</LM>
             </feats>
             <deprel>ATR</deprel>
             <childnodes>
              <LM order="22">
               <form>det</form>
               <lemma>det</lemma>
               <cpostag>pron</cpostag>
               <postag>pron</postag>
               <feats>
                <LM>nøyt</LM>
                <LM>ent</LM>
                <LM>pers</LM>
                <LM>3</LM>
               </feats>
               <deprel>FSUBJ</deprel>
              </LM>
              <LM order="23">
               <form>ikke</form>
               <lemma>ikke</lemma>
               <cpostag>adv</cpostag>
               <postag>adv</postag>
               <deprel>ADV</deprel>
              </LM>
              <LM order="25">
               <form>forskere</form>
               <lemma>forsker</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>appell</LM>
                <LM>mask</LM>
                <LM>ub</LM>
                <LM>fl</LM>
               </feats>
               <deprel>PSUBJ</deprel>
              </LM>
              <LM order="26">
               <form>på</form>
               <lemma>på</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ADV</deprel>
               <childnodes>
                <LM order="27">
                 <form>øya</form>
                 <lemma>øy</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>appell</LM>
                  <LM>fem</LM>
                  <LM>be</LM>
                  <LM>ent</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="28">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="3">
   <form>var</form>
   <lemma>være</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pret</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="2">
     <form>desember</form>
     <lemma>desember</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ubøy</LM>
     </feats>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="1">
       <form>1.</form>
       <lemma>1.</lemma>
       <cpostag>adj</cpostag>
       <postag>adj</postag>
       <feats>
        <LM>fl</LM>
        <LM>&lt;ordenstall&gt;</LM>
       </feats>
       <deprel>ATR</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="4">
     <form>det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>FSUBJ</deprel>
    </LM>
    <LM order="6">
     <form>år</form>
     <lemma>år</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>nøyt</LM>
      <LM>ub</LM>
      <LM>fl</LM>
     </feats>
     <deprel>SPRED</deprel>
     <childnodes>
      <LM order="5">
       <form>85</form>
       <lemma>85</lemma>
       <cpostag>det</cpostag>
       <postag>det</postag>
       <feats>
        <LM>fl</LM>
        <LM>kvant</LM>
       </feats>
       <deprel>DET</deprel>
      </LM>
     </childnodes>
    </LM>
    <LM order="17">
     <form>plantet</form>
     <lemma>plante</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pret</LM>
     </feats>
     <deprel>PSUBJ</deprel>
     <childnodes>
      <LM order="7">
       <form>siden</form>
       <lemma>siden</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="8">
       <form>Lars</form>
       <lemma>Lars</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>prop</LM>
        <LM>mask</LM>
       </feats>
       <deprel>SUBJ</deprel>
       <childnodes>
        <LM order="9">
         <form>Christensen</form>
         <lemma>Christensen</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>prop</LM>
         </feats>
         <deprel>FLAT</deprel>
        </LM>
        <LM order="16">
         <form>-ekspedisjonen</form>
         <lemma>-ekspedisjon</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>mask</LM>
          <LM>be</LM>
          <LM>ent</LM>
          <LM>samset</LM>
          
         </feats>
         <deprel>KOORD</deprel>
         <childnodes>
          <LM order="10">
           <form>og</form>
           <lemma>og</lemma>
           <cpostag>konj</cpostag>
           <postag>konj</postag>
           <feats>
            <LM>&lt;ikke-clb&gt;</LM>
           </feats>
           <deprel>KONJ</deprel>
          </LM>
          <LM order="11">
           <form>den</form>
           <lemma>den</lemma>
           <cpostag>det</cpostag>
           <postag>det</postag>
           <feats>
            <LM>dem</LM>
            <LM>mask</LM>
            <LM>ent</LM>
           </feats>
           <deprel>DET</deprel>
          </LM>
          <LM order="12">
           <form>første</form>
           <lemma>første</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>be</LM>
            <LM>ent</LM>
            <LM>pos</LM>
            <LM>&lt;ordenstall&gt;</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
          <LM order="13">
           <form>"</form>
           <lemma>$"</lemma>
           <cpostag>&lt;anf&gt;</cpostag>
           <postag>&lt;anf&gt;</postag>
           <deprel>FLAT</deprel>
          </LM>
          <LM order="14">
           <form>Norvegia</form>
           <lemma>Norvegia</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>FLAT</deprel>
          </LM>
          <LM order="15">
           <form>"</form>
           <lemma>$"</lemma>
           <cpostag>&lt;anf&gt;</cpostag>
           <postag>&lt;anf&gt;</postag>
           <deprel>FLAT</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="20">
       <form>flagget</form>
       <lemma>flagg</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>DOBJ</deprel>
       <childnodes>
        <LM order="18">
         <form>det</form>
         <lemma>det</lemma>
         <cpostag>det</cpostag>
         <postag>det</postag>
         <feats>
          <LM>dem</LM>
          <LM>nøyt</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DET</deprel>
        </LM>
        <LM order="19">
         <form>norske</form>
         <lemma>norsk</lemma>
         <cpostag>adj</cpostag>
         <postag>adj</postag>
         <feats>
          <LM>be</LM>
          <LM>ent</LM>
          <LM>pos</LM>
         </feats>
         <deprel>ATR</deprel>
        </LM>
       </childnodes>
      </LM>
      <LM order="22">
       <form>erklærte</form>
       <lemma>erklære</lemma>
       <cpostag>verb</cpostag>
       <postag>verb</postag>
       <feats>
        <LM>pret</LM>
       </feats>
       <deprel>KOORD</deprel>
       <childnodes>
        <LM order="21">
         <form>og</form>
         <lemma>og</lemma>
         <cpostag>konj</cpostag>
         <postag>konj</postag>
         <feats>
          <LM>clb</LM>
         </feats>
         <deprel>KONJ</deprel>
        </LM>
        <LM order="23">
         <form>øya</form>
         <lemma>øy</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>fem</LM>
          <LM>be</LM>
          <LM>ent</LM>
         </feats>
         <deprel>DOBJ</deprel>
        </LM>
        <LM order="24">
         <form>for</form>
         <lemma>for</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>OPRED</deprel>
         <childnodes>
          <LM order="26">
           <form>territorium</form>
           <lemma>territorium</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>appell</LM>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>ent</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="25">
             <form>norsk</form>
             <lemma>norsk</lemma>
             <cpostag>adj</cpostag>
             <postag>adj</postag>
             <feats>
              <LM>nøyt</LM>
              <LM>ub</LM>
              <LM>ent</LM>
              <LM>pos</LM>
             </feats>
             <deprel>ATR</deprel>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="27">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>har</form>
   <lemma>ha</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Bouvetøya</form>
     <lemma>Bouvetøya</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>prop</LM>
      <LM>fem</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="3">
     <form>status</form>
     <lemma>status</lemma>
     <cpostag>subst</cpostag>
     <postag>subst</postag>
     <feats>
      <LM>appell</LM>
      <LM>mask</LM>
      <LM>ub</LM>
      <LM>ent</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="4">
       <form>som</form>
       <lemma>som</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ATR</deprel>
       <childnodes>
        <LM order="6">
         <form>biland</form>
         <lemma>biland</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="5">
           <form>norsk</form>
           <lemma>norsk</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="7">
     <form>,</form>
     <lemma>$,</lemma>
     <cpostag>&lt;komma&gt;</cpostag>
     <postag>&lt;komma&gt;</postag>
     <deprel>IK</deprel>
    </LM>
    <LM order="8">
     <form>i</form>
     <lemma>i</lemma>
     <cpostag>prep</cpostag>
     <postag>prep</postag>
     <deprel>ADV</deprel>
     <childnodes>
      <LM order="9">
       <form>likhet</form>
       <lemma>likhet</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>fem</LM>
        <LM>ub</LM>
        <LM>ent</LM>
       </feats>
       <deprel>PUTFYLL</deprel>
       <childnodes>
        <LM order="10">
         <form>med</form>
         <lemma>med</lemma>
         <cpostag>prep</cpostag>
         <postag>prep</postag>
         <deprel>ATR</deprel>
         <childnodes>
          <LM order="11">
           <form>Dronning</form>
           <lemma>Dronning</lemma>
           <cpostag>subst</cpostag>
           <postag>subst</postag>
           <feats>
            <LM>prop</LM>
           </feats>
           <deprel>PUTFYLL</deprel>
           <childnodes>
            <LM order="12">
             <form>Maud</form>
             <lemma>Maud</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
              <LM>fem</LM>
             </feats>
             <deprel>FLAT</deprel>
            </LM>
            <LM order="13">
             <form>Land</form>
             <lemma>Land</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
             </feats>
             <deprel>FLAT</deprel>
            </LM>
            <LM order="15">
             <form>Peter</form>
             <lemma>Peter</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>prop</LM>
              <LM>mask</LM>
             </feats>
             <deprel>KOORD</deprel>
             <childnodes>
              <LM order="14">
               <form>og</form>
               <lemma>og</lemma>
               <cpostag>konj</cpostag>
               <postag>konj</postag>
               <feats>
                <LM>&lt;ikke-clb&gt;</LM>
               </feats>
               <deprel>KONJ</deprel>
              </LM>
              <LM order="16">
               <form>I</form>
               <lemma>I</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>&lt;romertall&gt;</LM>
               </feats>
               <deprel>FLAT</deprel>
              </LM>
              <LM order="17">
               <form>Øy</form>
               <lemma>Øy</lemma>
               <cpostag>subst</cpostag>
               <postag>subst</postag>
               <feats>
                <LM>prop</LM>
               </feats>
               <deprel>FLAT</deprel>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
  <LM order="2">
   <form>betyr</form>
   <lemma>bety</lemma>
   <cpostag>verb</cpostag>
   <postag>verb</postag>
   <feats>
    <LM>pres</LM>
   </feats>
   <deprel>FINV</deprel>
   <childnodes>
    <LM order="1">
     <form>Det</form>
     <lemma>det</lemma>
     <cpostag>pron</cpostag>
     <postag>pron</postag>
     <feats>
      <LM>nøyt</LM>
      <LM>ent</LM>
      <LM>pers</LM>
      <LM>3</LM>
     </feats>
     <deprel>SUBJ</deprel>
    </LM>
    <LM order="5">
     <form>er</form>
     <lemma>være</lemma>
     <cpostag>verb</cpostag>
     <postag>verb</postag>
     <feats>
      <LM>pres</LM>
     </feats>
     <deprel>DOBJ</deprel>
     <childnodes>
      <LM order="3">
       <form>at</form>
       <lemma>at</lemma>
       <cpostag>sbu</cpostag>
       <postag>sbu</postag>
       <deprel>SBU</deprel>
      </LM>
      <LM order="4">
       <form>territoriet</form>
       <lemma>territorium</lemma>
       <cpostag>subst</cpostag>
       <postag>subst</postag>
       <feats>
        <LM>appell</LM>
        <LM>nøyt</LM>
        <LM>be</LM>
        <LM>ent</LM>
       </feats>
       <deprel>SUBJ</deprel>
      </LM>
      <LM order="6">
       <form>under</form>
       <lemma>under</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>SPRED</deprel>
       <childnodes>
        <LM order="8">
         <form>herredømme</form>
         <lemma>herredømme</lemma>
         <cpostag>subst</cpostag>
         <postag>subst</postag>
         <feats>
          <LM>appell</LM>
          <LM>nøyt</LM>
          <LM>ub</LM>
          <LM>ent</LM>
         </feats>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="7">
           <form>norsk</form>
           <lemma>norsk</lemma>
           <cpostag>adj</cpostag>
           <postag>adj</postag>
           <feats>
            <LM>nøyt</LM>
            <LM>ub</LM>
            <LM>ent</LM>
            <LM>pos</LM>
           </feats>
           <deprel>ATR</deprel>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
      <LM order="9">
       <form>,</form>
       <lemma>$,</lemma>
       <cpostag>&lt;komma&gt;</cpostag>
       <postag>&lt;komma&gt;</postag>
       <deprel>IK</deprel>
      </LM>
      <LM order="10">
       <form>uten</form>
       <lemma>uten</lemma>
       <cpostag>prep</cpostag>
       <postag>prep</postag>
       <deprel>ADV</deprel>
       <childnodes>
        <LM order="11">
         <form>å</form>
         <lemma>å</lemma>
         <cpostag>inf-merke</cpostag>
         <postag>inf-merke</postag>
         <deprel>PUTFYLL</deprel>
         <childnodes>
          <LM order="12">
           <form>være</form>
           <lemma>være</lemma>
           <cpostag>verb</cpostag>
           <postag>verb</postag>
           <feats>
            <LM>inf</LM>
           </feats>
           <deprel>INFV</deprel>
           <childnodes>
            <LM order="14">
             <form>del</form>
             <lemma>del</lemma>
             <cpostag>subst</cpostag>
             <postag>subst</postag>
             <feats>
              <LM>appell</LM>
              <LM>mask</LM>
              <LM>ub</LM>
              <LM>ent</LM>
             </feats>
             <deprel>SPRED</deprel>
             <childnodes>
              <LM order="13">
               <form>en</form>
               <lemma>en</lemma>
               <cpostag>det</cpostag>
               <postag>det</postag>
               <feats>
                <LM>mask</LM>
                <LM>ent</LM>
                <LM>kvant</LM>
               </feats>
               <deprel>DET</deprel>
              </LM>
              <LM order="15">
               <form>av</form>
               <lemma>av</lemma>
               <cpostag>prep</cpostag>
               <postag>prep</postag>
               <deprel>ATR</deprel>
               <childnodes>
                <LM order="17">
                 <form>Norge</form>
                 <lemma>Norge</lemma>
                 <cpostag>subst</cpostag>
                 <postag>subst</postag>
                 <feats>
                  <LM>prop</LM>
                 </feats>
                 <deprel>PUTFYLL</deprel>
                 <childnodes>
                  <LM order="16">
                   <form>kongeriket</form>
                   <lemma>kongerike</lemma>
                   <cpostag>subst</cpostag>
                   <postag>subst</postag>
                   <feats>
                    <LM>appell</LM>
                    <LM>nøyt</LM>
                    <LM>be</LM>
                    <LM>ent</LM>
                   </feats>
                   <deprel>APP</deprel>
                  </LM>
                 </childnodes>
                </LM>
               </childnodes>
              </LM>
             </childnodes>
            </LM>
           </childnodes>
          </LM>
         </childnodes>
        </LM>
       </childnodes>
      </LM>
     </childnodes>
    </LM>
    <LM order="18">
     <form>.</form>
     <lemma>$.</lemma>
     <cpostag>clb</cpostag>
     <postag>clb</postag>
     <feats>
      <LM>&lt;punkt&gt;</LM>
     </feats>
     <deprel>IP</deprel>
    </LM>
   </childnodes>
  </LM>
 </body>
</conll>
